### ISSUE TITLE
Clarifying section move/removal; requesting consensus on PR approval/merge approach 

### ISSUE THREAD

**Issue by dnsguru** [publicsuffix/list#1007]
A number of requests within the Issue/PR queue are for removals or section moves.

@sleevi @weppos would like your support or comments on this approach as I process the backlog and I'd like to use it as a process going forward

With the _PSL TXT entries providing a strong connection of authority verification to a given PR#, I would like to propose a review process clarification that seems to be effective in aiding volunteer cycle throughput.

I am glad to narrow the scope of this to just removal requests, but these seem similar, so I am optimistic that they could be agreed together.

**The scope:**

1. list entries and comments, which
1.1. requests to remove a listed domain from the private section, or
1.2 requests for section moves that take a sub-delegation of an ICANN section entry to the PRIVATE section, 

**The proposal:**

In the presence of the following review elements, A PR can get approved and Squash-MERGED by where Assignee = Reviewer

- a validated lookup of the _PSL TXT record entry matching a given PR# URI for each effected change, and
- a well articulated, clear rationale, and
- the rationale goes well beyond just a desire to work around CA constraints, and
- no public policy listing at a registry which conflicts, and
- passed CI tests, and
- no objections

**Comment by sleevi** [comment]
It might be helpful to highlight issues/PRs here where you think it would
have helped here. Some of the proposed steps involve subjective judgement,
so it might be useful to concretely discuss.

**Comment by dnsguru** [comment]
> It might be helpful to highlight issues/PRs here where you think it would
> have helped here

Example where this worked well:
#971 

Examples where the record validation is causing longer review due to different missing elements:
#924 (and related #977)
#984 (an addition that also has a removal) 

> Some of the proposed steps involve subjective judgement
Well said, and true.  

Trying to preserve the flexibility to cover the majority of what we seem to be seeing as inputs seems like it requires some subjectivity.  The submissions do not seem to be similarly shaped, and not all have 90 degree angles and four sides.  

Do you have some ideas on tightening that up?  

The core objective I had here is to reduce the frictional aspects of the process while having some parameters and structure to work within

**Comment by dnsguru** [comment]
After spending some time working through the backlog of Issue/PR and reviewing the past issue/PR, this seems to be working.  If someone takes on the assignment and can move it forward, and there are no pause conditions, that it may be ok to proceed to be the assignee/approver/merger for velocity's sake. 

Maybe instead of having this issue be stated as a means to carve out a clear path through a presumptive NO, we instead identify the conditions that we use as something we use to identify those Issue/PR where we MUST incorporate a second or third opinion.    Such situations would be where some level of subjectivity is present or the rationale's confusing.
