### ISSUE TITLE
Could we use project board method to separate list update PRs from administrata

### ISSUE THREAD

**Issue by dnsguru** [publicsuffix/list#1008]
I have been working through the backlog of PR/Issues, and it seems like there are some general buckets:

- List Updates
- Project/Team Discussion, Documentation & Site
- Project/Tools, Automation, Generation & Test

This is not exhaustive. Open to what these are called but would want it narrow.

It would greatly help organize stuff a bit to perhaps go through and assign issues and PR to projects.

No project assignment = needs a look

I am not proposing epochs, timelines, sprints, or milestones at this time.

@sleevi @weppos could this work, and also would it break or impact any automation

**Comment by dnsguru** [comment]
@sleevi @weppos are y'all opposed to me creating a project so I can project board the issues and PR to keep them organized?

**Comment by sleevi** [comment]
This seems like a lot of work for limited value. I’m concerned about the
amount of overhead being introduced, but I appreciate the continued
volunteering.

However, I’m not opposed, assuming it’s fine for us to continue to ignore
it. If this requires us to adapt new workflows, I don’t think it’s worth
the investment compared to the end goal: which is automating ourselves away.

**Comment by dnsguru** [comment]
I get that project and lanes might be a bit much.  Just seeking a method to
do faster reviews without opening up stuff I didnt need to and pick up
where I left off or need to nudge folks on

I would like to set up either labels or use project to build some
stratification to pr and issues. Either one could work, but projects have
some automation steps that cut down on clicking

I tend to focus on the pr and issues related to entries in the list

There are pr and issues like this one we are updating which are meta or
documentation

There are many that are related to the testing/automation, documentation or
other stuff unrelated to the list entries which I dont have as much to
contribute on.

Selfishly, I see labels or projects as the path but I am one of many here
and dont want to proclaimeth anything

**Comment by dnsguru** [comment]
This is kind of related to #967 - I work through the web interface and am looking to optimize the workflow on the requests that come through and getting them through the funnel efficiently.

**Comment by dnsguru** [comment]
Here is a summary of the PR/Items as of this morning (I've closed a number of these, since but it shows the split):

Within them, I'd like to be able to know where they are at in stages so that I can demonstrate a bias for G.S.D. (gettin' stuff done) without having to open each one, read it, and do stuff and repeat.  I don't want to proclaim or define a process, but rather just leverage some of the benefits we have within GitHub's UI to help make the volunteer cycle more efficient.

I have gathered the PRs and Issues together and split them into two buckets
- List Edits
- Meta - Process Format or Question

My initial ask in #967 was to use labels to provide a visual indicator on the PR or Issue summary results page to at least flag ICANN or PRIVATE - which would infer "List Edit".  It does not solve the 'what needs to happen next' part, which is where project board might be helpful.  This is espcaially true in the Meta stuff, which has a much longer tail on it.  

This doesn't really track what stage they are at - and I think that will be helpful.  I have had abundant cycles in the past two weeks, but will return to the time constraints of dayjob [hopefully] soon, which means dropping in with less frequency.   We all get cycles to invest when we get them.  Being able to see where to step in and quickly move some things forward where appropriate is something I think can be good for all of us.   In the past, I've lost volunteer time to getting acclimated or figuring out what needs what.


Type | ID | PR/Issue | Title
-- | -- | -- | --
List Edit | #1000 | PR | add bitbridge.net to private   section
List Edit | #1004 | PR | Add kasserver.com / test-account.com to Private Section
List Edit | #1010 | PR | Add clic2000.net to Private Section
List Edit | #146 | Issue | krakow.pl (grandfathered) regional domain
List Edit | #601 | Issue | Wrong domainname in .ua geographic names section
List Edit | #646 | Issue | wroclaw.pl is a domain no longer a suffix
List Edit | #742 | Issue | .NP question
List Edit | #788 | Issue | nsw.gov.au (and nt.gov.au) incorrectly commented out
List Edit | #853 | PR | Third level РУС/xn--p1acf domains  question
List Edit | #876 | PR | Add blmgroep.nl as Private Domain  question r=sleevi
List Edit | #890 | PR | update public suffix for .ST zone  waiting-followup
List Edit | #912 | PR | Add dyndns.dappnode.io    pending-validation
List Edit | #915 | PR | add localzone.xyz
List Edit | #958 | PR | Add shopware.store domain    question
List Edit | #968 | PR | Add curv.dev to public_suffix_list.dat
List Edit | #969 | PR | Add kyma.ondemand.com domain and subdomains
List Edit | #973 | PR | Add *.owo.codes
List Edit | #974 | PR | Add seidat.net private domain
List Edit | #977 | PR | Removal of education.tas.edu.au  pending-validation waiting-followup
List Edit | #978 | PR | Add panel.gg and daemon.panel.gg
List Edit | #983 | Issue | Align .ss with registry.nic.ss listing and confirm with   Registry Admin
List Edit | #984 | PR | Added gentlentapis.com
List Edit | #987 | PR | Add cn.vu
List Edit | #990 | PR | Add dr.city.kharkov.ua
List Edit | #993 | PR | Add mintere.site
List Edit | #994 | PR | Add g.vbrplsbx.io domain
List Edit | #998 | PR | Add na4u.ru to list
List Edit | #999 | PR | Add Fabrica apps domain: onfabrica.com
Meta - Process Format or Question | #1007 | Issue | Clarifying section move/removal; requesting consensus on PR   approval/merge approach
Meta - Process Format or Question | #1008 | Issue | Could we use project board method to separate list update PRs   from administrata
Meta - Process Format or Question | #145 | Issue | Clarify number and position of wildcard labels
Meta - Process Format or Question | #208 | Issue | Inconsistent leading dot tests for "example.com"
Meta - Process Format or Question | #27 | Issue | Needs a processing model
Meta - Process Format or Question | #570 | Issue | Side effect of "default rule" on disallowed TLDs   question
Meta - Process Format or Question | #602 | Issue | Simplify by removing single label names
Meta - Process Format or Question | #603 | PR | Added a test for dns records
Meta - Process Format or Question | #671 | Issue | Better document the PSL roadmap and needs
Meta - Process Format or Question | #694 | Issue | The spec doesn't seem clear on how to handle   "incomplete" hostnames
Meta - Process Format or Question | #792 | Issue | Trailing dots and the PSL.
Meta - Process Format or Question | #798 | Issue | When a domain which is part of this list is wrongly added to   Google Safe Browsing phishing list
Meta - Process Format or Question | #806 | Issue | Provide the list in a structured format (e.g., JSON)
Meta - Process Format or Question | #848 | Issue | Clarify how to run the tests
Meta - Process Format or Question | #864 | Issue | Clarification of `uk.com` test
Meta - Process Format or Question | #887 | Issue | Clarify the expected public suffix of leading dot domains
Meta - Process Format or   Question | #982 | Issue | Update documentation to reflect prioritization and democratic   flow of processing requests

**Comment by sleevi** [comment]
Thanks! This is all super helpful.

Yeah, like I said, I'm not opposed, as long as it's not introducing or
adding steps to triage and label stuff. I'm bad enough with forgetting to
set r=sleevi vs indicating Approval on the merge request, and so just
trying to avoid having to do extra steps. Similarly, just trying to
understand the goal to make sure we're aligned, but strongly supportive of
whatever helps you personally achieve that if the goals are aligned :)

>

**Comment by dnsguru** [comment]
@sleevi I have this set up - the project boards have actions that move the cards on the kanban columns.  **I have a q: how is r= intended to work as a label?**

**Comment by dnsguru** [comment]
OK so I have added two projects to publicsuffix organization:

- List Add/Mod/Del
- Meta Topics, Questions, Process

The first, **List Add/Mod/Del**, is for the general PR/Issues submitted inside of publicsuffix/list
The second, **Meta Topics, Questions, Process**, is basically all not fitting in the first one, and it extends to publicsuffix/publicsuffix.org as well.

They each have kanban type cards for each issue or pr, and columns for their stage of progress to quickly see visually where things are.   There is automation within GitHub that will migrate the majority of what our activity is, with the exception "awaiting feedback"  where we have a q or need feedback from each other or the submitting party.

- "to-do"
- "in progress"
- "awaiting feedback"
- "done / won't"

I don't expect this to impact any of our process, other than to more quickly identify the items that are already being worked on to avoid losing time on those.
