### ISSUE TITLE
remove .presse.ml - ICANN Seccion

### ISSUE THREAD

**Issue by nic-ml** [publicsuffix/list#1009]
Please remove presse.ml from ICANN's list of public suffixes, as we will close it and migrate our customers to the .orgj.org suffix.

www.whoisprivacy.orgj.org

**Comment by nic-ml** [comment]
Note: I don't know how to use PSL, so I request that .presse.ml be removed from ICANN's list of public suffixes.

**Comment by nic-ml** [comment]
Note 2:

Domains used by organizations in languages such as Maltese, Slavic, Serbian, Polish and etc ... will be migrated to the .orgj.org suffix.

Domains used by LGBT + / Gay NGOs will be migrated to the suffix
.gays.lgbt

.presse.ml will be retired in 5 days and will be unavailable.

**Comment by dnsguru** [comment]
(Related #956)

@nic-ml Please create a pull request for these changes.

The pull request needs to include the changes desired, and should be
accompanied by a DNS entry in presse.ml zone (and others mentioned) to
validate the authority to make the requested changes.

**Comment by nic-ml** [comment]
@dnsguru I don't know how to create a PR.

I know how to create entries in the DNS of presse.ml or orgj.org/gays.lgbt, if necessary.

So I opened this Issue, because I don't know how to do a PR. I read the instructions, but I didn't quite understand.

**Comment by dnsguru** [comment]
Please follow this the detailed instructions from the wiki [link](https://github.com/publicsuffix/list/wiki/Guidelines)

If this is not clear and technical assistance is needed, have technical person familiar with github perform these steps on your behalf.  There is validation included within them, to help ensure that the person who operates the items that are submitted is involved in the process.

The request to remove the presse.ml should probably be in a pull request by itself, and the other related domains a separate request, as those would belong in the PRIVATE section.

In looking at the prior request #956 there was some discussion about the removal of this record.  In reviewing this current issue report the case of attempting to validate presse.ml by policy or whois, it was not possible. 

Hopefully the information in that wiki will assist in the process of submitting the pull request.

**Comment by nic-ml** [comment]
@dnsguru I am new to the company and the only person who knows how to do this, is on vacation and is no longer connected to this project.

I know I have to make record edits in the DNS for presse.ml, but I'm not familiar with Github.

If I can't, is there a problem with presse.ml remaining in the ICANN suffix section?

THANKS

**Comment by dnsguru** [comment]
Is the name being released to a party that will use it directly as a URL (ie http://presse.ml) or being released to the general pool of registration so that anyone can register the domain name presse.ml?

Or is it being turned off and held aside as a restricted name that shall not be possible to register?

The new registrant would probably want to remove the name from the PSL, as it will change how cookies, DOM, certificates or other things behave - and make it function differently than other domains.

Because it was treated like .com.ml essentially, if there are delegations currently below presse.ml (example bbc.presse.ml, if that exists) removal could effect the behavior of cookies and how Certificate authorities might process renewals for them or new requests for them.

**Comment by nic-ml** [comment]
@dnsguru Until dawn today, the domain registration website was www.whoisprivacy.presse.ml (see web.archive.org), but I completely deleted the site and registrars were notified about disqualification.

.Presse.ml was being abused for porn sites.

The company decided to migrate the domains to .gays.lgbt and disable presse.ml completely

A person using bbc.presse.ml will now have a bbc.gays.lgbt domain.

In the case of .com.ml, the suffix is reserved for AGETIC.

In the case of presse.ml it will simply be disabled.

**Comment by nic-ml** [comment]
@dnsguru presse.ml is being deactivated according to the suffix exchange program.

presse.ml will be replaced by gays.lgbt!

**Comment by nic-ml** [comment]
@dnsguru I know that the gay.lgbt domain has been reserved and is inactive by Afilias.

Therefore, our company started using gays.lgbt for some time and this year, after assuming the suffix presse.ml again and detecting abuse or improper use, decided to terminate it and replace it with gays.lgbt.

 I know that each domain has an owner.

Example:

bar.gays.lgbt belongs to the owner X

example.gays.lgbt belongs to owner Y

**Comment by dnsguru** [comment]
I personally applaud things being done to enhance diversity, but bringing it back to the binary matter of what to do here, I am not sure what we do here about this particular Issue report or how this all is related to the task at hand of either closing this issue.

The PSL has absolutely nothing to do with redirection or domain replacement.

If the domain presse.ml is being expired, there is not an impact to you that would not exist in DNS.

It seems like the right thing to do is to close this issue.  

IF the objective is seeking to submit those other domain names, they would be in the PRIVATE section and that's best handled through a different request.

**Comment by nic-ml** [comment]
Hello, it is no longer necessary to remove the suffix .presse.ml, as it will be managed by an organization that is negotiating the purchase of other Suffixes.

In this case is it necessary to open a Pull Request?

Please disregard the old Pull Request #1009, as some domain owners did not accept the exchange of Suffixes.

**Comment by dnsguru** [comment]
OK and thank you for the follow-up
