### ISSUE TITLE
Security issue for nodebalancer.linode.com

### ISSUE THREAD

**Issue by Zenexer** [publicsuffix/list#1018]
https://github.com/publicsuffix/list/blob/ff6fcea0f91830e909a8ea80c81ac101748d0c0b/public_suffix_list.dat#L12170-L12173

This is incorrect.  Example hostname:

```
nb-104-200-22-1.dallas.nodebalancer.linode.com
```

With the current rule, the public suffix for this would be `nodebalancer.linode.com`.  That means cookies could be shared across `dallas.nodebalancer.linode.com`.

The rule should be (or should include):

```
*.nodebalancer.linode.com
```

**Comment by sleevi** [comment]
Thanks for reporting this. This does indeed seem to be a bug, but one you should report to Linode, as they’re the only ones who can authorize the change.

**Comment by Zenexer** [comment]
Sent email to security@linode.com directing them to this issue.
