### ISSUE TITLE
Some TLDs in PSL are not in IANA Root DB

### ISSUE THREAD

**Issue by umairkhan-dev** [publicsuffix/list#1021]
Sorry, this is more like me asking about **why** instead of an issue.

IANA has a list of TLDs at https://www.iana.org/domains/root/db and https://data.iana.org/TLD/tlds-alpha-by-domain.txt
I noticed that there are some TLDs in ICANN section of PSL that are not listed in IANA's list.

For Example.

1.  ايران   (xn--mgba3a4fra)
2.  澳门   (xn--mix082f)
3.  پاكستان   (xn--mgbai9a5eva00b)
4.  السعودیة   (xn--mgberp4a5d4a87g)
5.  السعودیۃ   (xn--mgbqly7c0a67fbc)
6.  السعوديه   (xn--mgbqly7cvafr)
7.  سوريا   (xn--mgbtf8fl)
8.  臺灣   (xn--nnx388a)
9.  اليمن   (xn--mgb2ddes)

... and some more.

Please, I am confused, why is that so.?

**Comment by dnsguru** [comment]
Thanks for the question @umairkhan-dev 

Please see [ICANN's ccTLD IDN Fast Track](https://www.icann.org/resources/pages/string-evaluation-completion-2014-02-19-en)  Specifically, look at the table, fourth column,
I believe, working from memory of the rationale we used at the time, was that many or most of the strings listed above may have been identified by ICANN as Desired Variants of delegated ccTLD IDNs and were defined at the time by the IANA/ICANN as part of their ccTLD notices.  Since that time there has been more structure added to the process by ICANN and the IANA, but the strings remain in the PSL to avoid disruption to any of the affected communities.  The respective authority for each ccTLD IDN may request their removal.

**Comment by umairkhan-dev** [comment]
@dnsguru Thanks alot for your reply. Sorry, I am new to _TLDs_ as developer and I am making a small tool to check if given address has proper _TLD_. So I got my primary list from **IANA** and then had an intro with **PSL** and got confused.

I have another question. As mentioned [here](https://www.icann.org/resources/pages/string-evaluation-completion-2014-02-19-en).
>The desired variant string(s) are strings allocated to the requester. This does not mean that they will be delegated in the DNS root zone. They will be allocated to the requester in order to be reserved to the entitled manager for potential future delegation in the DNS root zone.

Is it safe to assume that the list provided by **IANA** ([here](https://www.iana.org/domains/root/db)) is final for the time being, and if a **desired variant string** makes way in **DNS root zone**, the **IANA** list will be updated.

**Comment by dnsguru** [comment]
Appreciate the questions, as these all build documentation for future eyes and others who want to know more.

> Above quoted as mentioned here.
> Is it safe to assume that the list provided by IANA (here) is final for the time being, and if a desired variant string makes way in DNS root zone, the IANA list will be updated.

Wise to not treat it as static.  IANA of course is most appropriate party to answer a question about the IANA list, but it is updated as time progresses and ccTLDs introduce IDN namespace (or new languages or variants).  The most significant change was the namespace expansion from the 2012 nTLD round, and there are occasional changes in the ccTLD space.

> There are some TLDs which work slightly different than how they should work.
> for example. *.bd (// bd : https://en.wikipedia.org/wiki/.bd). Asterisk (*) defines, I assume, that any sub-tld can be used with .bd, however .bd only allows the ones mentioned in their wiki page.

There likely may exist legacy entries in the PSL which may not be aligned to their current operations.  TLD administrators are encouraged to review their entries and update them.  Where volunteers in the community see a TLD needing to be updated, please encourage the respective TLD administrators to submit updates.

**Comment by umairkhan-dev** [comment]
@dnsguru Lots of thanks for your reply. It did clear some confusions.
For now, I have nothing to ask more. But I'll bug you in case of more questions /  confusions.
Thanks again.
