### ISSUE TITLE
Modify request template / documentation to include related historic Issue/PR #s

### ISSUE THREAD

**Issue by dnsguru** [publicsuffix/list#1027]
In reviewing submissions that modify or update previous approved submissions, I am noticing that having the submitting party furnish the historic PR or Issue numbers provides the community volunteers a more efficient process of review.

The most recent was #1025 where I had to look up #730 that they were expanding.  If we update the template and documentation to request that the submitting party include prior references, including approved and declined PR and Issues, it will help things move more efficiently, and it seems like a simple ask.

**Comment by sleevi** [comment]
Yeah, I can see no harm in asking, as long as we're not requiring. It's definitely useful to see how the example domains are changing (i.e. what doesn't work vs what they want to work)

**Comment by dnsguru** [comment]
Addressed in #1116
