### ISSUE TITLE
Disregard Issue #1009

### ISSUE THREAD

**Issue by nic-ml** [publicsuffix/list#1028]
Hello, it is no longer necessary to remove the suffix .presse.ml, as it will be managed by an organization that is negotiating the purchase of other Suffixes.

In this case is it necessary to open a Pull Request?

Please disregard the old Issue #1009, as some domain owners did not accept the exchange of Suffixes.

https://github.com/publicsuffix/list/issues/1009

**Comment by dnsguru** [comment]
OK thank you
