### ISSUE TITLE
agrica.za appears to be a typo

### ISSUE THREAD

**Issue by erikvanderpoel** [publicsuffix/list#103]
agrica.za appears to be a typo in:

http://www.zadna.org.za/content/page/domain-information

That same page mentions AGRIC.ZA, which appears to be correct:

http://google.com/search?q=site:agric.za

I have notified the za registry.

**Comment by erikvanderpoel** [comment]
Date: Wed, 13 Jan 2016 09:28:47 +0200
Subject: Re: agrica.za appears to be typo
From: Vika Mpisane <vika@zadna.org.za>
To: Erik van der Poel <erikv@google.com>
CC: Cedrick Lumadi <cedrick@zadna.org.za>

Hi Erik,

Thanks for picking this up. It's definitely a typo:-( We will correct it in
due course.

Regards,

Vika Mpisane  |  ZADNA  |  +27 11 314 0077 ext. 602


From:  Erik van der Poel <erikv@google.com>
Date:  Wednesday 13 January 2016 at 02:23
To:  <questions@zaDNA.org.za>
Subject:  agrica.za appears to be typo

Hello,

Your document:

http://www.zadna.org.za/content/page/domain-information

mentions both agrica.za <http://agrica.za>  and agric.za <http://agric.za>
but the former seems to be a typo (error), while the latter exists. Is that
right? I will notify publicsuffix.org <http://publicsuffix.org> .

Erik van der Poel

**Comment by weppos** [comment]
Thanks Eric, I fixed the typo.
