### ISSUE TITLE
Repo access rights for creating feature branches/PRs

### ISSUE THREAD

**Issue by kiddhustle** [publicsuffix/list#1034]
Hi

I don't see anywhere a procudure to request access rights so that contributors can create a branch to create a PR with.

Or is the procesdure to fork the repo then create feature branch/PR that way (without having to be granted access rights to the main repo)?

**Comment by weppos** [comment]
> Or is the procesdure to fork the repo then create feature branch/PR that way (without having to be granted access rights to the main repo)?

Yes, that's the expected behavior as per the GitHub documentation linked in the Guidelines.

**Comment by kiddhustle** [comment]
OK thanks for clarifying
