### ISSUE TITLE
co.ua TLD missing

### ISSUE THREAD

**Issue by ll1t** [publicsuffix/list#1038]
Hi there,

first of all, thanks for your work!

While using tldextract in Python, which relies on PSL, I noticed that co.ua is missing on the PSL, although apparently actively sold and used. Is it possible to amend the PSL to reflect the existence of this TLD?

Cheers!

**Comment by dnsguru** [comment]
Please contact the operator of this to submit the string, as it will
require them to perform some validation and verification.

**Comment by dnsguru** [comment]
@dk379 we removed dominic.ua in #1050, please comment on this co.ua - is it something that the ccTLD is directly running?

Also look at #990 to confirm please

**Comment by dk379** [comment]
On 12 Jun 2020, at 11:01, Jothan Frakes <notifications@github.com> wrote:﻿
> @dk379 we removed dominic.ua in #1050, please comment on this co.ua - is it something that the ccTLD is directly running?
> 
> Also look at #990 to confirm please
> 
> 
> 
would do; we do amend list of our public domains and I would compare PSL and our data.

comment about co.ua - we are not running this domain as part of UA public domain list.
It is delegated to private registrar, called nic.ua.  I think perhaps somebody got confused 
IANA/ICANN domains and private domains with public registration. Do you have changelog?

—dk@
