### ISSUE TITLE
AWS ap-northeast-2 for compute and S3 to Private Domains

### ISSUE THREAD

**Issue by lawells** [publicsuffix/list#105]
Please add the following domains:

ap-northeast-2.compute.amazonaws.com
s3.ap-northeast-2.amazonaws.com
s3-ap-northeast-2.amazonaws.com

http://docs.aws.amazon.com/general/latest/gr/rande.html#s3_region

<pre>// Amazon Elastic Compute Cloud: https://aws.amazon.com/ec2/
// Submitted by Luke Wells <lawells@amazon.com> 2016-02-05
ap-northeast-1.compute.amazonaws.com
ap-northeast-2.compute.amazonaws.com
ap-southeast-1.compute.amazonaws.com
ap-southeast-2.compute.amazonaws.com
cn-north-1.compute.amazonaws.cn
compute.amazonaws.cn
compute.amazonaws.com
compute-1.amazonaws.com
eu-west-1.compute.amazonaws.com
eu-central-1.compute.amazonaws.com
sa-east-1.compute.amazonaws.com
us-east-1.amazonaws.com
us-gov-west-1.compute.amazonaws.com
us-west-1.compute.amazonaws.com
us-west-2.compute.amazonaws.com
z-1.compute-1.amazonaws.com
z-2.compute-1.amazonaws.com</pre>

<pre>// Amazon S3 : https://aws.amazon.com/s3/
// Submitted by Luke Wells <lawells@amazon.com> 2016-02-05
s3.amazonaws.com
s3-ap-northeast-1.amazonaws.com
s3.ap-northeast-2.amazonaws.com
s3-ap-northeast-2.amazonaws.com
s3-ap-southeast-1.amazonaws.com
s3-ap-southeast-2.amazonaws.com
s3-external-1.amazonaws.com
s3-external-2.amazonaws.com
s3-fips-us-gov-west-1.amazonaws.com
s3-eu-central-1.amazonaws.com
s3-eu-west-1.amazonaws.com
s3-sa-east-1.amazonaws.com
s3-us-gov-west-1.amazonaws.com
s3-us-west-1.amazonaws.com
s3-us-west-2.amazonaws.com
s3.cn-north-1.amazonaws.com.cn
s3.eu-central-1.amazonaws.com</pre>

**Comment by lawells** [comment]
Hi,
Any chance we can have someone make this addition?
Thanks!

**Comment by weppos** [comment]
@lawells do you work at Amazon or are you affiliated with them?

**Comment by lawells** [comment]
weppos@ Yes, I do work at Amazon!

**Comment by weppos** [comment]
@lawells we need your email to verify the request. Also, do you happen to know if the people who previously requested the other suffixes are aware of your request?

**Comment by lawells** [comment]
@weppos - sure. lawells@amazon.com for the verification. Both Eric and Osman are aware.

**Comment by breadtk** [comment]
Commit 53940ee66c1ee03a3d1d5773656e55463280c6c1 looks good to me. Also confirming that @lawells is an employee at this time.
