### ISSUE TITLE
Add SLDs .NAME

### ISSUE THREAD

**Issue by diogoramires** [publicsuffix/list#1087]
please add Verisign reserved domains to .name, so that my domains work well!

* .asia.name
* .europe.name
*.unitedkingdom.name
*.mercosul.name
* .cu.name
* .web.name
* .americas.name
* .ar.name
* .days.name
* .ramires.name

Thank you!

**Comment by diogoramires** [comment]
I don't know what to do, as these slds are operated by Verisign.

**Comment by dnsguru** [comment]
Verisign would opt to do this (or not) as the administrative operator of the DNS for these.  That's the first place to inquire.  This should be closed, but you can reference it by URL to them when / if you contact them to pursue this.

They would need to open a Pull Request in order for this to proceed.  

IF **YOU** are the owner / registrant of these domain names specifically, **YOU** (or your DNS provider) could open a pull request to add these into the private section and establish the appropriate DNS TXT records to demonstrate / validate authority/administration of the names.

The validation stuff protects other users from having some random third party make changes that impact their _stuff_.

**Comment by diogoramires** [comment]
@dnsguru Verisign will not do this, as support said, there are more than 1,000 SLDs in use.

However, thank you for your attention!

**Comment by dnsguru** [comment]
The change could impact other registrants, so we err on the side of caution
and have rhe administrator be the party that makes these changes.

Thanks for understanding, stay safe and be healthy.
