### ISSUE TITLE
Make a working test suite

### ISSUE THREAD

**Issue by gerv** [publicsuffix/list#11]
We should assemble the fragments of code in the tests/ directory into an actual runnable test suite which checks the file for common errors and makes it as unlikely as possible that we will break anyone's tree or parser.

This bug covers testing the things the existing tests cover. We should file additional bugs for other things we might like to test.

**Comment by weppos** [comment]
It probably makes sense. We just broke it a few days ago, a patch was merged today (#14).

@gerv any preference about the language? I  may work on something, but I'm afraid my preferences may not meet yours or other devs.

I would most likely code something on Go or Ruby.

**Comment by gerv** [comment]
weppos: it needs to be something easily runnable on a variety of platforms. I'd prefer Python as many people know it, and the code won't be all that complex. But given that I don't have time to do it, I'd much rather you wrote it in Ruby than no-one wrote it :-)

**Comment by szepeviktor** [comment]
I suggest using Travis.

**Comment by malkusch** [comment]
> We just broke it a few days ago

You did it again (#21). +1 for CI (e.g. travis).

**Comment by szepeviktor** [comment]
There could be a regexp check for the list too.

- stripping emty and comment line
- `^\(\S\+\.)\+\S\+\$`

**Comment by szepeviktor** [comment]
Please consider prepending this line to the tests:
```bash
{ echo '<?php '; cat tests/test_psl.txt; } | php -l || echo "Invalid code in text file."
```

**Comment by weppos** [comment]
I prepared a preliminary test suite in #123. Feedback are welcome.

**Comment by weppos** [comment]
#123 was superseded by #130, which is now merged into master. A `Makefile` was added in #171 to run the tests locally using `make test` (or simply `make`).
