### ISSUE TITLE
If local-part is missing parse_email() validates successfully 

### ISSUE THREAD

**Issue by Dango-rs** [publicsuffix/list#1108]
Hi all, first of all great crate, it really can save a lot of time and trouble!

In the process of creating tests I noticed that my panic test can't pass because `parse_email("@mail.com")` get validated without errors.

So I tried searching across the RFC and some other sources to see if {local-part} is permitted to be empty due to some alias (or catch-all specification) or something similar, however I couldn't find anything on the topic.

In my opinion it should validate as error since I don't believe it should be empty or this is something that I'm concluding wrong?

During debugging I noticed that /src/lib.rs:500 the `local` var is actually returned as &str but without any length. I believe that a simple condition edit on line 505 would do the job, however I'm still not sure whether that's a mistake or on purpose?
I don't see a test about this case as well.

**Comment by sleevi** [comment]
@Dango-rs I think you meant to report this to a different project? This project doesn't provide any API, so I'm closing this as Wontfix.

**Comment by Dango-rs** [comment]
Oops, indeed I meant another... same name different tabs. Apologies.
