### ISSUE TITLE
Require that expiration be >2 years from submission date on domains submitted in Private section

### ISSUE THREAD

**Issue by dnsguru** [publicsuffix/list#1109]
#1095 Submitted a large list of entries, which included an expired name, which led to additional overhead in the back and forth dialog and replaying the review of the DNS validation.

I would like to update the documentation (and the rules) to state that it is the responsibility of the requestor to ensure that any names submitted must have expiration dates at least 2 or more years from the date of submission of a PR, and that the names maintain at least 1-2 years' of registration term in them.  I would also like to have a consequence of failing this step and ongoing obligation to be that they can lose their entry for that domain and/or their entire section. 

We do not have a means (currently, as I author this) to review the expiry date(s) of the names in the PSL private section to remove them, so I'd like to suggest we at very least introduce a requirement of names in the private section having at least 2 years of registration length remaining.  It can be lightweight requirement, as an assertion / statement within the rationale "the domains included in this submission hold a term length that extends more than 2 years from today's date".

Because there is not a clear requirement in the documentation, we may be receiving strings that could expire while listed.  

The change and requirements would allow for us to remove entries through third party reports of expiries or should we include a periodic and automated sweeping audit that indicated names having insufficient expiry dates.

We need something like this to help evolve from the set and forget mode that we have submitters using currently.

**Comment by sleevi** [comment]
@dnsguru I support this. I would even go further, to suggest something like 5 years, given the lifecycle.

**Comment by dnsguru** [comment]
https://github.com/publicsuffix/list/wiki/Guidelines/734d6b3579a38479cad2029f29d6ef9401bf72d6#validation 
Added third bullet point

I want to update the rationale template as well to include the boiler plate statement that I put in the updated bullet point

**Comment by dnsguru** [comment]
Here is the new bullet point:
```
We now require that domains submitted as private section entries have expiration dates more than 2 years beyond the submitting date of a PR. Please include a statement within the rationale that a] the domain name(s) submitted have at least 2 years of registration period left in them at the time of submitting the name, and b] include a commitment that you will maintain their registration in good standing with more than a year left in their term.
```

**Comment by dnsguru** [comment]
Added Bolded text to wiki section [Please be thorough](https://github.com/publicsuffix/list/wiki/Guidelines#information-furnished-in-the-pr-template-be-thorough): (**bold text is new**)

- What is the registration period for the domain (_if in the PRIVATE section_)? **The PSL now requires a MINIMUM of 2 years' remaining in the registration term.  At very least, provide an attestation that the domain(s) hold ample term, and state a commitment to keeping the domain(s) renewed beyond a year.  At some point in the future, when automated registration term review of private section names occurs, domains expiring within a year may be subject to automated removal (to prevent** the risk of churning)

**Comment by dnsguru** [comment]
I put some additional suggestion text in the submission template - but want @sleevi to look at it as it is my first pass on that

**Comment by dnsguru** [comment]
The ultimate objective on this is to help ensure that we do not have expired domain names in the PSL, but the trigger for adding this requirement was a PR (specifically #1095 ) that included an expired domain name.  

Although this is a change being made to reduce the wasted cycles of additions and updates, it will be possible to later introduce automation to auto-remove names that are not in current standing.

With the consequences of not being added or having one's entry removed, starting with ample years of registration and maintaining expiry dates in good standing with >1 year term allows for automation that can do auto-removals to check more easily on the private section.

**Comment by sleevi** [comment]
I took a stab at rewording it to be Less Serious and perhaps a bit clearer.

**Comment by dnsguru** [comment]
Thanks!

I'd made edits in two places, and your edits are good to me on the first
bullet point.  Were you good with the wording down under validation?

**Comment by sleevi** [comment]
Yeah, I'm fairly ambivalent about the validation side, I think we're having that discussion in the template review, but it's not end of world in the guidelines :)

**Comment by weppos** [comment]
Sorry for being late to the party, and thanks folks for taking care of it. The amount of GH notifications my account generates daily is currently vastly unmanageable, and I'm experimenting with ways to have a better and more reactive process.

I support the proposal. While I understand the potential concern of submitters mostly related to managing the cost of a registration, I this this is a good step towards ensuring a higher level of commitment for the submitted entries.

> With the consequences of not being added or having one's entry removed, starting with ample years of registration and maintaining expiry dates in good standing with >1 year term allows for automation that can do auto-removals to check more easily on the private section.

This is a very good point.
