### ISSUE TITLE
Provide Copyright information

### ISSUE THREAD

**Issue by kkoehne** [publicsuffix/list#1121]
Who owns the copyright of the publicsuffix list? 

Is it the coypright claimed on https://publicsuffix.org/: Copyright © 2007–20 Mozilla Foundation , or is that just for the website?

It seems to me that, by contributing to the list, you don't explicitly transfer copyright to Mozilla. I can see that now tracking individual contributors is cumbersome. Anyway, contributors of single entries are probably not needed, but I understand the original list was compiled by Jo Hermans. Are there more significant contributors?

A (somewhat sneaky) way out is to just claim 'Copyright 2020 Public Suffix List Contributors', or something similar.

**Comment by dnsguru** [comment]
The spirit of it is 'open' ... I am not an attorney and not good to answer this one.  What's behind the question?

**Comment by kkoehne** [comment]
Background is that we're shipping the publicsuffixlist as part of Qt : https://doc.qt.io/qt-5/qtcore-attribution-psl.html . We now got asked by an auditor whether the copyright information is indeed correct, pointing to https://publicsuffix.org/ Copyright footer.

I'm not a lawyer either ;) Anyow, the question of copyright is - in addition to the license - the most crucial information in documenting open source content though, and often a mandatory field in third-party code declaration documents. So it might be easiest to just make it explicit as part of the original document.

**Comment by dnsguru** [comment]
Ah, for that purpose you describe, I believe there is something called the
Mozilla Public License (MPL) which may suffice.

English, US version:
https://www.mozilla.org/en-US/MPL/

I believe it is applicable here, but let your legal / person performing the
due diligence make the ultimate determination on this.

Hope that helps.  If so, close this.

-Jothan

**Comment by dnsguru** [comment]
@kkoehne can we close this?

**Comment by kkoehne** [comment]
Well, the MPL is the license, which is usually treated independenly from the Copyright information. 

Anyhow, I understand that there's no clear copyright ownership for the spdx list , so I guess this can be closed, yes.
