### ISSUE TITLE
Handling Registry-Affiliated sub-eTLDs for ICANN Section 2012 nTLDs vs Automation of GTLD Pull bot

### ISSUE THREAD

**Issue by dnsguru** [publicsuffix/list#1158]
"Legacy" gTLDs like .pro or .aero have sub-spaces defined by the registry.

For the "nTLDs" from the 2012 round, there was a fast process put in place to automate the addition of those into the PSL at the pace of contracting with ICANN, so that there would be advance inclusion of the TLDs into the PSL to help ensure that devices that incorporated a static TLD list into their browser logic but update on 3-4 month cycles would incorporate the most up to date TLDs and be directing things to DNS instead of search.
 
When @gerv and all of us maintainers originally conceived the nTLD section handler, we put them all in one section due to the pace it was receiving zones at the time, recognizing that is did not hold registry affiliated subdomains as eTLDs, so the contracting notices would function to add the names where they would need to go.

We just received PR #1156 in which the sponsoring organisation for the .РУС ("Rus" in Cyrillic) gTLD requests a number of subdomains be added to the PSL, by the registry, as a private section.

@cpu @sleevi @weppos This is potentially a new scenario for our GTLD Pull Bot automation, and I am not certain what the result of the change will be should #1156 be merged.

**Comment by cpu** [comment]
@dnsguru Thanks for the headsup. I probably won't have a chance to look deeply into this for the next few days but if the existing automation does put up a PR that undoes the change I can temporarily disable the automation. I _think_ it will be OK but I haven't thought about this bit of code for a while.

Relatedly, I've been putting some work in recently to replace the Travis/BASH version with [a Github action](https://github.com/zmap/zlint/commit/12dfc1846136a481fa889340d591701a3dfaa516). My P.O.C for ZLint has [one last kink](https://github.com/zmap/zlint/issues/515) to work out but once that's sorted out I will likely try to achieve similar results for this repo if nobody is opposed.

**Comment by dnsguru** [comment]
I am at the ICANN meeting in Istanbul, and spoke with ICANN and they wanted
to know why we began downloading the json every second or so.

Can the script please get adjusted to only run one time per day?

**Comment by simon-friedberger** [comment]
Could you ask for some clarification about who "we" is? Or what they are seeing in their logs?

It seems the GH action correctly runs once a day, see https://github.com/publicsuffix/list/blob/main/.github/workflows/tld-update.yml#L6 and https://github.com/publicsuffix/list/actions/workflows/tld-update.yml

**Comment by simon-friedberger** [comment]
cc @dnsguru
