### ISSUE TITLE
Special use domain 'home.arpa' missing

### ISSUE THREAD

**Issue by da2x** [publicsuffix/list#1205]
> 'home.arpa.' is designated for non-unique use in residential home networks. 

See [RFC 8375](https://tools.ietf.org/html/rfc8375).

**Comment by tushev** [comment]
I would agree that this domain should be included. Many browsers don't treat is as they should.

**Comment by simon-friedberger** [comment]
I am not really against including it but I think it would be a no-op. Clearly, cookie separation cannot be handled in a reasonable way for a domain which may refer to different hosts at different times. It is also by definition not a "public" suffix but actually a private one. (The same applies to the recently reserved `.internal`.)

If anybody has arguments in favor, feel free to reopen.

**Comment by AndrewKvalheim** [comment]
Related: [Bugzilla #1871769](https://bugzilla.mozilla.org/show_bug.cgi?id=1871769)
