### ISSUE TITLE
Update to .BD entry to reflect current namespace

### ISSUE THREAD

**Issue by dnsguru** [publicsuffix/list#1227]
Update *.bd for Bangladesh .bd to reflect subdomain structure currently in place 
The IANA root DB  [LINK](https://www.iana.org/domains/root/db/bd.html) Provides a link to the URL for registration services: of http://domainreg.btcl.com.bd/ which redirects to https://bdia.btcl.com.bd/domain/domainQueryForBuy/searchDomain.jsp

This site lists the following

Domain Extension | Description
-- | --
.com.bd | Intended for Commercial entities and purposes
.org.bd | Intended for Not-for-profit entities
.info.bd | Intended for personal names, only individuals can register
.net.bd | Restricted to Bangladeshi Internet Service Provider's infrastructure
.edu.bd | Restricted to Bangladeshi Educational institute, college and universities
.ac.bd | Restricted to Bangladeshi Academic institute, schools and coaching center
.gov.bd | Restricted to Government

Their registration system also lists .co.bd and .gov.bd, and their root-listed DNS for the .bd zone shows nameservers under dns.bd with direct glue records.

Because the chain of authoritative reference begins at the IANA root DB and flows out to the respective page listing the stub zones, it is considered to be authoritative for the .bd zone, and the etld space within the .bd zone are deemed to be accurate and correct.

**Comment by simon-friedberger** [comment]
Since the current wildcard entry is more restrictive than what is proposed here, and it looks like they are trying to cover all possible use-cases with a specific subdomain anyway, I suggest we leave this as is.
