### ISSUE TITLE
.PRO missing some entries

### ISSUE THREAD

**Issue by sherwinflight** [publicsuffix/list#124]
The list is missing some entries for the .PRO TLD.

They are: recht.pro, aaa.pro, acct.pro, and avocat.pro

They can be seen on the Wikipedia page for .PRO: https://en.wikipedia.org/wiki/.pro

**Comment by weppos** [comment]
More context http://registry.pro/get-pro

**Comment by weppos** [comment]
I opened a PR at https://github.com/publicsuffix/list/pull/126
