### ISSUE TITLE
.cy test data appears to be outdated

### ISSUE THREAD

**Issue by svarshavchik** [publicsuffix/list#13]
From: https://raw.githubusercontent.com/publicsuffix/list/master/tests/test_psl.txt

// TLD with only 1 (wildcard) rule.
checkPublicSuffix('cy', null);
checkPublicSuffix('c.cy', null);
checkPublicSuffix('b.c.cy', 'b.c.cy');
checkPublicSuffix('a.b.c.cy', 'b.c.cy');

It looks to me like the current public_suffix_list.dat no longer has a *.cy wildcard, so these tests will fail. The dot-cy TLD currently lists thirteen explicit second-level domains.

I suggest replacing the cy TLD with bd.

**Comment by weppos** [comment]
Thanks for reporting the issue. A patch was provided in #14, I'm going to merge it.
