### ISSUE TITLE
Azote.org domains

### ISSUE THREAD

**Issue by Mika56** [publicsuffix/list#135]
Hi,

[Azote.org](http://www.azote.org) is a well known french free domain provider.
They provide .fr.cr, .fr.nf, .ze.cx, .asso.st, .infos.st and .xxl.st domains.

I contacted them and asked they add their own domains to this list, but they didn't answer back.

From what I've seen, you require validation of domains? Might we add their domains without validation on their side?

**Comment by weppos** [comment]
> Might we add their domains without validation on their side?

No, I'm sorry but the request must be approved (and potentially submitted) by the registry/owner of the suffix.
