### ISSUE TITLE
Please include more domain suffix in the mix.

### ISSUE THREAD

**Issue by Prajwal-Koirala** [publicsuffix/list#1356]
Guys please add `.bid`

**Comment by Prajwal-Koirala** [comment]
Please add `.js`

**Comment by dnsguru** [comment]
This maximum effort issue is being closed as a wontfix.



> Guys please add `.bid`

Already there

> Please add .js

 This is against the rules

### Submitting Amendments
Before submitting any change to the list, please make sure to read the Guidelines.

A properly formatted and validated patch will decrease the review time, and increase the chances your request will be reviewed and perhaps accepted. Any patch that doesn't follow the Guidelines will be rejected or, in the best scenario, left pending for follow-up.

### Common mistakes that may cause the request to be rejected include:

- Invalid patch formatting, rule sorting or changeset position (see this: Wiki:Formatting)
- Missing validation records
- Lack of proper domain ownership or expiry dates less than 2Y away
- Attempts to work around vendor limits (see #1245 as an example)
- **Submissions with TLDs non-compliant with ICP-3 or on the ICANN PSL**   <-------
- Insufficient or incomplete rationale (be verbose!)
- Smaller, private projects with <2000 stakeholders
- Make sure to review with the Guidelines before you open a new pull request.

Please also note that there is no guarantee of inclusion, nor we are able to provide an ETA for any inclusion request. This is also true of projects that incorporate the PSL downline. This is described, outlined and diagrammed here.
