### ISSUE TITLE
.ZM TLD rule is restricting valid domains

### ISSUE THREAD

**Issue by weppos** [publicsuffix/list#140]
The issue was raised today [in the Let's Encrypt forum](https://community.letsencrypt.org/t/issue-with-zm-tld/10593). Apparently, it's possible to register second-level `.ZM` domains such as `ischool.zm`. However, our current rule is `*.zm` that totally denies this possibility.

[According to Wikipedia](https://en.wikipedia.org/wiki/.zm) the .ZM TLD has several different suffixes. However, there is no official documentation from the registry, and the website is not providing any hint.

I'm going to contact the registry to get a list of officially approved suffixes, and to get more hints about second-level TLDs. Specifically, I'd like to know if they are exceptions, and in that case how long is the exception list.

If you have .ZM contacts, feel free to share.

/cc @gerv @sleevi

**Comment by weppos** [comment]
I sent an email to the email info@zicta.zm listed at https://zicta.zm/

**Comment by SkateScout** [comment]
"whois zm" => I would try to contact cnalubamba@zicta.zm

**Comment by guysherman** [comment]
I'll see if I know anyone who knows anyone there.

**Comment by weppos** [comment]
I got a quick and very helpful response from Christina Lesa from the registry. Here's the list:

1. ac
2. biz
3. co
4. com
5. edu
6. gov
7. info
8. mil
9. net
10. org
11. sch

I'll update the PR accordingly.

**Comment by weppos** [comment]
Actually, the response doesn't solve the issue with the second level TLD. Checking right now...

**Comment by weppos** [comment]
PR opened at #187

**Comment by HBMBR** [comment]
It would seem this issue applies to .zw domains as well - was it ever resolved ?

ACME Server Returned: Unexpected error - Response: {
  "type": "urn:acme:error:malformed",
  "detail": "Error creating new authz :: Name is an ICANN TLD",
  "status": 400
}
Press enter to continue.
