### ISSUE TITLE
What next for newly created 'Pull request'

### ISSUE THREAD

**Issue by smoussa2021** [publicsuffix/list#1427]
Dear support,
Could you please tell us what are the next steps after we submitted a pull request contiainig updates on .TN PSL ?
Thanks.

**Comment by dnsguru** [comment]
Hello and thank you for reviewing the .TN entries.

There is no support department here or any service levels, just a few volunteer maintainers. 

This appears to be related to #1426 - I will close 1427 (current issue report you are reading) and let us have the entire discussion within that to keep it simple and clean.


The next steps are that the PR will be reviewed for accuracy and that it conforms to the contributing guidelines, and there will be a review of the DNS verification to ensure this is coming from the authority on the name.  We have already noticed that ati.tn is the listed entity
