### ISSUE TITLE
psl-discuss mailing list unavailable

### ISSUE THREAD

**Issue by WesleyAC** [publicsuffix/list#1428]
When I attempt to view the [psl-discuss](https://groups.google.com/g/publicsuffix-discuss) mailing list, I'm instead served with this error:

![google groups error page](https://user-images.githubusercontent.com/5001092/134061566-d9757efc-387c-4811-a703-f937bb50e557.png)

This has happened to me on several different networks, whether or not I'm logged into my Google account.

Is this a known issue? I understand that you may not have much control over this, given that the list is hosted by Google, but I figured it would be good to inform people here of the issue.

**Comment by dnsguru** [comment]
![image](https://user-images.githubusercontent.com/330149/134078372-eb8947f7-db8c-4d41-a81e-b2f3902f48da.png)

WFM, literally this moment.

Are you subscribed?  We are volunteers here and really not resourced to support this nit kind of stuff (plus a little slammed)

**Comment by dnsguru** [comment]
Some geographies censor or block Google _stuff_?

**Comment by dnsguru** [comment]
@WesleyAC  are you subscribed?   assuming you tried obvious stuff, but I think the list may be set to member viewable which may just require a subscription

**Comment by WesleyAC** [comment]
I'm not subscribed, since I'm unsure how to. I'd expect to be able to subscribe at that page, but, well...
