### ISSUE TITLE
Add CORS headers to list resource

### ISSUE THREAD

**Issue by jakearchibald** [publicsuffix/list#1433]
Allow websites to access https://publicsuffix.org/list/public_suffix_list.dat by giving the resource the following header:

```
Access-Control-Allow-Origin: *
```

**Comment by dnsguru** [comment]
are you suggesting this added to the headers or the file itself?

**Comment by jakearchibald** [comment]
Added to the HTTP headers of the resource.

**Comment by jakearchibald** [comment]
The weird thing is, the rest of the site seems to have this header, eg https://publicsuffix.org/list/, but the list itself does not.

**Comment by jakearchibald** [comment]
Is this fixed? The list appears to have CORS headers now.

**Comment by dnsguru** [comment]
I believe that Mozilla Ops are transitioning CDN hosting of the list. This
may explain some of the diversity of messaging headers seen between Dec 15
and now.

**Comment by jakearchibald** [comment]
But, is this is issue intentionally fixed, or accidentally fixed and may be unfixed?

**Comment by simon-friedberger** [comment]
@jakearchibald While I agree with you in principle, is there a particular reason why it would be useful for a website to pull in the PSL?

**Comment by jakearchibald** [comment]
> is there a particular reason why it would be useful for a website to pull in the PSL?

My use-case: [I wrote an article on CORS which included a comparison of site vs origin](https://jakearchibald.com/2021/cors/#origins-vs-sites). I wanted the form to use the most up-to-date PSL.

**Comment by simon-friedberger** [comment]
So, whenever somebody reads that blog article, and probably doesn't even interact with that form, you still download 300K of public suffix list? ;)

**Comment by jakearchibald** [comment]
Indeed, I'm not a monster.
