### ISSUE TITLE
krakow.pl (grandfathered) regional domain

### ISSUE THREAD

**Issue by weppos** [publicsuffix/list#146]
[I received a report](https://github.com/weppos/publicsuffix-ruby/issues/93) about `krakow.pl`. Apparently, the site is up and running:
http://krakow.pl/aktualnosci/195027,34,komunikat,maraton_dla_programistow_i_designerow_zbliza_sie_do_krakowa.html

Although this is not a proof, I checked when the suffix was listed, and I noticed it is no longer considered a regional domain at https://www.dns.pl/english/dns-regiony.html

However, we grandfathered it in https://github.com/publicsuffix/list/commit/7d3893d72c8edc90f2a9cc73c5a061749f18ebb6 when we reorganized the .PL listings (see [bug 1069069](https://bugzilla.mozilla.org/show_bug.cgi?id=1069069)).

@gerv you were involved in the discussion. I don't see any specific mention to these grandfathered suffixes in the ticket. Do you have some more context?

**Comment by gerv** [comment]
Not particularly. If the list is wrong according to official sources, we should fix it :-)

**Comment by mkwm** [comment]
I see that this ticket is a bit old, but to clear up any confusion regarding krakow.pl (as I live in Kraków ;) ):

krakow.pl is not (and I believe it never was) a regional domain of NASK (who is national registrar responsible for .pl TLD maintenance), this is why you don't see it on the list at https://www.dns.pl/english/dns-regiony.html.

krakow.pl is handled by [Academic Computer Centre CYFRONET AGH](http://www.cyfronet.krakow.pl/) (Cyfronet is also an operator of Metropolian Area Network in Kraków), together with handful of other domains: http://www.cyfronet.krakow.pl/sieci/13198,artykul,obslugiwane_domeny.html. These domains also serve as websites of cities itself - or redirect to the them (for example: [Kraków](http://www.krakow.pl/), [Zakopane](http://www.zakopane.pl/), [Wieliczka](http://www.wieliczka.pl/)...). They should probably be treated similarly to "TASK geographical domains" present on PSL.

I believe they are not available from any resellers, but [you can buy and register subdomain directly at Cyfronet](https://www.cyfronet.krakow.pl/sieci/13185,1,2,rejestracja.html). I think that these zones administrators are at dns@cyfronet.pl - this email address in mentioned on their website.

**Comment by liliaouldhocine** [comment]
Any update here guys?

**Comment by daftano** [comment]
Cyfronet is the registrant but it seems that they didn't ask to add their domains to PSL, so the grandfathering should be considered expired. Don't you?

**Comment by simon-friedberger** [comment]
Since you apparently can register domains here it seems appropriate that `krakow.pl` is on the list.
