### ISSUE TITLE
`onmicrosoft.com` should be in the list

### ISSUE THREAD

**Issue by ojab** [publicsuffix/list#1485]
AFAIU subdomains there are used as an email domains for Office 365 customers, so each subdomain belongs to different customer and this subdomain could be registered via Office 365 subscription.
Not sure who should deal with it, so CC microsoft people with commits here /shrug
@miwebst @mostafaez

**Comment by dnsguru** [comment]
Microsoft is aware of the publicsuffix/list - this domain may or may not be
on the PSL deliberately ; will leave this issue open for a little while for
comments.

**Comment by freddieleeman** [comment]
+1 for adding `onmicrosoft.com` to the PSL

**Comment by dnsguru** [comment]
great input.  the decision to do or not do is 'on microsoft' by submitting a pull request and doing the needed DNS TXT record magic to validate.  Will watch for that to occur, and in the mean time, because this issue has been open for so very, very long, we'll close this as wontfix.
