### ISSUE TITLE
Add: dlinkddns.com

### ISSUE THREAD

**Issue by SkateScout** [publicsuffix/list#149]
dlinkddns.com is an Dynamic DNS server für DLINK Customer.
This can be checked under https://help.dyn.com/d-link-device-verification-faqs/

**Comment by SkateScout** [comment]
I contact userhelp@dyn.com to get some official statement about this topic.

**Comment by weppos** [comment]
@SkateScout do you work at Dyn?

**Comment by SkateScout** [comment]
No and i did also not receive any response for my email to them :-(

**Comment by weppos** [comment]
@SkateScout I'm closing it for now. Dyn may provide a patch if they are interested in getting listed.

**Comment by kutysam** [comment]
dlinkddns.com is a service that dyn provides for all dlink customers.
You can take a look @ https://help.dyn.com/d-link-device-verification-faqs/

I have registered my domain name to a <domain>.com and am using dlinkddns as a ddns service at home. My web server is using a pi to be run at home. I hope you can add dlinkddns.com to the list.
It is not in 
Line 10834 // DynDNS.com : http://www.dyndns.com/services/dns/dyndns/
as it is not a provided to customers who buy DynDNS services directly.
dlinkddns.com is reserved ONLY for dlink customers.

I hope you can assist in posting this request or direct me on how can get this done, eg. email dyn dlink etc.

I don't quite understand by what you mean by Dyn may provide a patch. 
Do they have access to this repository?

**Comment by Suxsem** [comment]
We really need dlinkddns.com to be added to the list in order to obtain a certificate from letsencrypt. You can get more information at https://www.dlinkddns.com/

**Comment by sleevi** [comment]
As stated in the Guidelines, that is not a valid reason to request.

**Comment by kutysam** [comment]
How can they put a patch and to where?
