### ISSUE TITLE
Update `.cy` categories from publicsuffix list

### ISSUE THREAD

**Issue by Panayiotou** [publicsuffix/list#1516]
Dear Sirs,

We want to update the .cy list with the following:
// cy : http://www.nic.cy/
// Submitted by registry Panayiotou Fotia <cydns@ucy.ac.cy>
cy
ac.cy
biz.cy
com.cy
ekloges.cy
gov.cy
ltd.cy
net.cy
org.cy
press.cy
pro.cy
tm.cy
mil.cy

Thank you

**Comment by dnsguru** [comment]
Thank you for the review of your PSL section and the update submission.

In reviewing this, followed from the IANA listing for nic.cy

https://www.iana.org/domains/root/db/cy.html

It lists *URL for registration services:* http://www.nic.cy

The following url on that website  documents that the submitted  list of 13
available namespaces within .cy matches the list in the documented nic
policies.

https://www.nic.cy/portal//sites/default/files/symfonia_gia_eggrafi.pdf

**Comment by dnsguru** [comment]
This will result in 

- Removing `name.cy`
- Removing `parliament.cy`
- Adding `mil.cy`

Is that correct @Panayiotou ?   

I will create a Pull Request for this and I will add an additional comment line with the policies URL.
