### ISSUE TITLE
nic.io list is no longer up

### ISSUE THREAD

**Issue by Scarjit** [publicsuffix/list#1527]
The source mentioned here:
https://github.com/publicsuffix/list/blob/2db6f4601303b2ac2a5014a33356b72164088e41/public_suffix_list.dat#L1369-L1372

returns 404.

It seems to have changed to http://www.nic.io/rules.htm

**Comment by dnsguru** [comment]
Same org operates .ac, .io and .sh so the PR #1528 updates all three and will close this once merged
