### ISSUE TITLE
Remove `no.com` from PSL due to new owner/different use than subdomain registry

### ISSUE THREAD

**Issue by cicku** [publicsuffix/list#1533]
Hi,

Just a note that no.com should be removed from the list. It is now a crypto wallet website.

**Comment by gbxyz** [comment]
CentralNic no longer runs it as a registry zone, but I cannot say what the current owner/operator is doing with it.

We've held off on submitting change requests for domains that have been off-boarded from our registry system, based on the view that only the current domain owner can properly request changes that affect their domains.

**Comment by cicku** [comment]
Well I wonder if there is a better way to remove it because originally this domain (along with few others *.com) was not added by the domain owner but the registry.

**Comment by dnsguru** [comment]
Will review - want to take care here.  The domain may have been repurposed,
but if the new use did some continuity plan for affected subdomain
registrants to mitigate cookie or other behaviors that a change to there
being a PSL entry present (or not) might disrupt, the PSL volunteers do not
want to trigger that by our own PR to address this issue.

IF there is no _psl TXT record in-zone for this entry, this can be taken
into consideration in a community submission of a pull request to remove
no.com, especially where there is a submitter or commentary from a prior
submitting party.

**Comment by dnsguru** [comment]
This can be re-opened by the domain owner of no.com as a Pull Request to indicate removal, tied to the associated DNS _PSL proof
