### ISSUE TITLE
Wildcard formatting bug on Format.md in wiki

### ISSUE THREAD

**Issue by cfredric** [publicsuffix/list#1545]
The last paragraph in the [Divisions](https://github.com/publicsuffix/list/wiki/Format#divisions) section has an example that involves "\*.com" and "\*.appspot.com" wildcards, but the source text does not escape the asterisks, so markdown interprets them as italics. (This is because the second asterisk comes after a non-whitespace character ["], and tricks the heuristic.)

To get the asterisks to show up properly, they should be escaped with \\.

(I tried to make a PR for this, but found that I couldn't edit the wiki since I'm not a contributor, and AFAICT there's no way to submit a PR to a github wiki.)

**Comment by dnsguru** [comment]
Thanks - I updated it
