### ISSUE TITLE
Non Registered TLDs should be Removed (eg. .museum)

### ISSUE THREAD

**Issue by PBhadoo** [publicsuffix/list#1563]
Understanding The Issue with this.

https://community.cloudflare.com/t/add-a-psl-public-suffix-list-domain/266190/8

There are too many .museum domains added in PSL. Which are also available for sale.

Anyone who registers .museum domain name either faces problem like the above shown or shouldn't able to register it.

The issue is not personal, but in public interest.

**Comment by dnsguru** [comment]
Rather than a hunting assignment, can a list of specifc names be identified?

This is a thinly resourced project that is maintained by a small pool of
volunteers.  We have a bit of a backlog.

So, in the public interest, if you would also do the work of identifying a
list of the .MUSEUM subdomains in focus of your report so it can be
reviewed, there is a greater likelihood of this proceeding.

Thank you for taking the time to report this, and in advance for helping it
proceed.

**Comment by katehra-brc** [comment]
I'll do that. I'll also check if this can be automated to avoid checking names again and again.

**Comment by dnsguru** [comment]
We have a general need for a culling process - there is a lot of 'set and
forget' in the PSL.  Thank you for your time and attention to helping
improve the PSL

For listed names in the upper 'ICANN' section, we want to interact with the
registry or back-end operator for it, while in the 'PRIVATE' section we
would be able to remove unregistered domain names (and perhaps other
categories, like those not answering in DNS, but we'd want to have this be
something that is discussed and agreed to vs any one volunteer proclaiming
a way.

For the .museum domain names, if there is a change in the reserved list,
then Musedoma or AFNIC would be the best authority.  If they have a
published document that identifies the domain names that are intended to be
present, a reference to that URL would be helpful in addition to the list
of names being identified.

**Comment by PBhadoo** [comment]
index.museum is outdated and contains broken links. I've contacted the welcome.museum Registry regarding this, hopefully someone replies. Also the data on index.museum doesn't match the PSL anymore. I'll continue this once I've more information.

**Comment by PBhadoo** [comment]
https://gitlab.com/ParveenBhadooOfficial/psl_dns_resolver

Here is something that can help check the lists. (I'll write some new code for checking all private TLDs in the list automatically.)

https://gitlab.com/ParveenBhadooOfficial/psl_dns_resolver/-/raw/main/ns_checker/invalid.txt

This is the list of TLDs those doesn't work at all.

**Comment by PBhadoo** [comment]
[museum.txt](https://github.com/publicsuffix/list/files/8657090/museum.txt)
Here is the File sent by https://czds.icann.org on Request.

**Comment by dnsguru** [comment]
@PBhadoo we're thinly resourced here and one of the back-burner tasks is to get some form of automation to cull out expired names in the PSL, generally.  We'd start with the elements in the private section.

The ICANN section, where registries have self-designated their subspace, those need some interaction with the registries.  In the case of the subspace within the .museum TLD specifically, AFNIC as the back-end are being contacted to review this.

**Comment by dnsguru** [comment]
@PBhadoo I am closing this issue out.... I was able to have dialog with afnic.fr about this issue, and I believe it was resolved in merging the pull request that they submitted which clears out the subdomain space - #1729
