### ISSUE TITLE
Are governemental suffixes "public suffixes"?

### ISSUE THREAD

**Issue by ogxd** [publicsuffix/list#1569]
As the definition says:

> A "public suffix" is one under which Internet users can (or historically could) directly register names. Some examples of public suffixes are .com, .co.uk and pvt.k12.ma.us. The Public Suffix List is a list of all known public suffixes.

In this context, I am wondering why a suffix such as [gov.br](https://www.gov.br/) is considered to be a public suffix since "under which internel users can directly register name" does not apply, since only the Brazilian government can do it. To me this is more of a private suffix. Also, you can see that [https://www.gov.br/](https://www.gov.br/) actually leads to the Brazilian website, hence is more of an actual domain.   

What has been to historical reason for such suffix (or domain) to be in this list?

**Comment by dnsguru** [comment]
@oxgd if this answered your question, I'd like to close this

**Comment by ogxd** [comment]
Sure, I'll probably directly contact domain owners.
