### ISSUE TITLE
add co.cc to Public Suffix List

### ISSUE THREAD

**Issue by erikvanderpoel** [publicsuffix/list#157]
Please add co.cc to the PRIVATE section of the Public Suffix List.

// GoDaddy Operating Company, LLC
co.cc

Why is co.cc a Public Suffix? Because http://co.cc/ offers to register domains.

Why PRIVATE? Because .cc only registers directly under .cc. It does not offer registration under .co.cc.

Why GoDaddy? If you start from iana.org, find the registrar for cc, find their whois service, and look up cc, it will say GoDaddy.

Why GoDaddy Operating Company, LLC? That's what it says at the bottom of godaddy.com.

**Comment by weppos** [comment]
@erikvanderpoel since this is a private domain, unfortunately we can't add the suffix until the request comes from GoDaddy or it is approved by someone at GoDaddy.

Any chance you can ping them?

**Comment by erikvanderpoel** [comment]
I chatted online with a GoDaddy rep, and they pointed out that co.cc is owned by someone else, who I looked up on GoDaddy's whois service. The organization is unclear, but the individual is jong sung kim and the email is katoffel@nate.com, so I sent an email. Will report here when I get a response.

**Comment by erikvanderpoel** [comment]
By the way, when you send email to a domain owner to ask them about adding their domain to the Public Suffix List, do you have a standard template for the email message that explains what PSL is, what it is used for, the advantages of adding your domain to that list, etc? If you already have a standard letter that works well (persuades them to respond), may I have a copy of that letter?

**Comment by weppos** [comment]
Eric,

At the moment we don't have a standard template because we basically the submission process is generally on the other direction: domains owners submit the request. We don't actively contact the owners of public domains for inclusion.

**Comment by weppos** [comment]
Closing for now, until we get news from the owner.
