### ISSUE TITLE
add co.dk, biz.dk, firm.dk, store.dk, reg.dk to Public Suffix List

### ISSUE THREAD

**Issue by erikvanderpoel** [publicsuffix/list#159]
Please add co.dk, biz.dk, firm.dk, store.dk, and reg.dk to the Public Suffix List. I believe they belong in the PRIVATE section, sorted by company. The company is:

// Digital Marketing Support ApS

Ownership was confirmed with:

whois -h whois.dk-hostmaster.dk co.dk
(and so on, for each domain)

Here is the email:

Date: Fri, 26 Feb 2016 11:02:29 +0100
Message-ID: <CAFybOX=9zOuqeN3eurFvjaMgiYD8ew3xkjcVShHbPMPRiDHnUA@mail.gmail.com>
Subject: Re: co.dk and publicsuffix.org
From: Hostmaster Digital <digital@digital.co.dk>
To: Erik van der Poel <erikv@google.com>
Cc: support@dansk.net
Content-Type: multipart/alternative; boundary=001a1140f86a9bfd19052ca96509

--001a1140f86a9bfd19052ca96509
Content-Type: text/plain; charset=UTF-8

Thanks for your e-mail.

We will be pleased if you could kindly add the following domain names to
publicsuffix.org as we offer to register domains under these:

co.dk, biz.dk, firm.dk, store.dk, reg.dk.

Best regards,

Anani Voule

Hostmaster

Dansk.net / Digital Marketing Support ApS

On 24 February 2016 at 22:15, Erik van der Poel <erikv@google.com> wrote:

> Hello,
>
> I got your email address from www.co.dk. I am trying to improve
> publicsuffix.org, which is a list of domains used by browser developers,
> search engines, etc to implement cookies, certificate checking, etc. I
> noticed that co.dk offers to register domains but it is not included in
> publicsuffix.org. I believe it belongs in the PRIVATE section of
> publicsuffix.org.
>
> Please let me know if you agree, or would like more information.
>
> Thanks,
> Erik van der Poel
> Software Engineer
> Google

**Comment by weppos** [comment]
Thanks Eric. Since you already have an opened conversation with them, do you mind to tell them to write to team at publicsuffix.org? I'll get back to them and validate the request.
