### ISSUE TITLE
###make the Public Suffix List (PSL) as current and accurate as possible

### ISSUE THREAD

**Issue by KM-services** [publicsuffix/list#1610]
I'II really appreciate help I don't know  where I should begin 🙏🏻

**Comment by dnsguru** [comment]
Read the wiki please.   Also understand this is a volunteer-resourced project with little or no resourcing to hand-hold newcomers beyond the documentation

**Comment by dnsguru** [comment]
Otherwise am going to close this as there really was not a request included
