### ISSUE TITLE
Remove `gwiddle.co.uk`

### ISSUE THREAD

**Issue by BenjaminEHowe** [publicsuffix/list#1637]
gwiddle.co.uk was added to the PSL several years ago in #521. [The charity has since been removed from the UK's charity register](https://register-of-charities.charitycommission.gov.uk/charity-search/-/charity-details/5099459/charity-overview), and the domain appears to now redirect to malicious content:

![image](https://user-images.githubusercontent.com/1445869/198888119-e27b827b-501a-4d28-8417-8eaab4cae654.png)

It appears that there are no gwiddle.co.uk subdomains hosting meaningful content: https://www.google.com/search?q=site%3Agwiddle.co.uk. The TXT record no longer exists.

Given that the domain appears to be controlled by bad actors, and in the interests of file modesty, this entry should be removed.

**Comment by BenjaminEHowe** [comment]
It looks like the original submitter's new GitHub handle is @jbayfield, although I'm not sure why GitHub has attributed their previous commits to "ghost". If they can verify their link with Gwiddle then perhaps they should be considered the submitter.

**Comment by jbayfield** [comment]
Hi - this domain (and the services related to it) have been decommissioned for quite some time now, and as mentioned the legal entity no longer exists. I'd be more than happy (and would prefer!) for the domain to be removed from the PSL.

**Comment by dnsguru** [comment]
Validated this - removing this entry

**Comment by dnsguru** [comment]
The pull request containing the removal has been merged ; closing this issue
