### ISSUE TITLE
Add `ladesk.com`

### ISSUE THREAD

**Issue by LenderDoc** [publicsuffix/list#1647]
We have added a DNS record for DNS Verification many month ago. Please, check the [PR-1538](https://github.com/publicsuffix/list/pull/1538)

**Comment by dnsguru** [comment]
It is "in the queue" - 

Please don't use issues to prod the unpaid volunteers here for expediting pull request reviews.  There are other requests ahead of it, and they get processed in as orderly a manner as the volunteer cycles allow for.

One thing that could be done to help the PR once review starts is a bit more robust description of the requesting org - a fast peek at it appears that there's not many words there and it appears to be more marketing flex than actual description of org
