### ISSUE TITLE
Cache response header

### ISSUE THREAD

**Issue by agostbiro** [publicsuffix/list#1674]
Hi,

Thanks for maintaining the PSL! 

I'm wondering if it was possible to add a `Cache-Control: public, max-age=86400` (24 hours) header to the response to `https://publicsuffix.org/list/public_suffix_list.dat` to make it easier to comply with this requirement:

> have your app download the list no more than once per day

Best regards,
Agost

**Comment by smarnach** [comment]
Thanks for the suggestion! You are asking at the right time – I'm currently working on the CDN setup for the Public Suffix List.

**Comment by smarnach** [comment]
This has been implemented. The list is stil only cached for one hour in CDN, so updates reach the CDN faster. I may change this to 24 hours later, though, which would mean that it can take up to one day after merging a PR until clients see the new version.

**Comment by agostbiro** [comment]
Thanks so much!

**Comment by dnsguru** [comment]
Thanks @smarnach for implementing this and @agostbiro for raising it
