### ISSUE TITLE
Please grant me temporary admin access on this repo and the website repo.

### ISSUE THREAD

**Issue by smarnach** [publicsuffix/list#1675]
I'm an SRE at Mozilla, and I'm working on the deployment and CDN setup for the Public Suffix List. I need temporary admin access to the repositories

* https://github.com/publicsuffix/list
* https://github.com/publicsuffix/publicsuffix.org

to look at their current configuration, potentially set up web hooks and GitHub Actions secrets. As discussed by email, I have created a TXT record in the publicsuffix.org domain pointing to this issue:
```
$ host -t TXT _mozilla-sre-smarnach-auth.publicsuffix.org
_mozilla-sre-smarnach-auth.publicsuffix.org descriptive text "https://github.com/publicsuffix/list/issues/1675"
```

**Comment by dnsguru** [comment]
Granted; test

**Comment by smarnach** [comment]
Thanks! I can confirm that I have the access I need. I'll let you know when I'm done (probably some time in January), and I'll drop my access again once I don't need it anymore.
