### ISSUE TITLE
Question: Parsing the DAT, why not JSON?

### ISSUE THREAD

**Issue by woss** [publicsuffix/list#1676]
Hi, i'm trying to find out how to parse the dat file properly.

Also i am wondering why not include json as well? It is universally supported.

Thanks

**Comment by weppos** [comment]
You can find more information about the format in the wiki
https://github.com/publicsuffix/list/wiki/Format#format

We discussed about providing a JSON version, but so far this has never been implemented. Given for how long integrations have been using the TXT version, it is not as critical to provide a JSON processed alternative.

Would it be nice? Probably yes. But not critical.

If you want some examples on how to process it, you can take a look at two libraries I've written that handles the list in two different ways (real time vs pre-processing).
https://github.com/weppos/publicsuffix-ruby
https://github.com/weppos/publicsuffix-go
