### ISSUE TITLE
Add timestamp metadata in the header

### ISSUE THREAD

**Issue by romuald** [publicsuffix/list#1677]
I'm not sure how feasible this is.
It would be nice to have the "timestamp" of list somewhere in the header

Something like:
```
...
// Please pull this list from, and only from https://publicsuffix.org/list/public_suffix_list.dat,
// rather than any other VCS sites. Pulling from any other URL is not guaranteed to be supported.

// Instructions on pulling and using this list can be found at https://publicsuffix.org/list/.

// This list was last changed on 2023-01-03
```

This might help humans to quickly find if the list is outdated or not

**Comment by weppos** [comment]
The list is currently processed manually, therefore it's not feasible to add a timestamp. You can rely on the Git repository SHA to determine if any update has occurred.
