### ISSUE TITLE
Tracking SAC113 on Private-Use TLDs - creation of `.INTERNAL`

### ISSUE THREAD

**Issue by dnsguru** [publicsuffix/list#1681]
Back in the day, RFC1918 defined a number of IP address ranges that were not to be routed, such as 192.168.1.1 or 10.0.0.1 which became widely used for Network Address Translation.  There was not really any similar type of Top Level Domain defined in a similar manner, and this is being explored in order to avoid collisions from a diversity of ad-hoc approaches that have caused issues over the years.

ICANN's Security and Stability Advisory Committee has published a document related to TLD namespaces that might be used in private networks, with advice related to them.  No domain names were recommended, this is just being shared as a placeholder to ensure it is something that stakeholders here in the dev community are aware of as it evolves and some TLDs are perhaps defined.

https://www.icann.org/en/system/files/files/sac-113-en.pdf 

These MAY or MAY NOT end up being defined within the PSL.  Not without some discussion, but that discussion should likely occur after more information is available, with abundant consideration for being non-disruptive to status quo expectations and functionality wherever possible.

**Comment by dnsguru** [comment]
As a follow-up to this, ICANN is opening a [comment period ](https://www.icann.org/en/public-comment/upcoming-proceedings)related to the introduction of a private-use TLD called INTERNAL shortly...  Before that introduction would happen, or typically any significant changes, ICANN open comment periods to allow for inputs from the community.  Often the comment periods quietly appear and quietly disappear for those not closely monitoring their existence.   So I raise this to the attention of the project stakeholders to not get caught off guard.

Their timeframe on opening a comment period states "January 2024"

Their description is:

>IANA has made a provisional determination that “.INTERNAL” should be reserved for private-use and internal network applications. This string was identified according to a previously consulted procedure on implementing SAC113, produced by the SSAC. Feedback is sought on whether the identified string meets the requirements of SAC113, or whether there are any other issues with the string that need to be considered prior to its reservation.

**Browsers and other stakeholders:**  Would this belong in the PSL or not?  Things to consider as part of the comment period and perhaps even popping your head into the "ICANN-o-SPHERE" and commenting might be to consider including a subdomain of ".INTERNAL" that might be added to PSL so that it would/could be used for cookie-related stuff.  Or Not.

The comment period is opening soon.

**Comment by dnsguru** [comment]
The [Comment Period](https://www.icann.org/en/public-comment/proceeding/proposed-top-level-domain-string-for-private-use-24-01-2024) is now open

This is the ICANN document on their selection of `.INTERNAL` and the rationale of how it was selected.
[https://itp.cdn.icann.org/en/files/root-system/identification-tld-private-use-24-01-2024-en.pdf](https://itp.cdn.icann.org/en/files/root-system/identification-tld-private-use-24-01-2024-en.pdf)

Requires the creation of an ICANN.ORG account, no fees involved.

**Comment by simon-friedberger** [comment]
Further discussion in #2235
