### ISSUE TITLE
Be aware of DBOUND 

### ISSUE THREAD

**Issue by dnsguru** [publicsuffix/list#1690]
There is a proposal to begin evolving DBOUND within the IETF - something that performs some (not all) overlapping functionality with the PSL.

IETF often brings forth proposals that solve specifc and narrow purposes, and in this proposal it would be helpful if devlopers using the PSL could review the DBOUND and participate in that group discussion.

Participation will help to ensure as minimum an adverse situatuon results should DBOUND change the status quo use of PSL that are baked in.
 [https://datatracker.ietf.org/doc/bofreq-pearce-domain-boundaries-dbound/](https://datatracker.ietf.org/doc/bofreq-pearce-domain-boundaries-dbound/)

**Comment by simon-friedberger** [comment]
Since DBOUND has failed twice now, I'm closing this.

**Comment by joshenders** [comment]
We'll be back :)
