### ISSUE TITLE
Urgent  !!! gouv.bj shouldn't be in the list because it's not a TLD.

### ISSUE THREAD

**Issue by gzinsou** [publicsuffix/list#1692]
Hello, 

We are having A headache on Cloudlfare to Add the domain gouv.bj .
When adding gouv.bj on Cloudflare, Cloudflare check this publicsuffix/list and at line 387 it get it and then deny adding it as a registered domain.

We have an issue about this.
Please kindly remove gouv.bj from this public list.
Thanks very much

**Comment by dnsguru** [comment]
Please either open a pull request related to this change or contact
Cloudflare to support the functionality of their system.

**Comment by dnsguru** [comment]
closing with the closure of #1693
