### ISSUE TITLE
Cuba domain .gov.cu not exist, but .gob.cu

### ISSUE THREAD

**Issue by bayuah** [publicsuffix/list#1695]
For disclaimer, I am not Cuban, but it seem I can't find any `.gov.cu` domain anywhere, even when I specifically search with "`site:gov.cu`" keyword.

When I try to search "`Cuban president website`" the top result is "`https://www.presidencia.gob.cu`" with `.gob.cu` domain. Based on latest [Wikipedia edit](https://en.wikipedia.org/w/index.php?title=.cu&oldid=1112705871), it seem the domain indeed it is `.gob.cu`.

Is there any plan to renew the list about Cuba `.cu` domain to reflect latest changes?

**NB:** My search engine is Google Search.

**Comment by bayuah** [comment]
Thank you. Probably I keep this ticket open, so it will easier to check whatever there's any related changes.

**Comment by dnsguru** [comment]
Thank you for submitting this. The entry for .cu appears quite old and was likely imported by volunteers along the way.

I have presented at various meetings to ccTLD administrators to help expand awareness of the PSL.

Following [IANA listing for .cu](https://www.iana.org/domains/root/db/cu.html) to the [nic.cu web page with
sld policies](http://www.nic.cu/docum_det.php?doc_id=2&opt=1), they list:

```
CUBANIC otorga nombres de dominio de segundo nivel bajo .cu  o de tercer nivel bajo los genéricos de .cu operados por él según se indica en la siguiente relación:

com.cu: para personas jurídicas con actividades comerciales de bienes y
servicios con fines de lucro;

edu.cu: para definir centros del sistema de Educación;

gob.cu: para órganos y organismos de la Administración Central del Estado y
otras estructuras de Gobierno;

inf.cu: para entidades relacionadas con la actividad de información
científica y proveedores de información o contenidos;

nat.cu: para personas naturales residentes en el país.

net.cu: para Proveedores Públicos de Telecomunicaciones;

org.cu: para Organizaciones no gubernamentales y sin fines de lucro;
```

There needs to be a Pull Request (PR) to revise the .CU listing.  A bias would be to have this come from the NIC.CU to ensure that every change is deliberate and intentional, as it is they who would get support calls if a change breaks anything.

There is a preference that the PR would need to place DNS TXT entries that include the Pull Request URL.

**Comment by dnsguru** [comment]
see #1694 for a recent example of what this would need to look like with involvement from the ccTLD administration

**Comment by rubenskuhl** [comment]
I'll try forwarding an alert of this issue to CITMATEL, the registry operator for .cu, thru LACTLD. I guess they have so many issues as a sanctioned country that they might have not noticed specific applications or services not working for a subset of their domains. Which suggests .ir and .kp as possible occurrences of the same lack of feedback loop.

**Comment by simon-friedberger** [comment]
Should we update anyway?

Current entries:
```
// cu : https://www.iana.org/domains/root/db/cu.html
cu
com.cu
edu.cu
org.cu
net.cu
gov.cu
inf.cu
```

So to get to https://www.nic.cu/docum_det.php?doc_id=2&opt=1 we want
```
-gov.cu
+govb.cu
+nat.cu
```

and we could just skip the removal.

**Comment by wdhdev** [comment]
I think it would be safe to do so. Would it be worth attempting to contact the registry via email to confirm this?

**Comment by groundcat** [comment]
If we consider the IANA page to be an authoritative source, the listing at http://iana.org/domains/root/db/cu.html designates http://www.nic.cu as the official registry link. Consequently, the domain list available at https://www.nic.cu/docum_det.php?doc_id=2&opt=1 can be regarded as a reliable and authoritative source. In my view, including these domains in the PSL would be a prudent step to benefit Internet users. However, this approach might not be suitable for removing domains unless the removal request comes explicitly from the registries themselves, as some domains may no longer be publicly available for registration but are still operational for existing users (such as `.bc.ca` under CIRA).

**Comment by wdhdev** [comment]
Google returns no results for `site:gov.cu` but does for `site:gob.cu`, and when searching for subdomains on `gov.cu` there are no results found using https://subdomainfinder.c99.nl/.

**Comment by rubenskuhl** [comment]
Are there any certificates in CT for .gov.cu ?


Rubens

Em sex., 6 de set. de 2024, 04:37, William Harrison <
***@***.***> escreveu:

**Comment by groundcat** [comment]
> Are there any certificates in CT for .gov.cu ?

The only certificate for `inre.inre.gov.cu` is found in CT (https://crt.sh/?q=gov.cu), but it expired two days ago on September 4, 2024.

![image](https://github.com/user-attachments/assets/2eb4dc53-5857-430a-a345-08008347c8a7)

So, if we exclude expired certificates, no domains would be found: https://crt.sh/?Identity=gov.cu&exclude=expired

**Comment by dnsguru** [comment]
@kjd Is there a context w gob.cu / gov.cu that could comment on our best path to take here?

**Comment by kjd** [comment]
We (IANA) spoke with the .CU manager and they confirmed `gob.cu` is in use as a public suffix, and `gov.cu` is not.
