### ISSUE TITLE
add second level domain for cloudns

### ISSUE THREAD

**Issue by JohaFreu** [publicsuffix/list#1703]
cloudns.nz
cloudns.ph

**Comment by dnsguru** [comment]
This is probably related to https://github.com/publicsuffix/list/pull/1593 - 

The PSL is volunteer-staffed we don't accept submissions via issue submissions like this.   Please make this request to the person who submitted that PR if it is related, add your proposed domains as a comment within that pull request, @JohaFreu.

**Comment by dnsguru** [comment]
It is not "invalid" per se., we just don't have a label for "mis-filed".

**Comment by boyanpeychev** [comment]
TXT records are added. Thank you!
