### ISSUE TITLE
Please add `run.app`

### ISSUE THREAD

**Issue by RezaRahmati** [publicsuffix/list#1710]
Hi there

Google cloud run domains are `run.app` by default. would you please add it.

example: `health-check-tool-2-api-izeboapi4q-nn.a.run.app`

Regards

**Comment by dnsguru** [comment]
You are welcome to contact the domain name owner and suggest they open a pull request for this and establish the appropriate DNS proofs

**Comment by RezaRahmati** [comment]
@dnsguru Thanks for response, any idea how should I contact google on this subject? (as the domain is related to google cloud)

**Comment by dnsguru** [comment]
I am an unpaid volunteer and do not work for Google. If they are paying attention, they will hopefully see this and do their thing.

**Comment by andreasstieger** [comment]
This is already in the list since 2018! (#681 / 921a6f2), your request is moot or based on incorrect assumptions.

**Comment by RezaRahmati** [comment]
Great, thank you @andreasstieger

**Comment by dnsguru** [comment]
Thanks @andreasstieger - I'm so slammed that I didn't look at this either
