### ISSUE TITLE
public_suffix_list.dat propogation to publicsuffix.org

### ISSUE THREAD

**Issue by dnsguru** [publicsuffix/list#1730]
@smarnach what is the amount of time that it takes for changes made to the public_suffix_list.dat file on github to propogate to https://publicsuffix.org/list/public_suffix_list.dat ?

I had the submitter ask about this in #1729 after I merged their PR to update .museum that resulted from an exchange that started last year.

Can you confirm it is propogating?

**Comment by smarnach** [comment]
The time until new files reach the Cloud Storage basket is rather short – about a minute or so. You can see the deployment logs in the [Actions tab]() ([logs for the mentioned PR](https://github.com/publicsuffix/list/actions/runs/4610408183)). The logs show whether the deployment succeeded.

Files are cached on CDN edge servers for up to a day. What version of the file you see depends on the edge server you happen to hit. You may hit different edge servers even if you run `curl` twice in immediate succession on the same machine. You can check the "age" header to see how old the file you got is, which should tell you whether it's the old or the new version. Here's an example from my machine:
```
$ curl -sI https://publicsuffix.org/list/public_suffix_list.dat | rg ^age:
age: 60936
$ curl -sI https://publicsuffix.org/list/public_suffix_list.dat | rg ^age:
age: 30343
```
You can see that I hit two different edge servers, and the cached version on each server have different age. Both servers already return the new version of the file for me, but it would be possible that one server returns the old version and the other the new version. After 24 hours the cached files expire, and all edge server should return the new version.

I mentioned that we may increase the cache time to one day on #1674. We did make this change when we migrated to GCP.

**Comment by dnsguru** [comment]
This appears to be "resolved"
