### ISSUE TITLE
 Domain id.vn is a new domain name in Vietnam. Not yet available

### ISSUE THREAD

**Issue by rinihome** [publicsuffix/list#1769]
Domain id.vn is a new domain name in Vietnam. Not yet available

**Comment by ToThangGTVT** [comment]
beside domain .io.vn .ai.vn not yet too

**Comment by dnsguru** [comment]
Related: #1771

**Comment by fool** [comment]
This PR has been merged, yay!

**Comment by dnsguru** [comment]
#1771 addresed this with respect to PSL, so closing this.
