### ISSUE TITLE
cut new release of gem with recent updates?

### ISSUE THREAD

**Issue by fool** [publicsuffix/list#1781]
In https://github.com/publicsuffix/list/issues/1769 we learned of a new TLD, which is actively being given out.  

Customers at my place of work are struggling to use this domain, since we rely on the publicsuffix list to declare these "pseudo-TLD" entries as - which will allow folks to have their own distinct 3-part TLD (them.id.vn) without conflicts with other customers.  I know some other webhosting companies do something similar to prevent subdomain takeovers and other "domain squatting" techniques where customers point DNS to "a CDN" and have to rely on the provider to protect them from takeovers.

In https://github.com/publicsuffix/list/pull/1771 we saw the code written to support this new TLD!

Yesterday, it was merged.

But, we see the last gem release in Dec 2022. 

Could we get a new gem release incorporating this and all the other updates in the meantime, please & thanks?

**Comment by weppos** [comment]
The Ruby library is one of the various independent project, is not managed directly by the PSL team.

I actually happen to be the author and maintainer of that lib. I release new versions periodically, the Gem release is independent from the changes in the list as any consumer can of the lib can use a custom version of the list.

I'm closing this ticket as it not pertains the PSL itself. Will cut a Gem release as soon as possible.
