### ISSUE TITLE
Include `ca.gov` in the list

### ISSUE THREAD

**Issue by Hrishikesh-K** [publicsuffix/list#1787]
Look like California government is giving out domains: https://domainnamerequest.cdt.ca.gov/. Can this be added to the list?

**Comment by dnsguru** [comment]
If they determine it necessary and appropriate, the administrators of that namespace can request it using a pull request.

The volunteers here don't have the cycles to chase down whomever administers that namespace - as the reporting party, if you'd like to see this get added, you have self-nominated yourself to be the person that follows this up with the administration of that domain name.

Happy Hunting!

**Comment by dnsguru** [comment]
[.CA.GOV Contact Page]](https://domainnamerequest.cdt.ca.gov/Home/ContactUs?ReturnURL=%252F) to set you in the right direction

**Comment by Hrishikesh-K** [comment]
Thanks! I've already reached out to them.

**Comment by dnsguru** [comment]
excellent, will watch for PR from them if they deterimine that they need it

**Comment by dnsguru** [comment]
Meanwhile, closing this.
