### ISSUE TITLE
add .secureserver.net

### ISSUE THREAD

**Issue by der-martin85** [publicsuffix/list#1790]
Please add .secureserver.net to the suffix list. This is not a DynDNS Domain, but the Generic Domain for Virtual Servers by Hosteurope. They have the form [IPinReverse].host.secureserver.net
Thank you!

**Comment by felixfontein** [comment]
@der-martin85 you should contact Hosteurope and ask them to get this going. They need to add a DNS entry for verification.

**Comment by dnsguru** [comment]
This would require a Pull Request from an administrator at Hosteurope or GoDaddy alongside corresponding DNS leaf records to demonstrate administrative connection.  Please obtain that directly from the appropriate parties within GoDaddy/HEG, and you can refer back to this issue, which can still be referenced but I am now closing.
