### ISSUE TITLE
proposal to automate PR review process

### ISSUE THREAD

**Issue by lfundaro-do** [publicsuffix/list#1794]
I was wondering if we could automate the review process and have the volunteers of this project only merge when all checks pass. I think the amount of PRs and cycles needed for review is overwhelming and may cause burn out on volunteers. 

Things like this review https://github.com/publicsuffix/list/pull/1789#issuecomment-1614289895 one might be able to automate with a github action and issue a label and comment indicating PR creators where to go next. 

I might be able to get some cycles to help on this.  @dnsguru do you think this is feasable ?. Asking because I'm completely new on this project and don't have much context.

**Comment by dnsguru** [comment]
There is some work being done on some automation of certain aspects of reviews - DNS _PSL txt presence, correct formating and sorting, and other aspects of the submission review.    Also being done by volunteers, from what I am told.  

Your offer is appreciated, but the resourcing is a challenge.... project managing multiple participants adds additional resource drain on this that are already non-existent.

The end-to-end process cannot be automated, but component tasks can likely be.

**Comment by simon-friedberger** [comment]
@lfundaro-do If you want to help take a look at the work that @danderson has been doing recently:
* #1987 
* #1999 
* #2005 
He is keeping a list of ToDos here: https://gist.github.com/danderson/f2d5a7a7e0400ea2a7c9dff18058615c#file-psl-todo-md
