### ISSUE TITLE
Add `.uk.to`

### ISSUE THREAD

**Issue by andriejs** [publicsuffix/list#1801]
Hi, `.uk.to` is a domain from [Afraid FreeDNS](https://freedns.afraid.org/) which a lot of people use (including me) and I'd like it to be included in this list.

Example use: [domain].uk.to

**Comment by dnsguru** [comment]
Please read wiki about submissions of Pull Requests - closing.

**Comment by andriejs** [comment]
@dnsguru I've made a pull request. #1803

**Comment by dnsguru** [comment]
Yay!
