### ISSUE TITLE
Open Q / Discussion: DNSSEC-Signed requests receiving prioritization 

### ISSUE THREAD

**Issue by dnsguru** [publicsuffix/list#1819]
In some of the feedback to #1813 that has come to me conversationally, one suggestion was to make DNSSEC signature of the eTLD+ be mandatory.

The benefits of the integrity of resolutions that DNSSEC are fairly great, though adoption is below what one would hope.  Probably related to the adoption is the friction/complexity to implementing it.

So perhaps making it mandatory is a bit unrealistic, but what might be a good idea would be to attract use of DNSSEC being in place to add safety/integrity, and as we automate SOA/TXT automation for the review process, also scan for DNSSEC records being present, and let those with DNSSEC jump ahead in priority of processing.

Would like to see some community feedback on this.

**Comment by dnsguru** [comment]
The thinking here would be to add something like this into the DNS scanning automation specifications that are being discussed

**Comment by dnsguru** [comment]
https://dnsrf.org/blog/use-of-subdomain-providers-gains-popularity-as-a-mechanism-to-launch-phishing/index.html

**Comment by simon-friedberger** [comment]
I doubt this would actually improve the adoption of DNSSEC a lot. The PSL just isn't that big. Plus, we are not slow enough that prioritization would make a meaningful difference.
