### ISSUE TITLE
How would you add an entry to the PSL only to use locally within a web browser?

### ISSUE THREAD

**Issue by PHJArea217** [publicsuffix/list#1842]
Not a request per se, but how would you be able to add a only-locally significant entry into a private copy of the Public Suffix List? For example, I have an application with a custom DNS server which generates random subdomains under the u-relay.home.arpa domain, for interpreting strings like ip4-192-0-2-1.u-relay.home.arpa (this is different from e.g. sslip.io because that domain wouldn't actually resolve to 192.0.2.1, not even as DNS64). This domain name is of course under a private zone, so it wouldn't be suitable for inclusion in the public version.

**Comment by PHJArea217** [comment]
In Other words, I want to add u-relay.home.arpa just to my local version of Firefox and Chrome without affecting anyone else's Firefox or Chrome.

**Comment by PHJArea217** [comment]
(The reason why I can't use an IPv4/v6 literal like 192.0.2.1 or 2001:db8::X directly is because in the specific network environment that the app is running in, it is not possible to reach any public IP addresses; instead, the DNS just points all domains to private IPs and the private IPs are proxied back to the domain names on the public Internet.

**Comment by dnsguru** [comment]
sounds like a hosts.txt issue perhaps?

**Comment by dnsguru** [comment]
This is not something PSL can address, either way... closing
