### ISSUE TITLE
Is the "Public Suffix List Compliance Action Needed: Missing _psl TXT Record" email legitimate?

### ISSUE THREAD

**Issue by TimWolla** [publicsuffix/list#1843]
Hi

we just received an email titled "Public Suffix List Compliance Action Needed: Missing _psl TXT Record" authored by a name and email address that does not appear to be related to either the current or past list of PSL maintainers. I was not able to find a current (pinned) issue or recent commit indicating the legitimacy of this email. The email contents are pretty generic and do not reference the domains that were detected to not have the `_psl` record.

Can you confirm or deny whether this is an official email by the PSL project?

I was confused, because we intentionally did not delete the `_psl` record from our domains. However when checking I noticed that one domain had `https://github.com/publicsuffix/list/issues/1168` instead of the correct `https://github.com/publicsuffix/list/pull/1168` within the record (i.e. `issues` instead of `pull`, the former redirects to the latter), which I then corrected. This might or might not have caused us to receive the email - I can't confirm due to the email not listing the exact domains. In any case I'm filing this issue in case some other domain owner is also confused about the legitimacy.

**Comment by groundcat** [comment]
Would you mind sharing the complete content of the email you just received and include the email headers? Was the addition of the "missing _psl txt record" the only request from the sender, or were there additional malicious/suspicious instructions?
If someone is impersonating the PSL volunteers with malicious intent, this could pose a security risk, and domain registrants probably should be alarmed. (I am not a PSL team volunteer.)

**Comment by dnsguru** [comment]
I can say confidently that we have not sent out any notice like you
describe - it would assume the volunteers are that well resourced.

That said, it is not a bad idea to make sure that you leave the records in
place.

**Comment by dnsguru** [comment]
see #1849 and the updated [readme](https://github.com/publicsuffix/list/blob/master/README.md)

**Comment by dnsguru** [comment]
> Would you mind sharing the complete content of the email you just received and include the email headers? Was the addition of the "missing _psl txt record" the only request from the sender, or were there additional malicious/suspicious instructions? If someone is impersonating the PSL volunteers with malicious intent, this could pose a security risk, and domain registrants probably should be alarmed. I am not a PSL team volunteer but I assume there might be some verifiable way of communication from the PSL maintainers?

Would like to see this also

**Comment by TimWolla** [comment]
I can confirm that the information in https://github.com/publicsuffix/list/issues/1846#issuecomment-1705863528 matches the data in the email we received.

Feel free to close this issue to not discuss this in multiple places, especially since you now created an official issue about this incident.

**Comment by groundcat** [comment]
Considering that the submitter's email addresses are openly accessible in the list and may be subject to abuse, I am contemplating whether it would be beneficial to include a disclaimer in the readme.md that clarifies the communication procedure between the PSL maintainers and the domain owners. For instance, it could specify that PSL maintainers will never send any emails to you or that only emails originating from the `@publicsuffix.org` address are valid. However, I am not entirely confident about the feasibility of this idea.
