### ISSUE TITLE
`scooper6@my.ccri.edu` is not with PSL and "Compliance" emails are not being sent from this project

### ISSUE THREAD

**Issue by dnsguru** [publicsuffix/list#1849]
Someone, **NOT US** is sending compliance notices.  Those are not from the project.  We have updated the project [README](https://github.com/publicsuffix/list/blob/master/README.md) and have added this notice.

#1843 and #1846 are just a couple examples of user feedback from those happening

**Comment by dnsguru** [comment]
```PLEASE POST ONE WITH HEADERS IF YOU HAVE RECEIVED ONE ```

**Comment by simon-friedberger** [comment]
They seem to have stopped.
