### ISSUE TITLE
Volunteer support:  comment on PRs that have Sorting wrong

### ISSUE THREAD

**Issue by dnsguru** [publicsuffix/list#1858]
Dear community

One issue that seems to expend a lot of time from the volunteers is where submitting parties' PR have not followed guidelines.  

It causes back and forth to request changes in the PR and then the time for the requestor to see it, revise their commit, and then again for the volunteers to review other aspects of the PR.  The goal here is not having to iterate like this when the core team reviewer has the cycles to approve and merge pull requests.

We receive a large volume of miss-sorted submissions, that have not followed guidelines.  This happens on:

* new addition to PSL that includes a new section, or
* update to an existing section to add domains

Most frequently we see submissions that do one or more of the following errors around sorting: 

* Place their entry at the end-of-file (EOF) instead of locating the commented organization that would come alphabetically before theirs, and adding their section just below it. (This is more for the new section additions)
* Adding domains within their section but not sorting them correctly.  The appropriate domain level sorting should be in ASCending order in this order of operation:    
  * Top Level Domain, then
  * Second Level Domain, then
  * Third Level Domain, etc.

I am told that there are some efforts under way to introduce some automation for this, but while we are wating for it, people seeking to help with this project, if you can review to suggest to the submitter that they need to fix those situations, it will help make for a faster processing.

Just review the given PR's code diff, and comment on the given PR where applicable with a suggestion to review their sorting to ensure it conforms to the guidelines, and cite the submitter with an @ in the comment so it nudges them to act.

It is my hope that some of the people that show up here can help to address these sorting errors by submitters and help get the project flowing.

**Comment by simon-friedberger** [comment]
Sorting is checked by GH action now.

**Comment by wdhdev** [comment]
@simon-friedberger This can be unpinned as well.
