### ISSUE TITLE
Poor Project. 

### ISSUE THREAD

**Issue by mercu0041** [publicsuffix/list#1888]
How many PR will be merge in a month?

I know this repo is maintained by a volunteer. but look!
there's no significant progress. is it 5-10 PRs a month? no.

it's like 0-1 PRs a month. it depends on the requester. if it's coming from big brand, e.g. amazon, aws,. then the progress is so fast. 

why????

what happens with the others? have been waiting for years...

this is not about volunteer time anymore. you have time. you just don't want to merge.

**Comment by dnsguru** [comment]
How not to motivate volunteers exhibit 1
