### ISSUE TITLE
Update example in wiki

### ISSUE THREAD

**Issue by simon-friedberger** [publicsuffix/list#1890]
> Here's a suggestion to make it clear that entries at a higher level don't impact lower levels. Add the following just below 1. com:

> *.foo.com

> and then add these bullet points just below Cookies may be set for foo.com.:

>    Cookies may not be set for bar.foo.com.
>    Cookies may be set for example.bar.foo.com.

We've gotten this proposal for updating https://github.com/publicsuffix/list/wiki/Format#example
which I think is a good suggestion but I don't have wiki editing rights so I am capturing it here.

**Comment by dnsguru** [comment]
@simon-friedberger @mozfreddyb - added to wiki, with re-numbering and then numbering that connects to them in the explainers that follow the examples.   Reopen if this was not correct
