### ISSUE TITLE
co.az is not exist in the list

### ISSUE THREAD

**Issue by rserit** [publicsuffix/list#1903]
Hi. az domains working well except co.az.
When you parse "xyz.co.az", TLD name is "az", registrable domain is "co.az". It's wrong because list file is not include "co.az".
Could you update?

**Comment by simon-friedberger** [comment]
If somebody from the registry of Azerbaijan requests it we would be happy to add it. Could you maybe reach out to them?

**Comment by mozfreddyb** [comment]
I've sent an email to see if they can comment in public.

**Comment by dnsguru** [comment]
Via the IANA Contact?

The ccTLD contacts get so much spam to those addresses, that it is typical
to not get responses.

I have found it has been more productive to do outreach in the tech day at
ICANN meetings every year or so.

**Comment by mozfreddyb** [comment]
> Via the IANA Contact? The ccTLD contacts get so much spam to those addresses, that it is typical to not get responses. I have found it has been more productive to do outreach in the tech day at ICANN meetings every year or so.

I'm sure it would be 1000 times easier to reach someone in person when at the same event. In this case, I read through [their regulatory government documents](https://whois.az/?page_id=10) and ended up writing to info@domain.az.

I'm not really expecting someone to answer. The document above, btw, does list all second level domains explicitly, albeit in prose text. @dnsguru Has that been enough in the past or would we rather wait?

**Comment by dnsguru** [comment]
We typically have (with ccTLD) let the registry speak for cookie etc
affectation through the addition of the DNS validation record being added
in-zone (or in TLD Apex).

Largely, because the change would impact their customers and potentially
trigger customer service calls - thus the desire is to have the inclusion
be intentional.

**Comment by dnsguru** [comment]
>@dnsguru <https://github.com/dnsguru> Has that been enough in the past or
would we rather wait?

where one of us has had some form of interaction with the cctld or the
cctld has directly participated in the creation or comments on a pull
request have made changes but not with third party submissions.

We will see 1-2 requests directly from ccTLDs after an event I present at -
where they have spoken with me directly to help them review their
section(s)

We have a couple of ccTLD pull requests currently open which merit review
or commentary from the ccTLD - i add a label for these where ICANN section
entries are affected

**Comment by rserit** [comment]
I can contact the registry. Our friends in Azerbaijan can guide us. Let me see what I can do. I will inform

**Comment by dnsguru** [comment]
outstanding - that follows #1439 which is pinned to the issues list
