### ISSUE TITLE
Add alternate roots TLD

### ISSUE THREAD

**Issue by CTIMarc** [publicsuffix/list#1917]
It would be nice to add non ICANN related TLD:

list from https://en.wikipedia.org/wiki/List_of_Internet_top-level_domains:

## OpenNIC
```
.bbs
.chan
.cyb
.dyn
.geek
.gopher
.indy
.libre
.neo
.null
.o
.oss
.oz
.parody
.pirate
```

## FurNIC
```
.fur	
```

## Emercoin
```
.lib
.coin
.emc
.bazar	
```

## New Nations
```
.ku
.te
.ti
.uu
.ko
.rm	
```

**Comment by felixfontein** [comment]
See also #1585 and #442.

**Comment by dnsguru** [comment]
please read the wiki and #1585 referenced earlier as to closure rationale.
