### ISSUE TITLE
Unlink deprecated PHP TLDExtract from `/learn/`

### ISSUE THREAD

**Issue by imme-emosol** [publicsuffix/list#1931]
remove
link to https://github.com/layershifter/TLDExtract
from https://publicsuffix.org/learn/

**Comment by simon-friedberger** [comment]
This is in the wrong repo @dnsguru can you give me write permissions on publicsuffix/publicsuffix.org so I can take care of this?

**Comment by imme-emosol** [comment]
Handled/Fixed in https://github.com/publicsuffix/publicsuffix.org/pull/42 .
