### ISSUE TITLE
Volunteering and forward looking structure to the PSL

### ISSUE THREAD

**Issue by geseeto** [publicsuffix/list#1946]
Hi Jothan and Simone,

I am reaching out to see what how myself and a colleague could step up to help you two in maintaining the PSL and also how open you both might be to improving the existing PSL? Also what is the governance model around this?

Thanks in advance!

**Comment by dnsguru** [comment]
one important area that has been in place for the last 15 years is evaluating requestors against security lists to ensure no criminal requestors could leverage the PSL to advance their perpetration of criminal activities, which has a lot of attention by security experts at the moment.

**Comment by simon-friedberger** [comment]
@geseeto If you can spend some time to help out that's great! Just go through the PRs and add a checklist like I usually do, for example here: https://github.com/publicsuffix/list/pull/1940#issuecomment-1985206360

When everything is ready, ping @dnsguru so he can merge it directly or me, to add it to his merge queue.

You can skip issues which have r=$somebody or which are already in this list: https://github.com/orgs/publicsuffix/projects/2#column-19755113

Does this answer your question?
