### ISSUE TITLE
has Mozilla broken the publicsuffix.org link to public_suffix_list.dat?

### ISSUE THREAD

**Issue by dnsguru** [publicsuffix/list#1951]
submitter of #1944 asking why the publicsuffix.org website has not updated the public)suffix_list.dat file to match that of the main github repository 

is propogation malfuncitoning or has Mozilla deliberately broken the publishing of the dat file?  This is likely to cause disruptive consequences with multiple-authorities issue based upon a split of manners in which the file gets incorporated or used.

[public_suffix_list.dat](https://github.com/publicsuffix/list/blob/master/public_suffix_list.dat) should be publishing on publicsuffix.org in a stable manner to demonstrate Mozilla's ongoing capability to resource this project

**Comment by dnsguru** [comment]
Seems to have stabilized - Was this related to propogation delay?  Was this an unannouced code/publishing change?  Was there an issue?  There was a multi-day publishing delay happening that was reported by someone who's merged change was not up on the pubilcsuffix.org link to the dat file, so there was a different version between github's dat file and the one on publicsuffix.org

**Comment by simon-friedberger** [comment]
According to our SREs they made some changes to the bucket but everything should be working smoothly again.
