### ISSUE TITLE
Problem with domain names with .tr extension.

### ISSUE THREAD

**Issue by yasinyilmaz1** [publicsuffix/list#1965]
When I enter the domain names with com.tr, net.tr and .tr extensions into the domain name section to create hosting on cloudpanel, cloudpanel does not create hosting. I opened a request to cloudpanel for this, but they said that the problem was not related to cloudpanel and the details are available in the description in this link. https://github.com/cloudpanel-io/cloudpanel-ce/issues/449

The error I get is as follows.
CLI
root@mail:~# clpctl site:add:reverse-proxy --domainName=mail.domain.net.tr --reverseProxyUrl='https://127.0.0.1:17443/' --siteUser=user --siteUserPassword='**************'
cURL error 28: Operation timed out after 10000 milliseconds with 68188 out of 308886 bytes received (see https://curl.haxx.se/libcurl/c/libcurl-errors.html) for https://publicsuffix.org/list/public_suffix_list.dat

Domain names with tr extension were transferred from nic.tr management to trabis.gov.tr. Could the problem be related to this?

**Comment by dnsguru** [comment]
>Domain names with tr extension were transferred from nic.tr management to trabis.gov.tr. Could the problem be related to this?

That would have no impact unless the folks at trabis.gov.tr submitted a change.

Candidly, it sounds like something appropriate to raise with that hosting provider directly about their broken process.

net.tr is in the PSL, but more notably that error code pasted looks like something where that curl fetch didn't work - from the perspective of the PSL there is no problem for the unpaid volunteers of this project to support.  





```
// tr : https://nic.tr/
// https://nic.tr/forms/eng/policies.pdf
// https://nic.tr/index.php?USRACTN=PRICELST
tr
av.tr
bbs.tr
bel.tr
biz.tr
com.tr
dr.tr
edu.tr
gen.tr
gov.tr
info.tr
mil.tr
k12.tr
kep.tr
name.tr
net.tr.   <---- that one
org.tr
pol.tr
tel.tr
tsk.tr
tv.tr
web.tr
```
