### ISSUE TITLE
#1789 pull request update

### ISSUE THREAD

**Issue by anantsparrow** [publicsuffix/list#1981]
Hey there, i was in medical emergency so could not do the renewal or check updates here, can you please reopen the pull request, I will fix the issues, like the renewal of domain to 2 years and update psl, now asap. I really waited 1 years for this pull request to be merged, please help on this,

**Comment by mozfreddyb** [comment]
No need to file a duplicate. We'll look at #1789.

**Comment by anantsparrow** [comment]
@mozfreddyb Okay, please update so i can renew and update the domain

**Comment by anantsparrow** [comment]
@mozfreddyb can you please look into this once? my pr is still closed.
