### ISSUE TITLE
Usage example

### ISSUE THREAD

**Issue by szepeviktor** [publicsuffix/list#20]
May I put this into the [Wiki](https://github.com/publicsuffix/list/wiki)?
This script outputs only the SLD part from a list of domain names.
So if you have `subdomain.example.co.uk` on your list, the output will be `example.co.uk`.
```bash
# Prepare the list for finding second-level domains
Publicsuffix_regexp() {
    local LIST_URL="https://publicsuffix.org/list/public_suffix_list.dat"

    # Download list,
    #   remove empty lines and comments,
    #   escape dots, asterisks and add SLD regexp
    wget -qO- "$LIST_URL" \
        | grep -v "^\s*$\|^\s*//" \
        | sed -e 's/\./\\./g' -e 's/\*/.*/' -e 's/^\(.*\)$/[^.]\\+\\.\1$/'
}

Publicsuffix_regexp | grep -o -f - "$YOUR_DOMAINS"
```
I use it for registration expiry purposes.

**Comment by weppos** [comment]
@szepeviktor thanks for your contributions. I'm closing this, as we don't currently add usage examples or libraries to the wiki.

Also double check your code properly reflects the [formal algorithm](https://publicsuffix.org/list/), including the exceptions. Or you may get inaccurate results.
