### ISSUE TITLE
Updates on aland.fi

### ISSUE THREAD

**Issue by molangning** [publicsuffix/list#2009]
While looking through the list, I have noticed an entry on aland.fi

https://github.com/publicsuffix/list/blob/bc648febe28883c5585ec463f5a10d8a57edd6f2/public_suffix_list.dat#L1017-L1024

In the comments, it was mentioned that the suffix should be checked again in 2009. It’s 2024 now, and accoding to the whois, the domain will expire in 2025. 

Should the comment be updated to 2025 or beyond, or has the domains under aland.fi been removed?

https://www.whois.com/whois/aland.fi

**Comment by simon-friedberger** [comment]
I think we can remove this comment. The domain still exists and still points to the registry so presumably they are keeping it around.

**Comment by dnsguru** [comment]
We have a lot of legacy cctlds' entries in the PSL uppder section like this, where (and in this case) there was wikipedia as the original reference.  I think the suggestion of changing the header is good, while leaving the aland.fi entry intact.

I went to iana.org and their root db for [.fi ](https://www.iana.org/domains/root/db/fi.html) and found that there is
https://domains.fi as the registry website,  It redirects to  
https://www.traficom.fi/fi/viestinta/fi-verkkotunnukset

I'd like to suggest that we replace the wikipedia legacy link line with this:
```// fi : https://www.iana.org/domains/root/db/fi.html```

and remove the line with ```// TODO:```
