### ISSUE TITLE
cyclic.sh shut down

### ISSUE THREAD

**Issue by wdhdev** [publicsuffix/list#2046]
Cyclic announced they were shutting down their services back on the 27th April, 2024, announcing all services would be disconnected by May 31st, 2024. It is nearly 2 months since then and I noticed they are still on the PSL here: https://www.cyclic.sh/posts/cyclic-is-shutting-down/

Do they still need to be on the PSL if their service has shutdown? Unless they are planning on reopening their service in future.

cc @seekayel (original submitter of the service in #1737)

**Comment by seekayel** [comment]
Fine to be removed. Is the expectation I do that as the original submitter?

**Comment by wdhdev** [comment]
I believe they would just need your approval, which you have given here. I've opened a PR for it: #2051
