### ISSUE TITLE
Please remove saratov.ru

### ISSUE THREAD

**Issue by Paradokc** [publicsuffix/list#206]
Hello. 
Please remove saratov.ru from publicsuffix

**Comment by sleevi** [comment]
Can you explain why and how to authenticate this request?

**Comment by Paradokc** [comment]
I am the owner of domain. 
https://www.nic.ru/whois/?query=saratov.ru&opensearch=1
How can I confirm this for you?

**Comment by Paradokc** [comment]
And this domain name is not geographical from 2011

**Comment by sleevi** [comment]
It looks like the registry cancelled all geographic registrations in 2009, based on the footnote at https://cctld.ru/ru/docs/archive/detail.php?ELEMENT_ID=3446

@weppos @gerv It seems like we should update the .ru registry based on https://cctld.ru/ru/domains/domens_ru/reserved/ [[Translated]](https://translate.googleusercontent.com/translate_c?act=url&depth=1&hl=en&ie=UTF8&prev=_t&rurl=translate.google.com&sl=auto&tl=en&u=https://cctld.ru/ru/domains/domens_ru/reserved/&usg=ALkJrhhBecD5877hg48pF0LkPbL1D-tPLw) . Are there any concerns?

**Comment by gerv** [comment]
We've had at least one other of these come through... Is there an existing issue about this? Anyway, it would be great to find out the situation and make the PSL match.

**Comment by sleevi** [comment]
There isn't, @gerv, which is why I was hijacking this. I included more information about "the situation", so I'm trying to see what, if anything, else should be provided before we take action.

**Comment by weppos** [comment]
Most of the `.ru` entries were changed/added in 2008, one year before the regional hostnames were deleted.
https://github.com/publicsuffix/list/blame/master/public_suffix_list.dat

The removal of `mosreg.ru` was requested in 2014, see [Bugzilla#1090800](https://bugzilla.mozilla.org/show_bug.cgi?id=1090800). Here's the request body:

> We are Moscow Region Government. 
> Because CCTLD cancelled all geographical domain names on September 30, 2009 ( http://cctld.ru/ru/domains/domens_ru/domaintypes/ ). We need to delete the mosreg.ru domain from public suffix list

It looks like at that point we accepted the request, but we didn't fully investigate and realize that the cancellation would have affected most of the listed geographical domain names.

To mee it seems that we should sync the .ru list to match the content of https://cctld.ru/ru/docs/archive/detail.php?ELEMENT_ID=3446

Here's the (unsorted) list:

```
// industry

ac.ru
com.ru
edu.ru
int.ru
net.ru
org.ru
pp.ru

// geographical

adygeya.ru
bashkiria.ru
ulan-ude.ru
buryatia.ru
dagestan.ru
nalchik.ru
kalmykia.ru
kchr.ru
ptz.ru
karelia.ru
komi.ru
mari-el.ru 
joshkar-ola.ru
mari.ru 
mordovia.ru
yakutia.ru
vladikavkaz.ru
kazan.ru
tatarstan.ru
tuva.ru
udmurtia.ru    
izhevsk.ru
udm.ru  
khakassia.ru
grozny.ru
chuvashia.ru
altai.ru
kuban.ru
krasnoyarsk.ru
marine.ru
vladivostok.ru
stavropol.ru
stv.ru
khabarovsk.ru
khv.ru
amur.ru
arkhangelsk.ru
astrakhan.ru
belgorod.ru
bryansk.ru
vladimir.ru
volgograd.ru
tsaritsyn.ru
vologda.ru
voronezh.ru
vrn.ru
cbg.ru
ivanovo.ru
irkutsk.ru
koenig.ru
kaluga.ru
kamchatka.ru
kemerovo.ru
kirov.ru
vyatka.ru
kostroma.ru
kurgan.ru
kursk.ru
lipetsk.ru
magadan.ru
mosreg.ru
murmansk.ru
nnov.ru
nov.ru
nsk.ru
novosibirsk.ru
omsk.ru
orenburg.ru
oryol.ru
penza.ru
perm.ru
pskov.ru
rnd.ru
ryazan.ru
samara.ru
saratov.ru
sakhalin.ru
yuzhno-sakhalinsk.ru
yekaterinburg.ru   
e-burg.ru
smolensk.ru
tambov.ru
tver.ru
tomsk.ru
tsk.ru
tom.ru
tula.ru
tyumen.ru
simbirsk.ru
chelyabinsk.ru
chel.ru
chita.ru
yaroslavl.ru
msk.ru
spb.ru
bir.ru
jar.ru
palana.ru
dudinka.ru
surgut.ru
chukotka.ru
yamal.ru

// localities

amursk.ru
baikal.ru
cmw.ru
fareast.ru
jamal.ru
kms.ru
k-uralsk
kustanai.ru
kuzbass.ru
magnitka.ru
mytis.ru
nakhodka.ru
nkz.ru
norilsk.ru
snz.ru
oskol.ru
pyatigorsk.ru
rubtsovsk.ru
syzran.ru
vdonsk.ru
zgrad.ru

// state
gov.ru
mil.ru

// reserved
test.ru
```

**Comment by sleevi** [comment]
Simone: that's the old list (as indicated on the translated version of the
page)

Post 2009 there are no more geographical domains (see what I linked)

**Comment by weppos** [comment]
@sleevi oh, right, I thought that list was up-to-date, I've just noticed the other page you linked.
https://cctld.ru/ru/domains/domens_ru/reserved/

I'm a little bit confused by:

> Industry domains are intended for registration of third level domain names, taking into account sectoral, > departmental and other similar specificity. Ac.ru  - for scientific and research organizations; institutions > of higher education; cultural institutions, leading research edu.ru  - for schools that have a license for educational activity int.ru  - for international organizations

Specifically, the first line seems to implicitly indicate that there are industry domains (in fact they were listed in the previous page), but they are not listed here.

In other words, in addition to

```
ac.ru
edu.ru
int.ru
gov.ru 
mil.ru 
test.ru
```

it's possible we also have to include

```
ac.ru
com.ru
edu.ru
int.ru
net.ru
org.ru
pp.ru
```

It may be worth to get a confirmation from the registry.

**Comment by weppos** [comment]
@sleevi I found https://cctld.ru/en/news/news_detail.php?ID=634

> That is why, at its meeting the Council of the Coordination Center ruled to cancel the sectoral type of second-level domain names COM .RU, NET.RU, ORG.RU, PP.RU and geographic second-level domain names.

Therefore, it looks like the list published at the link you provided is complete (aka .com.ru & friends are no longer suffixed offered by the .RU registry).

However, the link also mention that these suffixes were transitioned to some private entities, hence some of them may still be alive and we should thread them as private domains (which makes the change a little bit more complicated as now we should also deal with those private entities).

**Comment by sleevi** [comment]
Right, this is where a policy on how to handle removals might be handy, @gerv ;)

I think we should definitely proceed with the saratov.ru removal, and it sounds like we may need to attempt to contact all of the "to-be-removed" holders? Or would you rather we keep them until they request otherwise?

**Comment by weppos** [comment]
@sleevi honestly, I'm kind of inclined to directly remove all geographical and localities names. The only entities I'd try to contact are the ones that today are managing the industry domains that have been reassigned.

Geographical and localities names were likely added in bulk because of registry constraints. As the registry demoted them to standard names (under the .ru suffix), my opinion is that we could consider to simply remove them.

Starting to formalize a removal policy is something I definitely endorse.

**Comment by sleevi** [comment]
@gerv Ping on https://github.com/publicsuffix/list/issues/206#issuecomment-211857024

**Comment by gerv** [comment]
I think it's becoming clear from multiple bug reports that all the .ru geographic names have been offered for sale. So we should just remove all of them, for some definition of "all of them", without trying to contact the new owners (some might not even have new owners).
