### ISSUE TITLE
How can i add a new sld for submission ?

### ISSUE THREAD

**Issue by anantsparrow** [publicsuffix/list#2075]
Hey there, i have one SLD already approved on the publicsuffix, how should i add a new one?

**Comment by wdhdev** [comment]
The PSL is volunteer run, and therefore not resourced to answer these kind of questions. Please read the [wiki](https://github.com/publicsuffix/list/wiki) to learn how to add and format an entry.

**Comment by groundcat** [comment]
As @wdhdev mentioned, please refer to the wiki for guidance as your primary reference. I think the same guidelines and requirements (expiration, reasoning, `_psl` records, etc.) will apply to your new entry addition, whether you have an existing entry or not.
