### ISSUE TITLE
Security advisory not functional

### ISSUE THREAD

**Issue by groundcat** [publicsuffix/list#2086]
https://github.com/publicsuffix/list/blob/4f58803a4353778a3ddd337f55e15ac6e7c3ce67/SECURITY.md?plain=1#L11

The security advisory link `https://github.com/publicsuffix/list/security/advisories/new` (added from #1856) is currently not functional and may require some [setup](https://docs.github.com/en/code-security/security-advisories/working-with-repository-security-advisories/about-repository-security-advisories) to be completed, if necessary.

**Comment by felixfontein** [comment]
I get a regular GitHub 404 page: 
![image](https://github.com/user-attachments/assets/1056c8c5-464e-4856-a94b-bca038d98ec7)

**Comment by dnsguru** [comment]
The PSL is a static text file.  I still scratch my head as to why tf we need to have any security advisory like this for ANY practical reason.

**Comment by simon-friedberger** [comment]
Because we have things like Github actions which are really easy to mess up in a way they give people write access to the repo. 😞

**Comment by simon-friedberger** [comment]
Could one of the admins please enable private reporting as described here: https://docs.github.com/en/code-security/security-advisories/working-with-repository-security-advisories/configuring-private-vulnerability-reporting-for-a-repository#enabling-or-disabling-private-vulnerability-reporting-for-a-repository

**Comment by simon-friedberger** [comment]
@weppos Would you mind? Or just make me an admin maybe?

**Comment by weppos** [comment]
I enabled the feature. Can someone given it another try and confirm it works? I am unable to test, as an admin I could already access it before.

**Comment by felixfontein** [comment]
It seems to work. I can access the form, and was able to submit a test report (it now says "Thank you for reporting a vulnerability to publicsuffix/list. Maintainers have been notified and will review your submission.").

**Comment by simon-friedberger** [comment]
@weppos Just FYI: It seems I cannot see the submissions on Github so yall will have to handle them.

**Comment by dnsguru** [comment]
Why again is this needed?

**Comment by wdhdev** [comment]
> Because we have things like Github actions which are really easy to mess up in a way they give people write access to the repo. 😞

**Comment by simon-friedberger** [comment]
Fixed afaiu.
