### ISSUE TITLE
.NYC.MN is Unregisterable

### ISSUE THREAD

**Issue by muidar** [publicsuffix/list#2112]
When you click Check Availability, it turns out to be 404.

**Comment by muidar** [comment]
website:http://registry.nyc.mn/

**Comment by wdhdev** [comment]
Interesting, I can indeed see that it returns 404. I'm not sure how this domain even got approved as when looking through the SSL certificate logs (https://crt.sh/?q=nyc.mn) there are less than 10 SSLs ever registered, and less than 3 that are active. When using a subdomain scanner, nothing is returned (https://subdomainfinder.c99.nl/), and when searching `site:nyc.mn` on Google, only the registry site is returned.

There does not seem to be evidence of any usage other than for the registry website which does not seem to work properly.

I think this domain should likely be removed, what are your thoughts @groundcat and @simon-friedberger?

**Comment by groundcat** [comment]
At a quick glance, it appears this registry site still exists and .nyc.mn can (probably) be registered through registrars like Marcaria (https://whois.marcaria.com/en/asia/mn-domain-search) so I'm not sure if the registry website is the only place for registration. The _psl TXT record exists, indicating an intention from the registrant to keep this domain in the PSL. Therefore, I'm slightly hesitant to remove it unless the initial requester or current registrant explicitly asks for its removal, although I agree with you the registration process seems to be dysfunctional and the usage is quite limited. In my opinion, how the registrant conducts their business internally might be beyond the scope and capacity of PSL volunteers to address. 

If the maintainers choose to remove this, I believe an overwhelming amount of similar entries in the PSL would also need to be removed. For example, `paris.eu.org` is in a similar situation (with usage not being visible), and many other domains might be in the same category. Maybe it's a good opportunity to establish a policy, but I wonder if the maintainers and volunteers would have enough resources to keep up. In my opinion, focusing on domains with NXDOMAIN, holds, or expired and repurposed statuses might be a more feasible approach for a removal policy.

It seems the MX records at `nyc.mn` is still active, so I suggest the first step would be to email `mattbrown@nyc.mn` to confirm and remove it if no response is received, following the [proposed procedure in PSL-discuss](https://groups.google.com/g/publicsuffix-discuss/c/Wb70HCsLKIQ) by @simon-friedberger which I believe would be a good policy to follow for removal PRs :)

**Comment by wdhdev** [comment]
The URL you provided does not actually support the extension, even though it is advertised. When you add a .nyc.mn domain to cart, it says `TLD NOT SUPPORTED`.

Tested URL: https://www.marcaria.com/ws/en/domain-search-results?domain=williamstestdomain.nyc.mn

![image](https://github.com/user-attachments/assets/f3032d36-9e7d-44fb-bd74-f6e2671d0b98)

**Comment by simon-friedberger** [comment]
Let's keep the rest of the discussion in the PR.
