### ISSUE TITLE
please merge pull request #64 (noip domains)

### ISSUE THREAD

**Issue by kaefert** [publicsuffix/list#213]
I've written a quick easy script that checks the required DNS TXT records and prints them in a way that their existence and correctness can be verified on a single glance.

[check_noip_dns-txt-records.sh.txt](https://github.com/publicsuffix/list/files/229442/check_noip_dns-txt-records.sh.txt)

Also noipcom has removed the date from their header and rebased on latest master as asked. Please tell us if anything else is missing or if there are any more obstacles that prevent you from merging the pull request https://github.com/publicsuffix/list/pull/64

Thank you for your efforts of maintaining this list and making the internet a safer place in the way!

**Comment by weppos** [comment]
Thanks @kaefert. Please, let's not duplicate the effort. 😉 

Duplicates #64

**Comment by kaefert** [comment]
@weppos thanks for your response, although it has not been what I hoped for. You did not tell us what else is missing and you did not merge the pull request.

Just another argument for the discussion about how (un?-)important the no-ip pull request might be, for example compared to some changes with russian local TLDs you mentioned as priority ranked above it for you.

Noipcom has 20 million users (see http://www.noip.com/about ) that use it as ddns provider, and that number does not include the users of websites hosted by those 20 million people. That is a lot of potentially problematic cookies that most of these users (both of the ddns service and of their hosted websites) are probably unaware of, and you could protect them.

Also the motivation of all those selfish people (me included) that have bugged you in the discussion of https://github.com/publicsuffix/list/pull/64 to get free certificates to be able to migrate from http to https with their services has a big potential to make the internet a safer place.

As already stated, all given requirements have been met and you either have already verified the pull request, or can very easily do so in a few minutes at the most - For example using my script - that you do not need to trust me to not contain any maleficent code, it only has 1 function "check" with two easily understandable lines and a list of the no-ip domains below it:
```bash
function check(){
 out=$(dig +short TXT "_psl.$1")
 echo "$out <- $1"
}
```

So please merge or tell us what else you need or why you can't or don't want to merge.

**Comment by sleevi** [comment]
As you note, this is already being discussed on #64. I will echo @weppos's
concerns - which are clearly spelled out on that bug - and indicate you are
making it much more difficult to give this issue the time, attention, and
coordination by opening bugs such as this and ignoring the remarks on the
parent bug.

We are working with NoIP to validate these domains, but being rude,
demanding, or opening additional bugs and demanding justifications is
neither productive nor within the spirit of positive contributions.

Thank you for understanding, and please do not reply further - instead,
watch the original bug.

**Comment by kaefert** [comment]
I am really sorry to be replying again, although you told me not to.
I am watching the original bug, and for me it looks like it is ready to be merged, but for some to me unknown / hidden reason it still isn't merged. 

You say you are in direct communication with the domain owner (noipcom), but there seems to be no information for anybody else. In this case sadly there are a lot of other people interested in this, with hardly any information to go on.

All I am asking is for you to be a bit more open with your information politics. Try to take your hoster here (github.com) as a role model, and just tell us what is happening. Why are you still not merging this pull request? Thank you.

**Comment by weppos** [comment]
> Why are you still not merging this pull request?

Because we haven't reviewed it yet. So please relax, be patient, and stop asking.

**Comment by kaefert** [comment]
I'm sorry, but I really don't understand it.

If what you are trying to tell me that you didn't have time to do it yet:
With that new verification method with those DNS TXT Records the verification would seem to me to be task that affords 5 minutes top. Much less than taking the time to converse with me here...

**Comment by weppos** [comment]
> Much less than taking the time to converse with me here...

Then stop asking and keeping us busy here, so that we have more time to work.

**Comment by kaefert** [comment]
So the last (publicly conceivable) action in the matter at hand here happened 1 month ago.

From my perspective it looks like the validation & merging of the referenced pull request would be a 5 minutes job for you, so once again I ask you the question:

Why are you not merging this pull request? Is there something someone outside your core team can do to help and or convince you to merge the no-ip domains into your list?

**Comment by gerv** [comment]
check_noip_dns-txt-records.sh.txt checked against list in PR, script run, all suffixes are validated in DNS.
