### ISSUE TITLE
Candidates for removal

### ISSUE THREAD

**Issue by danderson** [publicsuffix/list#2172]
I see @groundcat and @wdhdev have been going on a spree of removing dead entries ( :heart: ). While hacking on #2160 and trying to get the entire PSL to pass validation, I found the following domains that look suspiciously dead from a DNS perspective and may merit removal.

I'm not investigating them myself right now as I want to focus on getting more automation up, but if anyone does want to dig into them, here is the list of domains (I removed ones I could find that have an outstanding removal PR or have been pinged and are waiting for a reply). Let me know if there's a better place to call these out, I couldn't find an obvious place in my searches!

```
firm.ng TIMEOUT
ir.md TIMEOUT
n4t.co TIMEOUT
ybo.faith TIMEOUT
ybo.party TIMEOUT
ybo.review SERVFAIL
ybo.science TIMEOUT
ybo.trade TIMEOUT
```

Where `TIMEOUT` means there's no responsive DNS server at all, and `SERVFAIL` is... well, DNS server is up but responded with SERVFAIL instead of records. These have been consistently in this state for at least a month.

**Comment by danderson** [comment]
Trimmed the list down, I'd missed a few that @groundcat was already pinging. Apologies for the dupes!

**Comment by danderson** [comment]
One more, broken in a different way: `cnpy.gdn`.

The domain is expired according to whois. For some reason despite this status, it still has NS records and _psl.cnpy.gdn points to https://github.com/publicsuffix/list/pull/100. That PR is completely unrelated to cnpy.gdn, the correct PR would have been #633.

In #633 the owner of cnpy.gdn points to understory.live as the user-facing website for the entity. That domain is also expired and not currently registered, according to whois.

So, invalid _psl record and also lapsed registration - seems like an obvious removal.

**Comment by groundcat** [comment]
Thank you @danderson! For the entries you listed, I will track them with the current status below:

`firm.ng` – Following up in #2127. The requestor submitted their change two weeks ago and decided to keep `firm.ng` in the PSL. I will send them a reminder in #2127 via a comment to ensure their `_psl` record stays active at all times.

`ir.md` – Following up in #1625. I will raise a removal PR if no response is received from the initial requestor.

`n4t.co` – Following up in #257, but it is likely no response will be received. I will probably raise a removal PR for the dead/expired ones. This DDNS service is still operational (users can still register and use subdomains), but some of their domains have expired or are inactive, while some are still in use. The status of their operation is uncertain, and there has been a lack of moderation, leading to abuse. Multiple domains are in clienthold or serverhold status set by the registrar or TLD registry. The admin has been unresponsive for several months despite multiple attempts to reach them via email. An example is #2113.

`ybo.` – I agree with you that these dead domains should obviously be removed. I have raised PR #2173.

**Comment by irancms** [comment]
Hello,

First, I sincerely apologize for the issue and any confusion caused. We were in the process of a server migration, which led to the temporary downtime of our domain and subdomains. I’m pleased to inform you that the domain is now functioning correctly, and the project remains active.

We appreciate your efforts in maintaining the Public Suffix List and understand the importance of keeping it up to date. Please rest assured that the necessary _psl TXT record is being maintained, and the domain renewal is in good standing with more than two years before expiration.

Thank you for your understanding, and I look forward to ensuring continued inclusion in the PSL.

Best regards,
Ali Soizi
ir.md
https://github.com/publicsuffix/list/pull/1625

**Comment by simon-friedberger** [comment]
All of these should be resolved now.
