### ISSUE TITLE
Grammar and spelling in the wiki

### ISSUE THREAD

**Issue by wdhdev** [publicsuffix/list#2195]
There are quite a lot of typos in the wiki, along with a lot of bad grammar which I think should be fixed just so it is a bit more professional.

I've made a new repo which has a bunch of grammar/spelling/formatting fixes as I couldn't find a way to PR my changes here directly, so it might require a maintainer to manually update the wiki page by page.

Repo: https://github.com/wdhdev/updated-psl-wiki
You can see my updates here: https://github.com/wdhdev/updated-psl-wiki/commit/c284f7170ad7170e548523a1a61f74e9cfa0d9d1

**Comment by simon-friedberger** [comment]
(N.B. You can actually check out the wiki. You just can't create PRs for it.)

I've had a quick look and found some errors. Maybe make smaller commits so I can cherry-pick?

**Comment by wdhdev** [comment]
> (N.B. You can actually check out the wiki. You just can't create PRs for it.)

Yeah, that's why I created a separate repo for it.

> I've had a quick look and found some errors.

Fixed those.

> Maybe make smaller commits so I can cherry-pick?

As in a separate commit for each individual file, or each like individual change?

**Comment by simon-friedberger** [comment]
Up to your discretion, but if you mix manual changes with a code formatting that breaks things I cannot merge because I don't want to git-select individual hunks.

**Comment by wdhdev** [comment]
The code formatter was only updating that text it thought was italic, the rest was done manually.

And for updating the wiki, you should be able to just copy the raw content of each file on the GitHub repo, then just edit the page and overwrite the content on github.com instead of using the CLI.

**Comment by dnsguru** [comment]
I will read through it.  We have used 'edit as you go' method due to resourcing across the decade we were adrift from resources

**Comment by simon-friedberger** [comment]
I've merged this.
