### ISSUE TITLE
Please add stratoserver.net to publicsuffix list

### ISSUE THREAD

**Issue by lefty78** [publicsuffix/list#221]
The webhoster Strato is giving each Server of a customer an adresslike hXXXXXX.stratoserver.net. Each customer can run there his own website / domains an so on.

**Comment by weppos** [comment]
@lefty78 are you the owner of the domain?

**Comment by quackila** [comment]
+1

**Comment by fortax** [comment]
+1

**Comment by weppos** [comment]
Per our guidelines, only the owner can request the listing.
https://github.com/publicsuffix/list/wiki/Guidelines
