### ISSUE TITLE
Should all dynamic DNS providers have their domains in the PSL?

### ISSUE THREAD

**Issue by thezedwards** [publicsuffix/list#2243]
I've noticed that some dynamic DNS providers like noip[.]com and dynu[.]com have ~all of their domains listed in the PSL, but it appears the public domain list from FreeDNS @ https://freedns.afraid.org/domain/registry/ is not on the PSL? 

is this an oversight? or is there a potential reason this is the case? appreciate anyone's time or feedback.

**Comment by groundcat** [comment]
According to the [guidelines](https://github.com/publicsuffix/list/wiki/Guidelines), only the domain registrant is permitted to request their domain to be added to the PSL. We want this action to be taken deliberately by the domain holder. For example, `us.to` is one of the domains under FreeDNS, so only the registrant of `us.to` may submit a PR if all requirements outlined in the guidelines are met.

**Comment by thezedwards** [comment]
Cheers that totally makes sense, thank you for clarifying! I appreciate you explaining that section of the guidelines. Thanks for your time.

**Comment by thezedwards** [comment]
thanks again
