### ISSUE TITLE
Is `Results of Syntax Checker` still required?

### ISSUE THREAD

**Issue by wdhdev** [publicsuffix/list#2251]
I don't really see the point in the submitter running the tests on their machine, since all tests run on the PR regardless.

Would it be worth removing that section for the PR template?

The only reason I could think of to keep it is to just to minimise the amount of invalid PRs, however there are people who do lie about running the tests anyway, so whether it's in the template or not is irrelevant.

Let me know if I'm missing anything. The main reason for this issue is to try reduce the amount of unneeded content in the PR template as there is a fair amount of comments, etc, which can lead the submitter to potentially ignore them.

**Comment by simon-friedberger** [comment]
Agreed, could you make a PR to remove it, please?

**Comment by mozfreddyb** [comment]
Requires maintainers to manually approve the workflows though.

**Comment by simon-friedberger** [comment]
True but we do that anyway.
