### ISSUE TITLE
auto.pl is not a public suffix

### ISSUE THREAD

**Issue by bmarek0** [publicsuffix/list#2282]
auto.pl cannot be public suffix, as https://www.auto.pl/ is a Polish automotive portal offering free classified ads for selling passenger cars, commercial vehicles, trucks, motorcycles, and car parts.

I recommend to delete it from the PSL.

We found this bug using BigQuery NET.REG_DOMAIN function.

**Comment by groundcat** [comment]
I just confirmed with the registry on November 18, 2024, that the list of functional domain names is up to date:  
https://www.dns.pl/en/list_of_functional_domain_names.  

This list includes `auto.pl` as a valid suffix.  

The automobile website https://www.auto.pl/ you mentioned has actually smartly registered `www.auto.pl` under `auto.pl`. They are not taking over `auto.pl` at the second level but rather using `www.auto.pl` as a third-level domain.  

The .PL registry did not reserve the `www` string to prevent registration, which is something many other registries often do to avoid confusion.  

A quick Google search for `site:auto.pl` (https://www.google.com/search?q=site%3Aauto.pl) shows many other websites using `auto.pl` as a suffix, which are unrelated to the `www.auto.pl` website.  

Therefore, `auto.pl` should still be considered a public suffix.
