### ISSUE TITLE
The effects of both a non-wildcard and wildcard entry

### ISSUE THREAD

**Issue by wdhdev** [publicsuffix/list#2297]
Reference: https://github.com/publicsuffix/list/pull/2237#issuecomment-2440753994

We don't have any existing entries that combine both a non-wildcard entry (e.g. `example.com`) and a wildcard entry (e.g. `*.example.com`).

Do we actually know the effects of having both? Do they work together, how do browsers interpret them? Would it be worth testing this?

**Comment by wdhdev** [comment]
Wow, that is quite complex. Thanks for researching into this, it is quite interesting how the PSL is interpreted.

Regarding Cloudflare's limitation, you can contact CF staff to actually get a public suffix added manually, I have done this before multiple times.

It is still quite tempting to run a test with both to see what would actually happen in a production version of the list (the scientific method, sort of? 🤣). However it could potentially break some parsers that aren't expecting 2 rules for the same domain, so probably not the best to do.

**Comment by simon-friedberger** [comment]
> Regarding Cloudflare's limitation, you can contact CF staff to actually get a public suffix added manually, I have done this before multiple times.

Thank you! TIL!
