### ISSUE TITLE
How to run the tests?

### ISSUE THREAD

**Issue by erikdubbelboer** [publicsuffix/list#23]
Can you please add some documentation on how to run the tests.

**Comment by rockdaboot** [comment]
While the docs should be added, have a look at https://github.com/rockdaboot/libpsl
You'll find C source code in the tests/test-registrable-domain.c directory that performs the tests (using libpsl).

**Comment by ErikDubbelboer** [comment]
I guess #26 would close this issue as it shows exactly how to run the tests.

**Comment by weppos** [comment]
@erikdubbelboer #26 was closed. Feel free to reopen this issue if you feel the solution is not sufficient.
