### ISSUE TITLE
Remove re-registered domains

### ISSUE THREAD

**Issue by fakeboboliu** [publicsuffix/list#2345]
After fix the [groundcat/private-domains-checker](https://github.com/groundcat/PSL-private-domains-checker/pull/5), 
I found several re-registered domains that does not have `_psl` records while checking if it works well. 
Maybe first step removing them? It should indicate it's safe for removal.

 - `platter-app.com` (reg 2023/6/16, pr #935 2020/4/4)
 - `drud.us` (reg 2021/2/10, pr #234 2016/7/9)
 - `spacekit.io` (reg 2022/5/10, pr #166 2016/6/8)
 - And more...

And a lot of other domains no longer have `_psl` remains but should have to (after 2016):
 - `netfy.app` (#1991, 6mo ago)
 - `durumis.com` (#1978, 7mo ago)
 - More and more...

That could be another opportunity for volunteers, but I haven't had much free time until Chinese New Year. (In fact, as you can see, I have already started to talk nonsense now)

**Comment by wdhdev** [comment]
We have recently been removing quite a lot of these, and I have some open PRs removing a few of them.

I'll look into opening a few more removal PRs in a little bit.
