### ISSUE TITLE
define "registrable domain"  "registered domain"  on publicsuffix.org/list

### ISSUE THREAD

**Issue by equalsJeffH** [publicsuffix/list#236]
the Algorithm section of https://publicsuffix.org/list/ contains this step:
`7.  The registered or registrable domain is the public suffix plus one additional label.`
..but "registered domain" and "registrable domain" are not defined. 

Discussion with `<team@publicsuffix.org>` yielded these definitions:
```
A registered domain is a domain that is registered - which is a process
defined within the domain name system related to the IANA functions,
ICANN, the notion of domain "registries", and as such, is why I'm having
trouble finding an alternative definition.

A registerable domain is similarly a domain which might be registered,
even if it is not presently.
```
Perhaps the above definitions (or refinements thereof) could be added to https://publicsuffix.org/list/ ?

**Comment by rockdaboot** [comment]
You can clone https://github.com/publicsuffix/publicsuffix.org and create a pull request with your changes.

**Comment by weppos** [comment]
Feel free to provide a patch at https://github.com/publicsuffix/publicsuffix.org

**Comment by equalsJeffH** [comment]
am not sure why you closed this prior to receiving a PR that fixes it.

**Comment by weppos** [comment]
Hi @equalsJeffH, I closed this because this is the repo for the list itself. We've working to clear the backlog of listing requests, and I didn't want to keep more things that were not strictly related to the listing.

**Comment by equalsJeffH** [comment]
Ok, thx.
