### ISSUE TITLE
Please add 2nd level cook islands TLDs

### ISSUE THREAD

**Issue by kyle-mt** [publicsuffix/list#237]
IANA (https://www.iana.org/domains/root/db/ck.html) points to http://www.oyster.net.ck which redirects to http://www.telecom.co.ck/ which has no domain registration information whatsoever.
Wikipedia mentions http://www.oyster.net.ck/about/index.php?about=domain
that page is defunct, but https://archive.is/Rx6H shows the following tlds:

```
.co.ck: business organisations
.org.ck: not-for-profit organisations
.edu.ck: educational institutions
.gov.ck: government agencies
.net.ck: Internet Service Providers
```

Additionally, Wikipedia (https://en.wikipedia.org/wiki/.ck) shows the following list of tlds:

```
.co.ck: business organisations
.org.ck: not-for-profit organisations
.edu.ck: educational institutions
.gov.ck: government agencies
.net.ck: Internet Service Providers
.gen.ck:
.biz.ck: Business related pages for the Cook Islands
.info.ck: Information pages relating to the Cook Islands
```

Unfortunately, I'm not sure what would be considered an authoritative answer here. Anecdotally, I can find domain registrars available out on the internet for .biz.ck, .co.ck, .gen.ck, .info.ck, .net.ck,, and .org.ck, but not .ck.

I also noticed that the .ck TLD is associated with test data (https://github.com/publicsuffix/list/blob/master/tests/test_psl.txt#L62), but I wasn't able to figure out where or how cookie authorization was determined (per https://publicsuffix.org/list/#list-format).

**Comment by weppos** [comment]
I sent an email to the recipients listed as admin and technical in the IANA entry. I'll get back as soon as I receive an update.

**Comment by weppos** [comment]
No response yet.

**Comment by kyle-mt** [comment]
I appreciate the check-ins. Any luck yet?

**Comment by weppos** [comment]
Closing as I was (sadly) not able to get in touch with anyone, nor to validate the suffixes.
