### ISSUE TITLE
please update .BA 2nd level ccTLD PSL

### ISSUE THREAD

**Issue by enesh** [publicsuffix/list#241]
Currently the following secondary level public domains are open for registration:

edu.ba
gov.ba
net.ba
org.ba
mil.ba

References:
https://www.iana.org/domains/root/db/ba.html
http://nic.ba/users_data/files/pravilnik_o_registraciji.pdf

**Comment by weppos** [comment]
It looks like `com.ba` is also available, although not for registration (delegated).

![screen shot 2016-06-12 at 14 27 54](https://cloud.githubusercontent.com/assets/5387/15991140/f189f61c-30a9-11e6-9220-c7ce2db1df8e.png)

There are at least a few URLs.
https://www.google.com/?ion=1&espv=2#q=allinurl%3A.com.ba

**Comment by enesh** [comment]
You are right, subdomain com.ba is delegated to BHTelecom (https://www.bhtelecom.ba) and they should provide registration under .com.ba domain (currently  they do not provide registration over the public interface)
