### ISSUE TITLE
Please add browsersafetymark.io to list

### ISSUE THREAD

**Issue by dtharp** [publicsuffix/list#247]
Pull request is : https://github.com/publicsuffix/list/pull/228

The email in the pull request is the official contact point (browsersafetymark.io@quicinc.com).

Unfortunately I can't put the requisite TEXT record in DNS (my IT department is, well, challenged). I can provide proof that I'm the official contact/owner for the domain via email.

**Comment by dtharp** [comment]
Note there's an updated pull request: #251 

We can close #228

**Comment by weppos** [comment]
Closing in favor of #251

**Comment by dtharp** [comment]
@weppos Pardon, but I'm confused here.  You have closed this **Issue** "in favor of" my **Pull Request** #251 ? That doesn't even make sense to me.  The pull request is still open, and now, again, enough time has passed so it needs to be re-based **again**.  And not there's not even an open issue attached to it (since you closed it), so I presume my pull request is now orphaned.

This was my second attempt and getting this landed.  Clearly I don't understand the process (and the website/wiki isn't definitive). Here are the steps and process as I understand it.  Please correct me where I'm wrong.

1. Submit a pull request
2. Submit an issue referencing the pull request
3. Someone from your team sees the issue, and looks at the pull request
4. Since the pull request is fresh, passed the tests, and it doesn't need rebasing because it hasn’t languished for weeks, it gets landed, and the issue gets closed.

What am I missing here? I want to completely understand the process before I waste more weeks with no results, and another stale pull request.

**Comment by weppos** [comment]
@dtharp the pull request is enough as reference, there is no need to have an issue AND a pull request.

As for the timing, are you can see we've been actively merging a lot of requests lately. It's an effort for you to keep your PR in sync, but it's an effort for us as well to manage all the requests and follow up with everybody.

Also, please note that we need you to follow the guidelines posted here
https://github.com/publicsuffix/list/wiki/Guidelines
and add the records for validation.

**Comment by dtharp** [comment]
@weppos Thanks for the reply. I appreciate that you all are busy.

As far as following the guidelines, I have tried really. Unfortunately, my IT department is either clueless or just unwilling to set the requisite DNS TXT records. (For some reason, probably paranoia, they allow us to host our servers on AWS, but disallow letting us use Route66 -- they manage DNS internally). 

The guidelines mention that email Authentication is appropriate in some cases.  I'm hoping I qualify for this.  We have set up a mailing list for the site : browsersafetymark.io@quicinc.com.

So...
- is it possible to do email auth in this case?
- If so, how do I go about submitting a PR and getting it landed before it goes stale again?

**Comment by weppos** [comment]
@dtharp DNS validation is preferable because it is faster. Moreover, in a future it's possible we'll require to persist a DNS record, otherwise we'll remove the data from the PSL.

I tried to validate the data from the whois record, but sadly although the contact data generally matches, I can't find a correspondence between the registrant email listed at the whois (http://nic.io/cgi-bin/whois) and quicinc.com.

The only correspondence is MarkMonitor, which however is indeed not your company.

Unfortunately, that makes it very hard to go with email validation.
