### ISSUE TITLE
Please add .cn.com to list

### ISSUE THREAD

**Issue by hanfeihan1992** [publicsuffix/list#253]
Please add .cn.com to list

www.gybg.cn.com

**Comment by weppos** [comment]
@hanfeihan1992 are you the owner of that suffix?

**Comment by hanfeihan1992** [comment]
@weppos No, maybe the owner is http://www.cn.com/

**Comment by weppos** [comment]
As per our guidelines, we can only add a private domain if they submit it.
https://github.com/publicsuffix/list/wiki/Guidelines
