### ISSUE TITLE
Now-IP DDNS domains

### ISSUE THREAD

**Issue by Now-DNS** [publicsuffix/list#257]
Please add the following domains to the private section;

now-ip.org
now-ip.net
zapto.xyz
now-ip.xyz
16-b.it
32-b.it
64-b.it
forumz.info
x443.pw
mypi.co
tcp4.me
myiphost.com
crafting.xyz
001www.com
hicam.net
n4t.co
ntdll.top
dnsup.net

 Thank you!

**Comment by weppos** [comment]
Please read the Guidelines for proposing private domains
https://github.com/publicsuffix/list/wiki/Guidelines

Ideally, you should provide a patch and provide the relevant information to proceed and validate the request.

**Comment by Now-IP** [comment]
[domains.txt](https://github.com/publicsuffix/list/files/344604/domains.txt)

**Comment by weppos** [comment]
Please read the guidelines and provide a PR if needed.
https://github.com/publicsuffix/list/wiki/Guidelines

**Comment by groundcat** [comment]
Hello @Now-DNS , it seems that the project or organization associated with your domain, which was merged into the Public Suffix List (PSL), may no longer be active based on the observable usage of subdomains. 

- n4t.co TIMEOUT (See #2172)
- 001www.com NXDOMAIN  #2113
- now-dns.top NXDOMAIN  #2113

If the service has been decommissioned and the domain is no longer linked to an active project, as outlined in your original request, please confirm whether it can be safely removed from the PSL. This will help prevent leaving unnecessary entries for PSL volunteers and future registrants, as requesters often "set and forget" and neglect to request the removal of their domains from the PSL when their project reaches its end of life (EOL).

The PSL is a globally used resource, and it's important to understand that tens of millions, if not hundreds of millions, of devices and users incorporate the list. We aim to keep it as minimal as possible for those who truly need PSL inclusion. Projects that are smaller in scale, such as those without thousands of users or subdomains belonging to thousands of individual entities, will likely be ineligible for inclusion. If you no longer need your entry to remain on the PSL, **please create a new pull request to remove it** or reply here to confirm.

If your project or organization is still active and requires continued inclusion in the PSL, please reply at your earliest convenience. If we do not hear back from you for an extended period, **your entry may be subject to removal**. 

Additionally, ensure that the required `_psl` TXT record is maintained, as specified in the [PSL Guidelines](https://github.com/publicsuffix/list/wiki/Guidelines#validation-of-submissions--always), and that your domain is kept renewed with an expiry date of more than 2 years at all times to avoid future removal.

Thank you.
