### ISSUE TITLE
Add a comment on top of the list, asking people to pull the list from the right URL

### ISSUE THREAD

**Issue by timdream** [publicsuffix/list#258]
With MXR gone, code like these are now broke.

https://github.com/search?q=https%3A%2F%2Fmxr.mozilla.org%2Fmozilla-central%2Fsource%2Fnetwerk%2Fdns%2Feffective_tld_names.dat&ref=searchresults&type=Code&utf8=%E2%9C%93

We should add a minimum comment on top of the list, ask people writes new code to pull the file from https://publicsuffix.org/list/public_suffix_list.dat

**Comment by timdream** [comment]
I can prepare a pull request if people agrees.

**Comment by weppos** [comment]
@timdream I agree to add a comment at the top of the list that references https://publicsuffix.org/list/public_suffix_list.dat

It would be a good idea regardless MXR, as people may find the file online and it is helpful to have a quick reference.

Feel free to provide a patch.
