### ISSUE TITLE
TLD xn--90ae is missing in PSL

### ISSUE THREAD

**Issue by erikvanderpoel** [publicsuffix/list#263]
The TLD xn--90ae appears to be missing in the PSL.

http://www.iana.org/domains/root/db/xn--90ae.html

This bug may be similar to https://github.com/publicsuffix/list/issues/181

**Comment by gerv** [comment]
@sleevi do you have a syncing script for these? If not, perhaps Erik could kindly do a comparison for us and give us a pull request.

Gerv

**Comment by erikvanderpoel** [comment]
sleevi added this in https://github.com/publicsuffix/list/commit/0fdf7e85709a020049602b4218dabb255525cd68
