### ISSUE TITLE
.post has structure

### ISSUE THREAD

**Issue by pzb** [publicsuffix/list#270]
Table 2 in https://www.upu.int/fileadmin/documentsFiles/activities/dotPost/policyManagementDotPostEn.pdf lays out the heirarchy for .post, including com.post, edu.post, and org.post plus ISO 3166-1 alpha 2

Based on the .post zone file, there are currently names registered with three labels under ao, ci, es, id, kh, ma, mo, my, nl, ug, uy, za and org.

**Comment by dnsguru** [comment]
Spoke with @pzb on this as a follow-up.  There is some structure within the .POST TLD according to the zone file, but we'd want the registry themselves to provide this directly, and it looks complex to parse deep into the namespace defined within the document.  

The UPU file link was no longer working, here is the [Archive.org version](https://web.archive.org/web/20181005165818/https://www.upu.int/fileadmin/documentsFiles/activities/dotPost/policyManagementDotPostEn.pdf)

Will close this for now but keep for archival purposes and flag this as a namespace with heavy structure and potentially many levels, akin to .US #274  and #276 , .NAME #277, .BR or .JP (certainly others exist) where the ICANN section might exponentially grow (#277 proposed adding nearly 20k lines to PSL).

We may look at some means to address the more heavily structured TLDs in the future, but for now, we'll close this ticket and reference it in the roadmap.
