### ISSUE TITLE
name TLD missing suffixes

### ISSUE THREAD

**Issue by pzb** [publicsuffix/list#275]
The PSL says "name : has 2nd-level tlds, but there's no list of them"

https://gist.github.com/6aa9f1a509ecb6a6ec44b46de387a449 contains a list of the over 19,000 registerable namespaces.  Does the PSL want to include this large list?

**Comment by dnsguru** [comment]
We've fallen back to allowance of these individually being submitted into the private section, or alternatively if Verisign submitted a URL to the list of registry SLD under .name to us with a pull request to modify their comment line to include it, that would keep the PSL from growing exponentially.
