### ISSUE TITLE
Domains in freedns.afraid.org

### ISSUE THREAD

**Issue by tracker1** [publicsuffix/list#278]
Just curious, I have bbs.io in freedns.afraid.org, and would like to get it added to the public suffix list, should I create a FreeDNS.afraid.org entry, and put it under there, or should I just do a bbs.io entry and have it there by itself.

**Comment by weppos** [comment]
Only the owner of the domain is allowed to ask the entry to be listed (see #271). If you are interested in being able to obtain certificates with Let's Encrypt, they now offer a form to bypass request limits.
