### ISSUE TITLE
Split list source into multiple files

### ISSUE THREAD

**Issue by pzb** [publicsuffix/list#296]
Given the potential for the PSL to grow considerably in size (between private suffixes, the large number of new gTLDs, IDN ccTLDs, Spec13, etc), maybe the list should be maintained in multiple files which can get compiled together.  To start breaking it into four files would seem to make sense:
- Spec13 gTLDs
- ccTLDs (including IDN ccTLDs)
- Other TLDs (not covered the above groups)
- Private suffixes

The current `public_suffix_list.dat` could be compiled by combining all four with boundary text, but this would make the list more maintainable and also allow consumers who don't need the full list to access it in parts.

**Comment by sleevi** [comment]
I'm not sure why you feel it would be more maintainable. Consumers who don't need the full list can already compile it out.

I'm not opposed to it, but I don't think this ranks in the high order bits of concerns

**Comment by gerv** [comment]
The issue here is that the current format is non-extensible and already a bit hacky; adding in e.g. Spec13 gTLDs would complicate the format further. I don't think multiple files is the answer, I think a new format is the answer which is a superset of the current format, and from which the current format can be automatically generated. So people can then choose to either import the old or the new file, and parse it accordingly.

**Comment by weppos** [comment]
I agree that a possible long-term solution is to provide the list in a format that is flexible enough to be easily parsed and re-compiled according to consumer's needs.

As of today, for example, the only possible (easy) transformation is to separate IANA vs Private suffixes. Any other futher elaboration (e.g. separating new gTLDs vs TLDs) can't be achieved from the existing source.

However, it's also questionable whether this is the scope of the PSL. If someone wants to compile a list of different types of TLDs, there are other projects that may be more appropriate (e.g. https://github.com/zonedb/zonedb).

The size of the current list may or may be irrelevant. It's true, it's one giant file, but it's also true that any consumer has the freedom to download, parse, shrink, split and adapt the list. In fact, AFAIK almost nobody uses the original file.

That said, I think a starting point could be to try to understand what the current list makes hard to accomplish. @pzb I would be interested to know if your proposal originates from a specific requirement that is currently hard to achieve with the current list.

Practical needs may make easier to understand the flaws of the current solution that needs to be addressed (e.g. format, syntax, etc).

**Comment by weppos** [comment]
@pzb just a ping to see if this request is still valid, or if you changed your mind.
If it is, I would be interested to learn more about the reason (as per my last comment).

**Comment by sleevi** [comment]
Marking WontFix. Splitting into individual files doesn’t necessarily help the extensibility, which seems to be the real goal here. While valid, figuring out the objectives of a new format are probably best for a new bug.
