### ISSUE TITLE
Add .vlogs.com.br in Public Suffix List

### ISSUE THREAD

**Issue by ghost** [publicsuffix/list#298]
1) Cookies may not be set for .br
2) Cookies may not be set for .com.br
3) Cookies may not be set for .vlogs.com.br

**Comment by weppos** [comment]
Please have a look at the submission guidelines.
https://github.com/publicsuffix/list/wiki/Guidelines

Can you please clarify the request? It's not clear which kind of rule you are submitting. Also, if you plan to submit a PR, there is no need to open also a separate ticket.

**Comment by rhuano** [comment]
Thanks
