### ISSUE TITLE
Update ICANN NewTLDs section to include TLDs contracted with ICANN through 2015-06-10

### ISSUE THREAD

**Issue by dnsguru** [publicsuffix/list#3]
Includes the following new ICANN gtlds: 
bet, dds, grainger, metlife, pet, srl, theatre, app, apple, beats, blog, extraspace, hkt, nowtv, olayan, olayangroup, pccw, richardli, security, vig, volkswagen, xn--fzys8d69uvgm, xn--mgba7c0bbn0a, xperia, aarp, aetna, audi, dot, mlb, nikon, amica, bostik, game, games, dtv, lamborghini, locker, moto, ollo, ott, weber

For Search, the following are the U-Labels
xn--fzys8d69uvgm = 電訊盈科
xn--mgba7c0bbn0a = العليان

Domains with ICANN contract announcements between 05/05/2015 and 06/10/2015.

**Comment by dnsguru** [comment]
I've submitted a patch in a fork - and a request @gerv to document the new process for 

additions
changes
'approval' (for lack of better term on consensus used in deciding what makes it in)

-J

**Comment by gerv** [comment]
Hi Jothan,

When I click "Pull Requests" for this repo I don't see any. Are you sure you've issued a pull request? You need to click the green button near the top left of:
https://github.com/dnsguru/list/tree/dnsguru-patch-1

Gerv

**Comment by dnsguru** [comment]
Gerv there are a ton that have added since 7 June so I'll incorporate all

**Comment by gerv** [comment]
Now fixed by #8.
