### ISSUE TITLE
New Amazonaws.com address

### ISSUE THREAD

**Issue by MikeSchroll** [publicsuffix/list#309]
Looks like s3.amazonaws.com is returning a CNAME to s3-1.amazonaws.com

since amazonaws.com is not listed as a suffix, only s3.amazonaws.com; this now means it doesn't match.

Looks as though there is also an s3-2.amazonaws.com

**Comment by sleevi** [comment]
Closing this as WontFix.

A CNAME does not mean it needs to be added, but also because Amazon's team is the one responsible for requesting and reviewing PSL changes for Amazon domains, which they have.
