### ISSUE TITLE
Remove mil.by from public suffix list.

### ISSUE THREAD

**Issue by postmaster-mod-mil-by** [publicsuffix/list#315]
Need this change to make DMARC policy for mil.by domain work on all sub-domains of mil.by.

```
--- public_suffix_list.dat      2016-10-10 18:28:21.311338502 +0300
+++ public_suffix_list.dat.new  2016-10-10 18:28:43.702798491 +0300
@@ -501,7 +501,6 @@
 // list of other 2nd level tlds ?
 by
 gov.by
-mil.by
 // Official information does not indicate that com.by is a reserved
 // second-level domain, but it's being used as one (see www.google.com.by and
 // www.yahoo.com.by, for example), so we list it here for safety's sake.
```

**Comment by weppos** [comment]
Hi @postmaster-mod-mil-by, as this is a registry suffix, we need to authenticate your request to make sure you are entitled to represent the .BY registry.

Can you please send us an email to team@publicsuffix.org from an official email approving this request?

I also have two extra questions for you.

1. You mentioned that you:

> Need this change to make DMARC policy for mil.by domain work on all sub-domains of mil.by.

Can you explain it further? Having `mil.by` listed it means that the following subdomains are effectively treated as separate domans:

- foo.mil.by
- bar.mil.by

If you remove it, you are indicating that all these subdomains can share security policies (e.g. a cookie set by foo.mil.by would be applied also to bar.mil.by). Is it what you want?

It's also the first time I hear that being listed affects a DMARK policy. I would be interested to learn more.

2. It looks like the .BY TLD is quite outdated (and we originally grab the information from third party sources. I see https://domain.by/ has several suffixes listed (e.g. at.by or net.by). Would you be able to provide an official list of suffixes for the .BY TLD?

**Comment by postmaster-mod-mil-by** [comment]
> Can you explain it further? Having mil.by listed it means that the following subdomains are effectively treated as separate domans:
>
>   foo.mil.by
>   bar.mil.by
>
>If you remove it, you are indicating that all these subdomains can share security policies (e.g. a cookie set by foo.mil.by would be applied also to bar.mil.by). Is it what you want?

All sub-domains of mil.by belong to Belarus Ministry of Defence or subordinated organizations, so they do share security policy. 
I see mil.by not as a public domain but as Belarus Ministry of Defence domain.

>It's also the first time I hear that being listed affects a DMARK policy. I would be interested to learn more.

DMARC policy for Organizational Domain is used for all sub-domains that have no DMARC policy defined.
mil.by is in Public Suffix List,  therefore in terms of DMARC it can't be used as Organizational Domain ([RFC 7489](https://tools.ietf.org/html/rfc7489#page-8))

> It looks like the .BY TLD is quite outdated (and we originally grab the information from third party sources. I see https://domain.by/ has several suffixes listed (e.g. at.by or net.by). Would you be able to provide an official list of suffixes for the .BY TLD? 

No.

**Comment by dnsguru** [comment]
History (#315 and #316)
#316 was closed and wontfix

We shall close this issue for now.  If this required further consideration at a later time, submit this request again with another PR submission along with the appropriate _PSL DNS TXT records to validate / verify.
