### ISSUE TITLE
SSL certificate of publicsuffix.org cannot be verified

### ISSUE THREAD

**Issue by cmtt** [publicsuffix/list#33]
Hello publicsuffix team,

I am the maintainer of the [publicsuffixlist](https://github.com/cmtt/publicsuffixlist) module for Node.js.
By the way, it would have been great to see it at https://publicsuffix.org/learn.

One of its users has [reported](https://github.com/cmtt/publicsuffixlist/issues/5) an issue while the module was attempting to download a recent version of the list - which is part of its installation routine.

Further research has shown, that on the users' OS (a debian-based distribution) download managers like cURL and wget reject the certificate, too. In contrast, browsers like Firefox and Google Chrome do not complain about the certificate as they seem to bundle more recent certificates.

In a recent MacOS X 10.10.5 environment, the file is downloaded flawlessly, but I couldn't verify this on "Windows".

When attempting to download the list with cURL, the debug options returns the following:
````
$ curl https://publicsuffix.org/list/public_suffix_list.dat
* Hostname was NOT found in DNS cache
*   Trying 63.245.217.20...
* Connected to publicsuffix.org (63.245.217.20) port 443 (#0)
* successfully set certificate verify locations:
*   CAfile: none
  CApath: /etc/ssl/certs
* SSLv3, TLS handshake, Client hello (1):
* SSLv3, TLS handshake, Server hello (2):
* SSLv3, TLS handshake, CERT (11):
* SSLv3, TLS alert, Server hello (2):
* SSL certificate problem: unable to get local issuer certificate
* Closing connection 0
curl: (60) SSL certificate problem: unable to get local issuer certificate
More details here: http://curl.haxx.se/docs/sslcerts.html

curl performs SSL certificate verification by default, using a "bundle"
 of Certificate Authority (CA) public keys (CA certs). If the default
 bundle file isn't adequate, you can specify an alternate file
 using the --cacert option.
If this HTTPS server uses a certificate signed by a CA represented in
 the bundle, the certificate verification probably failed due to a
 problem with the certificate (it might be expired, or the name might
 not match the domain name in the URL).
If you'd like to turn off curl's verification of the certificate, use
 the -k (or --insecure) option.
````

The same is valid for the former location: https://publicsuffix.org/list/effective_tld_names.dat?raw=1 - wget returns the following:
````
Connecting to publicsuffix.org (publicsuffix.org)|63.245.217.20|:443... connected.
ERROR: cannot verify publicsuffix.org's certificate, issued by ‘CN=DigiCert SHA2 Secure Server CA,O=DigiCert Inc,C=US’:
  Unable to locally verify the issuer's authority.
To connect to publicsuffix.org insecurely, use `--no-check-certificate'.
````

At the moment, this issue forces me to disable certificate validation while downloading.
This should be regarded solely as temporary workaround for all users who want to deploy their applications on Debian-based servers.

**Comment by sleevi** [comment]
@gerv - Sounds like an issue for Mozilla infrastructure team; could you open up a Bugzilla with them?

publicsuffix.org is sending the static-san.mozilla.org cert, but it's not sending the "DigiCert SHA2 Secure Server CA" intermediate.

It's unclear whether that will fix _node's_ issue, but should resolve the curl/wget issues (which, as we know, are incredibly sensitive to configuration issues and unable to handle the WebPKI completely)

**Comment by rockdaboot** [comment]
@gerv As a quick workaround (download cert and give it to wget):
$ wget https://www.digicert.com/CACerts/DigiCertSHA2SecureServerCA.crt
$ openssl x509 -inform DES -in DigiCertSHA2SecureServerCA.crt -out DigiCertSHA2SecureServerCA.pem -outform PEM
$ wget -d --ca-certificate=DigiCertSHA2SecureServerCA.pem 'https://publicsuffix.org/list/effective_tld_names.dat?raw=1'

**Comment by gerv** [comment]
See https://bugzilla.mozilla.org/show_bug.cgi?id=1201820 .

**Comment by w0ts0n** [comment]
I believe this is resolved. (The curl works for me now)

**Comment by cmtt** [comment]
Thanks a lot for the quick reactions.
The issue has been resolved, signature verification will be re-enabled with the next version of the module.
