### ISSUE TITLE
Missing extensions

### ISSUE THREAD

**Issue by Chybeck** [publicsuffix/list#343]
Hi Guys,

I work for a worlwide registrar. We try our best to get accredited everywhere.

For the record, here are some missing public extensions  :

co.ee
com.ne
com.kw
ni
com.bn
com.bj
co.ke
com.ye
com.mz
com.bd
com.kh
co.zw
com.mm

It's 100% reliable since it corresponds to domain names we actually registered.

Regards,

Antoine.

**Comment by gerv** [comment]
@Chybeck: how do you know these extensions are public (i.e. run by the NIC; would go in the ICANN section of the PSL) and not private (i.e. run by a private company; would go in the PRIVATE section)?

**Comment by Chybeck** [comment]
Oh sorry, I didn't know you make that distinction (does it really makes sense?). By "public" I meant that one can be accredited/authorized to register within these extensions. 

For .NI , COM.BJ, .CO.ZW, it's the NIC itself for sure.
Most of the others are ruled by local registrars, generally with the complicity of the NIC.
ex: com.ne http://www.nigerhosting.net/

**Comment by gerv** [comment]
@Chyback: for private ones, the owner themselves has to apply. For public ones, we can add them, but it helps if you can demonstrate (e.g. using a URL on the NIC's website) that they are definitely public suffixes.

**Comment by weppos** [comment]
Closing as no actionable. Please provide specific patches where applicable and according to the [Guidelines](https://github.com/publicsuffix/list/wiki/Guidelines).
