### ISSUE TITLE
Add .jur.pro.br Private Domain Section  

### ISSUE THREAD

**Issue by SuffixJUR** [publicsuffix/list#352]
+// Company : http://www.registry.jur.pro.br
+// Submitted by Jean Turola <suffix@jur.pro.br>
+jur.pro.br

**Comment by weppos** [comment]
Duplicates #324

**Comment by RegistryPRO** [comment]
@weppos This was done by another team within the organization, for inclusion of the suffix in the PublicSuffix.org catalog.We were not aware of this duplicate request, made by 2 different teams of the organization.Is the data supplied sufficient or not?
