### ISSUE TITLE
Should second-level domains of .il be listed in the PSL?

### ISSUE THREAD

**Issue by mjball** [publicsuffix/list#38]
According to [Wikipedia][1] and [ISOC-IL][2], there are eight second-level domains under `.il`. Given my limited understanding of the PSL, it seems like those eight<sup>1</sup> should be listed in addition to `*.il`. Otherwise the public suffix of, for example, `clean-carpets.co.il` will be identified as `il` when it should be `co.il` – as I understand it.

Please let me know if I'm totally wrong here. 

-------

<sup>1</sup> `ac.il`, `co.il`, `org.il`, `net.il`, `k12.il`, `gov.il`, `muni.il`, and `idf.il`

[1]: https://en.wikipedia.org/wiki/.il
[2]: http://www.isoc.org.il/domains/il-domain-rules.html

**Comment by sleevi** [comment]
*.il means that all second-level domains are treated as public suffices.

Thus for clean-carpets.co.il, it will be identified as co.il, because 'co.il' matches the '*.il' rule of being a public suffix.

**Comment by mjball** [comment]
Ok - then this is definitely a bug in my PSL implementation. Thanks for the quick followup!
