### ISSUE TITLE
List of .ru SLD domains are incomplete

### ISSUE THREAD

**Issue by do11** [publicsuffix/list#395]
Correct list of SLD for zone `.ru` is there: https://cctld.ru/en/docs/aktiv_8.php

Currently (as of 8 Feb 2017) your list is not including even well known .ru top level domains such as `org.ru`, `net.ru`.

What you currently reference [in `public_suffix_list.dat` for ru is](https://cctld.ru/en/domains/domens_ru/reserved/) a "list of reserved names **[not available for registration](https://cctld.ru/en/domains/domens_ru/)**." Even though there is a few domains in these SLD, this list is not complete and generally not used.

**Comment by sleevi** [comment]
@do11 That's not the correct list. See the discussion in https://github.com/publicsuffix/list/commit/7914f5961b3977f8dbc8ec90f02e26241be55c3e and related issues.

**Comment by yaleks** [comment]
This should be resolved by #377 , but ANO "MSK-IX" officials needed.

**Comment by weppos** [comment]
As @sleevi mentioned, the link you reference is the old one, and the reason why the list was updated.

**Comment by do11** [comment]
You are right in that document is obsoleted since 2009, and some previously public and free service is transferred to private entities and become pay service.

But, public `net.ru` and `org.ru` registration was valid [until at least 2016.12.05](http://tcinet.ru/documents/archive/). And there is many publicly registered subordinate domains since then. Isn't it's exact point of PSL to account for such domains?

No need to prove from current domain maintainer officials (MSK-IX) that these domains was registrable to the public before 12/2016. You can review that into on CCTLD.ru and TCNET.ru sites.

Even if new registration in these zones is stopped, it's no matter, because, there is still valid public sub-domains in them.

So, can you just add `org.ru` and `net.ru` until these domains are valid? I fear we could wait officials to contact directly, what my appear to them as random web site, forever. And they have no relations to establishing a fact that domains was publicly registrable before December 2016.

You can see that `net.ru` and `org.ru` NSes are same NSes as whole `ru`:

```
$ host -t ns net.ru.
net.ru name server d.dns.ripn.net.
net.ru name server f.dns.ripn.net.
net.ru name server e.dns.ripn.net.
net.ru name server a.dns.ripn.net.
net.ru name server b.dns.ripn.net.
$ host -t ns org.ru.
org.ru name server e.dns.ripn.net.
org.ru name server d.dns.ripn.net.
org.ru name server a.dns.ripn.net.
org.ru name server f.dns.ripn.net.
org.ru name server b.dns.ripn.net.
$ host -t ns ru.
ru name server a.dns.ripn.net.
ru name server b.dns.ripn.net.
ru name server d.dns.ripn.net.
ru name server e.dns.ripn.net.
ru name server f.dns.ripn.net.
```

**Comment by weppos** [comment]
The fact that a public suffix exists is not a proof for inclusion. And only the owner has the right to request the inclusion.

That's exactly the reason why they were removed and will be re-added only upon explicit request of the entity that owns those suffixes.

**Comment by yaleks** [comment]
@do11 see #384 for the right way to resolve this. Try to find contacts of MSK-IX.

**Comment by do11** [comment]
What decision could MSK-IX provide? I bet nobody of current `net.ru` `org.ru` sub-domains owners have relations and obligations with MSK-IX. MSK-IX is only holding these, previously public, domains since December 2017. What if MSK-IX does not want new users to be registered? There is still a lot of previous registrations.

Your registrations policy is not flexible enough to appropriate such situation, where current zone owner does not accept new registrations (and does not care to contact you), but there is many still valid old registrations and sub-domains.

If MSK-IX will decide to unregister current sub-domain (which is doubtful), the you could delete these from public suffix list, but as long of that decisions is not stated and not acted you could rely on old documents (CCTLD.ru's and TCI's). Otherwise, currently, there is more loss for these sub-domain users.
