### ISSUE TITLE
Reduce .ru PSL - extent to be determined

### ISSUE THREAD

**Issue by gerv** [publicsuffix/list#43]
Lots of Russian domains lost special status 5 years ago:
http://cctld.ru/en/news/news_detail.php?ID=634&sphrase_id=128335

http://cctld.ru/en/domains/domens_ru/reserved/ now lists only ac.ru, edu.ru, int.ru, gov.ru, mil.ru and test.ru.

However, because they didn't cancel 3rd level registrations when that made e.g. com.ru not special any more, there are still many companies in com.ru. So I don't think we can simply reduce the PSL to the list above. We will need to do an investigation and make our best guess. It may be that we leave the generic ones and remove the regional ones, but we need to look at the situation carefully.

**Comment by gerv** [comment]
Another relevant URL is http://www.cctld.ru/ru/docs/archive/detail.php?ELEMENT_ID=3446

@sleevi : any thoughts?

**Comment by sleevi** [comment]
@gerv How was .co.uk handled? My understanding is that also lost special-status.

Regarding .com.ru being special/not-special, can anyone register .com.ru? Presumably not, so long as active registrations still exist for it, so wouldn't it still be considered special implicitly, even though no new registrations are allowed?

**Comment by gerv** [comment]
> How was .co.uk handled? My understanding is that also lost special-status.

News to me! Definitely still special AFAIK. Registrations directly under .uk are now allowed, but that doesn't stop you registering a .co.uk as well, using the same mechanisms and registrars as before.

Your second para is my exact question :-) com.ru seems like a fairly obvious one to keep, but there are a lot on the .ru list, and owners of some (e.g. magnitka.ru) want them removed. How do we decide? Do we google for site:wibble.ru and see if there seem to be lots of unrelated 3LD registrations?
