### ISSUE TITLE
Add .jur.pro.br in Private Section

### ISSUE THREAD

**Issue by RegistryPRO** [publicsuffix/list#436]
+ // RegistryPRO Brasil : https://jur.pro.br/ 
+ // Submitted by Saymon Rhuano<saymonrhuano@jur.pro.br>
+  jur.pro.br

**Comment by weppos** [comment]
Duplicate of https://github.com/publicsuffix/list/issues/324

**Comment by RegistryPRO** [comment]
@weppos The problem is that it was detected in our system, but it is the bug that will be corrected so far Wednesday.

If I try today or I'm not, I'll be able to make the mistake.

**Comment by RegistryPRO** [comment]
@weppos Do you have to wait until tomorrow 16PM on Wednesday?

**Comment by RegistryPRO** [comment]
@weppos The only problem is will be resolved corrected after 16pm this Wednesday. Only then can confirmation be done!

**Comment by RegistryPRO** [comment]
@weppos Can I reopen the request for suffix inclusion using this ticket number?

**Comment by weppos** [comment]
See my comment at https://github.com/publicsuffix/list/pull/448
