### ISSUE TITLE
Remove magnitka.ru from .ru list

### ISSUE THREAD

**Issue by gerv** [publicsuffix/list#44]
Lots of Russian domains lost special status 5 years ago (see issue #43). We have been specifically asked by the owners of magnitka.ru to remove them. We should be able to do this even before completing the larger investigation.

**Comment by stakly** [comment]
How long this request will processed?

**Comment by gerv** [comment]
To git@github.com:publicsuffix/list.git
   e801df4..46e1a7e  master -> master

Gerv
