### ISSUE TITLE
Alternative DNS Providers

### ISSUE THREAD

**Issue by harleyh** [publicsuffix/list#442]
Is there a way to represent alternative DNS providers as described [here](https://en.wikipedia.org/wiki/Alternative_DNS_root)? I'm not an alt root provider but if they were to request to be added it seems like the private section might not be the best spot based on the discussion in #160.

**Comment by sleevi** [comment]
No. The Public Suffix List requires conformance with ICP-3 ( https://github.com/publicsuffix/list/wiki/Guidelines )

@gerv @weppos It seems we can/should clarify this more prominently. I suspect Guidelines is the best place, but perhaps also on publixsuffix.org. Thoughts?

**Comment by dnsguru** [comment]
Hi -

If we tweak the ICP-3 text to make it more pronounced or even more clear, I
suspect we will still receive inquiries, but I volunteer to help with the
wordsmithing.

-Jothan

**Comment by gerv** [comment]
Yes, we should make this clear in the Guidelines. Happy to accept patches for the website also.

**Comment by weppos** [comment]
I see a note has been added to the Guidelines.
