### ISSUE TITLE
Add gov.hu to .hu section

### ISSUE THREAD

**Issue by vargaviktor** [publicsuffix/list#45]
As it is published but only in flowing text form, the 
gov.hu is controlled by governmental agency.

Reference: http://www.domain.hu/domain/English/szabalyzat/specnev.html

thanks, Viktor Varga

**Comment by gerv** [comment]
It is correct that gov.hu is probably a public suffix. However, some governments have single signon across lots of domains, and adding them breaks that. So we should really get confirmation first. Do you know who runs DNS for the Hungarian government?

**Comment by vargaviktor** [comment]
Yes, they are breaking it, gov.hu without any subdomain goes to the magyarorszag.hu.

The online available documents are really old
http://dsd.sztaki.hu/mockups/itb/dadmin/domainpol.html
this dated back to 1997. :)

the dns references to the nisz.hu, but there is nothing to find there about the gov.hu domain.
i also not found any whois possibility for the gov.hu like the domain.hu (.hu domains) have.

**Comment by gerv** [comment]
In which case, without clear input from the Hungarian government, I think we should leave things as they are.
