### ISSUE TITLE
*.gu treats all subdomains of "gu" as subdomains.

### ISSUE THREAD

**Issue by rpunjabi** [publicsuffix/list#465]
The list contains the following entry for Guam:
// gu : http://gadao.gov.gu/registration.txt
*.gu

The *.gu treats all subdomains of gu as TLD as well.

Me thinks the entry needs to be changed to "gu".  That seems like whats used for most other top level domains.

I tried creating a branch to open a pull request but I don't have permission.

Thanks,
Rajesh

**Comment by gerv** [comment]
You need to fork the repo, and then you can make a change and open a pull request.

However, just changing to "gu" is not right, because there exist some 2LDs like "gov.gu" which need to be listed as well. If you were able to do the research and make the correct patch, we would be most grateful.

**Comment by weppos** [comment]
@rpunjabi please have a look at https://github.com/publicsuffix/list/wiki/Guidelines and feel free to open a PR if needed.
