### ISSUE TITLE
onion proxies

### ISSUE THREAD

**Issue by berrythesoftwarecodeprogrammar** [publicsuffix/list#47]
i really think these onion proxies should be added:
```
onion.cab
onion.city
onion.direct
onion.link
onion.lu
onion.nu
onion.sh
onion.to
tor2web.blutmagie.de
tor2web.fi
tor2web.org
torstorm.org
```
(list may be slightly out of date)

they are proxies for the tor hidden services and work like this:
`http://berrycckr666acln.onion/` -> `https://berrycckr666acln.onion.link/`
so that users can visit these websites without tor.

the problem is that if people whitelist the proxies e.g. `onion.link` in their browser/addons then they allow every tor website which they visit on that suffix to be whitelisted. this would be unsafe and unwanted. addons/browsers should be able to distinguish every proxied onion site from each other

the other problem is that most of them have no proper way of contact or they have not replied to my emails. if you look at any of these websites, their sole purpose is to proxy onion hostnames to the clear web and they should be treated as suffixes. what can be done about this?

**Comment by gerv** [comment]
We don't add privately-held domains without the consent of the domain owner. 

"the other problem is that most of them have no proper way of contact or they have not replied to my emails."

Then perhaps we shouldn't be encouraging people to use such a sketchy service by adding it to the list? :-)

**Comment by berrythesoftwarecodeprogrammar** [comment]
lol, i mean a lot of people seem to use these services and they should be aware of how they work and what using them means. they arent really sketchy, they explicitly warn users about the ramifications of using these services. e.g. https://tor2web.org/ (the main one)

would adding them to the list encourage the use of them? i dont think so but i dont know

but yeah its as i thought, domains arent added without consent so ill just keep trying to contact them or forget it
