### ISSUE TITLE
Maintaining list

### ISSUE THREAD

**Issue by nosovk** [publicsuffix/list#472]
Briefly check showed that lots of domains in a private part of list looks like abandoned

http://remotewd.com/
http://wedeploy.me/
http://cryptonomic.net
http://c66.me
http://virtueeldomein.nl/
http://xenapponazure.com/
http://browsersafetymark.io/
http://backplaneapp.io/
http://myasustor.com/
http://on-aptible.com/
http://t3l3p0rt.net/
http://beep.pl

I was guessing is somebody maintaining list removing dead entries out? Or need pull request to do that?

**Comment by sleevi** [comment]
Only the domain holder can remove domains

**Comment by weppos** [comment]
Unfortunately, besides what anticipated by @sleevi, we don't have a full removal policy yet.

The main reason is that originally the PSL was a short list, but we had an explosion of inclusions after the project was adopted by Let's Encrypt.

I am personally fine to consider removing the domains from the list if a domain is deleted. Actually, I would push it even further and enforce the domains to keep the DNS entries we ask for validation, and auto-remove them from the list if the entries are removed.

I haven't been able to formalize a proposal yet to this last topic, personally speaking the last years have been incredibly dense of tasks (and I'm also very thankful to @sleevi for his huge help in dealing with the pending private requests).

I'd love to be able to come with a practical proposal soon.

In the meanwhile, I am happy to open a proposal to remove the entries corresponding to expired/deleted domains. @nosovk can you clarify what you mean for abandoned?

**Comment by nosovk** [comment]
About abandoned I mean empty domains, like in list above. They could be expired or just not used any more. (like http://t3l3p0rt.net/)
If you ok wit NodeJS I can write script that will remove all domains if nslookup failed. It's good starting point - cause it's easy to launch it on a weekly basis.

**Comment by sleevi** [comment]
Domains not serving content on the bare domain are perfectly valid for
inclusion.

Regarding automatic removal, that's something that isn't quite ready, in as
much as it requires clearly communicating policies and ensuring we reach
out to domain holders to maintain the accuracy of the list before removal.

If there are domains whose registration is expired, we can safely remove
those.

**Comment by nosovk** [comment]
Domains not serving content on the bare domain - why they should be included in a list used by browsers for cookies policy?
At least those who removed psl verification could be removed...

**Comment by sleevi** [comment]
Because they still represent valid distinctions between subdomains. There
is no requirement that the base domains serve content - and, in fact, it's
discouraged.

And no, as the PSL policy does not currently require indefinite serving,
they cannot and should not be removed prior to contacting the domain
holder. That is the point; it would not be appropriate to change policy and
suddenly put users at risk.

**Comment by nosovk** [comment]
Why domain without content should be added into PSL if it's used for cookies security?

**Comment by sleevi** [comment]
Because subdomains need to be segmented, and subdomains can have content

**Comment by nosovk** [comment]
ok, than why not to remove entries without _psl verification? It's not hard to implement that too. And it could be automated. For example if _psl TXT not found - mail responsible person. If no answer - just remove domain from list.

**Comment by weppos** [comment]
> than why not to remove entries without _psl verification?

The _psl DNS record is a fairly recent introduction, most old entries did not require it. Personally, I'd eventually like to reach the point where we can use it as a form of validation and guarantee (like the HSTS header preload), but we're not there yet.

I'm closing this ticket for now, as it's not actionable. For further discussions I encourage to use the list psl-discuss@publicsuffix.org
