### ISSUE TITLE
support disappeared domains

### ISSUE THREAD

**Issue by hyzhak** [publicsuffix/list#473]
Hello! 

I'm working on a project that focuses on the history of Internet. And I need to match any domains that were before and exist right now. But I have found that you delete obsolete domains like `yu` (https://bugzilla.mozilla.org/show_bug.cgi?id=661509 and https://github.com/publicsuffix/list/commit/f3793d6c22dd3592bf3f42394ef76d7641dfc050). And I'm sure that you could continue it in the future.

What could you recommend? Do you have the list of domains which had been before but disappeared for some reasons?

**Comment by weppos** [comment]
I suspect that you mean TLDs, not really domains.

You may have a look at the IANA delegated database, they generally keep old entries and they flag them as "Retired"
https://www.iana.org/domains/root/db

I was not able to find the .yu there.

Another valuable project is [zonedb](https://github.com/zonedb/zonedb/), that pulls data from different sources. They tend to keep historical data, and in fact `.uy` is in their [definition table](https://github.com/zonedb/zonedb/blob/master/zones.go).

**Comment by hyzhak** [comment]
Yes, you are right. I've meant TLD. Thanks! `zonedb` really has `.yu`.
