### ISSUE TITLE
Add .бг (xn--90ae) ccTLD

### ISSUE THREAD

**Issue by sleevi** [publicsuffix/list#482]
See https://www.iana.org/domains/root/db/xn--90ae.html and https://en.wikipedia.org/wiki/.%D0%B1%D0%B3

**Comment by dnsguru** [comment]
@sleevi is there status on this one?  NIC operator reached out to me PM to inquire if there was an issue with it they could answer questions about.

**Comment by dnsguru** [comment]
Correction, submitter, not nic, was inquiring.

**Comment by sleevi** [comment]
Forgot to close it in https://github.com/publicsuffix/list/commit/0fdf7e85709a020049602b4218dabb255525cd68
