### ISSUE TITLE
Make Rule.DEFAULT optional in PublicSuffixListFactory build method

### ISSUE THREAD

**Issue by neeravats** [publicsuffix/list#486]
By adding a wildcard rule in  PublicSuffixListFactory's build method makes all suffix pass even if they are not present is Mozilla's public suffix list.

// Builds a PublicSuffixList.

private PublicSuffixList build(final InputStream list, final URL url, final Charset charset,
       
final IndexFactory indexFactory) throws IOException {

        Parser parser = new Parser();

        List<Rule> rules = parser.parse(list, charset);

        rules.add(Rule.DEFAULT);

        Index index = indexFactory.build(rules);

        return new PublicSuffixList(index, url, charset);
    }

Is there a way to avoid it? I would like to filter out public suffix that are not in Mozilla's list.

**Comment by weppos** [comment]
@neeravats this is the repo of the list itself. It looks like you are referring to a specific library. Please open the ticket in the specific library repo.
