### ISSUE TITLE
Add mynetgear.com to PSL

### ISSUE THREAD

**Issue by c-stauffer** [publicsuffix/list#488]
mynetgear.com appears to go through no-ip but is not on the list.

**Comment by sleevi** [comment]
Are you the domain owner/operator?

**Comment by c-stauffer** [comment]
I am not; Netgear routers provide one complimentary subdomain.

See: https://kb.netgear.com/23860/How-to-Setup-a-NETGEAR-Dynamic-DNS-account

According to that the domain is via a partnership between Netgear and no-ip.

**Comment by sleevi** [comment]
I see. Netgear or No-IP will need to request inclusion, then.
