### ISSUE TITLE
Add New Domain GRU.BR on public_suffix_list

### ISSUE THREAD

**Issue by kutpenco** [publicsuffix/list#502]
Hello, Please add the Domain GRU.BR Released on 2018-08-07 12:00 (GMT -03:00) by NIC.BR on Brasil.

Regards, Penco Lucas.

**Comment by kutpenco** [comment]
+// add domain by NIC.BR on 2018-08-07 12:00 GMT -3:00
+gru.br
+// end edit, credits Lucas Penco. tks

**Comment by sleevi** [comment]
Please see https://github.com/publicsuffix/list/wiki/Guidelines

**Comment by weppos** [comment]
Duplicate of #504
