### ISSUE TITLE
Adding .bit ?

### ISSUE THREAD

**Issue by Heat-Miser** [publicsuffix/list#505]
Hello,

do you think it's conceivable to add .bit TLD il your list ?

I know it's not a classic TLD, but it's used by malware to host c2, and this list is used in the "tldextract" python module used to analyse malware.

https://en.wikipedia.org/wiki/.bit

Thanks for your feedback !

**Comment by sleevi** [comment]
Unfortunately, without `.bit` being reserved by IANA/ICANN, it would not be appropriate to add to the list. This was equally true of `.onion` in the past, until https://tools.ietf.org/html/rfc7686
