### ISSUE TITLE
Redelegation .presse.ml

### ISSUE THREAD

**Issue by RegistryPRO** [publicsuffix/list#513]
The ccSLD .presse.ml has been redeleged to the NIC Presse du Mali

**Comment by sleevi** [comment]
Can you explain why this is an issue for the PSL?

**Comment by RegistryPRO** [comment]
@sleevi It should include the administrative contact of the new .presse.ml operator.

Or can the list of .ml suffixes continue like this?

Thanks

**Comment by RegistryPRO** [comment]
@sleevi Registration of domains under the ccSLDs .com.ml, .net.ml and .org.ml were closed. The .gouv.ml and .gov.ml domains are managed by AGETIC, the .ml domains are operated by Freenom, and the .presse.ml domain registration is done by the NIC Presse du Mali.

Officially there are 3 registry's in Mali

**Comment by sleevi** [comment]
The PSL does not actively maintain contact information. It sounds like you're mentioning the information is out of date, but that's not an issue.

**Comment by RegistryPRO** [comment]
@sleevi Thank you
