### ISSUE TITLE
Add .nitr.pro - ICANN Root (IANA) (Re-Include)

### ISSUE THREAD

**Issue by RegistryPRO** [publicsuffix/list#517]
+// .NITR.PRO Registry: http://www.registry.nitr.pro
+// Submitted by: Saymon Rhuano
+nitr.pro

https://github.com/mhuggins/dominatrix/blob/master/lib/extensions.txt

**Comment by weppos** [comment]
@RegistryPRO please check out the Guidelines and provide a PR if applicable.
https://github.com/publicsuffix/list/wiki/Guidelines
