### ISSUE TITLE
Please remove “tp” from public suffix list

### ISSUE THREAD

**Issue by sushmahn** [publicsuffix/list#53]
Please remove “tp” from public suffix list. Earlier this year IANA decided to remove “tp” top level domain after a long deliberation process. 
https://www.iana.org/reports/2015/tp-report-20150126.html  
https://features.icann.org/removal-tp-top-level-domain-representing-portuguese-timor

**Comment by weppos** [comment]
@gerv @sleevi do you see any implications in removing a suffix that represents a TLD that was previously included in the list?

There shouldn't be any (as we have removed other suffixes in the past), but since this is a TLD I'm asking before going ahead.

**Comment by weppos** [comment]
Moreover, apparently @sleevi originally submitted this TLD.

**Comment by sleevi** [comment]
@weppos There's no problems; it was reserved from the IANA list and is shut-down. I didn't bother with this because it was closed by the reporter, but we should do a secondary pass on the IANA RZD to see if IANA has decomissioned any other domains, but considering .tp is no longer resolvable, removing is the Right Thing To Do.

**Comment by weppos** [comment]
> but we should do a secondary pass on the IANA RZD to see if IANA has decomissioned any other domains

As far as I remember, this year IANA removed:
- AN https://github.com/whois/ianawhois/commit/d20b16c4b4ab15dedfe2a31be9d354e44862c466
- TP https://github.com/whois/ianawhois/commit/c42c6e80af7bcdd09282b2177abf77c436daaca0

After further investigation, it looks like `.AN` was already removed in 109f3723f9e86c615054e12e0aace866205fb380 by @gerv  (see https://github.com/publicsuffix/list/pull/50), hence I believe it's fine to go ahead and remove also `.TP`.

**Comment by gerv** [comment]
Yes, do remove it.

Gerv

**Comment by weppos** [comment]
Removed.
