### ISSUE TITLE
com.de inclusion?

### ISSUE THREAD

**Issue by quirins** [publicsuffix/list#538]
Hi,

I recently stumbled across the com.de domain, which seems to be selling subdomains:
http://com.de/faqs/policy/

I am not familiar with all the PSL details, but thought this candidate would apply?

Kind regards
Quirin

**Comment by weppos** [comment]
Hello Quirin,

Yes, it is a candidate, but per our guidelines only the owner can request the inclusion.
https://github.com/publicsuffix/list/wiki/Guidelines
