### ISSUE TITLE
Please add .post to public suffix list

### ISSUE THREAD

**Issue by AlexHowerton** [publicsuffix/list#547]
Please add .post to the public suffix list, as well as the country codes at the SLD level, as listed below:

ae.post
af.post
ag.post
ai.post
al.post
am.post
ao.post
aq.post
ar.post
as.post
at.post
au.post
aw.post
ax.post
az.post
ba.post
bb.post
bd.post
be.post
bf.post
bg.post
bh.post
bi.post
bj.post
bm.post
bn.post
bo.post
bq.post
br.post
bs.post
bt.post
bw.post
by.post
bz.post
ca.post
cc.post
cd.post
cf.post
cg.post
ch.post
ci.post
ck.post
cl.post
com.post
cm.post
cn.post
co.post
cr.post
cu.post
cv.post
cw.post
cx.post
cy.post
cz.post
de.post
dj.post
dk.post
dm.post
do.post
dz.post
ec.post
edu.post
ee.post
eg.post
er.post
es.post
et.post
fi.post
fj.post
fk.post
fo.post
fr.post
ga.post
gb.post
gd.post
ge.post
gf.post
gh.post
gi.post
gl.post
gm.post
gn.post
gp.post
gq.post
gr.post
gt.post
gu.post
gw.post
gy.post
hk.post
hn.post
hr.post
ht.post
hu.post
id.post
ie.post
il.post
in.post
io.post
iq.post
ir.post
is.post
it.post
je.post
jm.post
jo.post
jp.post
ke.post
kg.post
kh.post
ki.post
km.post
kn.post
kp.post
kr.post
kw.post
ky.post
kz.post
la.post
lb.post
lc.post
li.post
lk.post
lr.post
ls.post
lt.post
lu.post
lv.post
ly.post
ma.post
mc.post
md.post
me.post
mg.post
mk.post
ml.post
mm.post
mn.post
mo.post
mq.post
mr.post
ms.post
mt.post
mu.post
mv.post
mw.post
mx.post
my.post
mz.post
na.post
nc.post
ne.post
nf.post
ng.post
ni.post
nl.post
no.post
np.post
nr.post
nu.post
nz.post
om.post
org.post
pa.post
pe.post
pf.post
pg.post
ph.post
pk.post
pl.post
pm.post
pn.post
pr.post
ps.post
pt.post
py.post
qa.post
qm.post
qn.post
re.post
ro.post
rs.post
ru.post
rw.post
sa.post
sb.post
sc.post
sd.post
se.post
sg.post
sh.post
si.post
sk.post
sl.post
sm.post
sn.post
so.post
sr.post
ss.post
st.post
sv.post
sx.post
sy.post
sz.post
tc.post
td.post
tg.post
th.post
tj.post
tk.post
tl.post
tm.post
tn.post
to.post
tr.post
tt.post
tv.post
tw.post
tz.post
ua.post
ug.post
us.post
uy.post
uz.post
va.post
vc.post
ve.post
vg.post
vn.post
vu.post
wf.post
ws.post
xz.post
ye.post
yt.post
za.post
zm.post
zw.post

**Comment by sleevi** [comment]
Please see the [Guidelines](https://github.com/publicsuffix/list/wiki/Guidelines) for how to submit a request, and what the necessary levels of proof of ownership include.

**Comment by weppos** [comment]
@AlexHowerton  please check out the Guidelines and provide a PR if applicable.
https://github.com/publicsuffix/list/wiki/Guidelines
