### ISSUE TITLE
request: change privately managed suffixes policy 

### ISSUE THREAD

**Issue by kaefert** [publicsuffix/list#56]
Although I could not find an explicit mission statement of your project, most of the information you publish sounds like it would be something like having the most accurate list of public suffixes possible, which in turn would help browsers (and other internet related software / services) deliver a better and more secure web experience to users.

Under that light, I would like an explanation for the policy that privately managed suffixes can only be submitted by authorized representatives of the domain registrant.

The only explanation I found for myself is that you have an overwriting goal of protecting those registrants' property sacrificing the security of internet users in the process.

If this is not the case, I would ask you to replace that policy with simply some kind of proof of that the added domains are in fact public suffixes (like for example a link to a registration page that shows every internet user can register a subdomain of them).

**Comment by weppos** [comment]
There are implications of adding a new item to the list, implications that may affect how browser and clients in general will deal with cookies and SSL certificates for specific hostnames. Because of this implications, it's important that a request to add an items to the list is not ambiguous and it comes from the owner (manager) of the suffix, as the owner will take responsibility for such change.

@gerv can probably provide a more exhaustive and official response as he represents Mozilla.

**Comment by kaefert** [comment]
@weppos thank you for your reply. Well yes of course it should affect how browsers (and other software / services) manage cookies and stuff. My argument is that for the internet user, it would be beneficial if his browser knew what domains are public suffixes, even if the commercial owner of the public suffix does not care or doesn't want the browsers to know.

Otherwise it would (is) possible for privately operated public suffixes (like for example no-ip) that are not on your list to set supercookies or impersonate one of their clients with a wildcard certificate.

(I don't suggest that anyone is doing that, which of course would be considered a crime in most justice systems, but as in so many other areas, it's better to make sure using technology instead of relying on people to obey the law)

**Comment by gerv** [comment]
> Otherwise it would (is) possible for privately operated public suffixes (like for example no-ip) that are > not on your list to set supercookies or impersonate one of their clients with a wildcard certificate.

The latter is already possible - CAs are perfectly entitled to issue *.publicsuffix.tld (where publicsuffix.tld is in the private section) to the owners of publicsuffix.tld. If you are taking a subdomain from someone, you need to trust them - the PSL doesn't change that. What is changes is that you don't have to trust all their other customers.

However, some places which seem to be doing open registration still offer services such as federated login across their customers which require *.publicsuffix.tld cookies. We can't analyse their operations and future plans. Therefore it remains true that we require domain owners to request their own addition to the list. If a company you are considering doing business with is offering subdomains and isn't on the list, consider not doing business with them :-)

**Comment by kaefert** [comment]
okey, so federated login is a good argument. but for business models like no-ip this is clearly a non issue, this would be more like for services like *.wordpress.com that don't give away subdomains to point to ip's under their clients control, but rather give their customers space on their servers to use a specific application their.

But I guess it's quite difficult to investigate the business model of each and every privately operated public suffix - though for the few very big ones at least like dyndns (which is already on the list anyway) or no-ip it would seem like a no-brainer to me...

**Comment by gerv** [comment]
> But I guess it's quite difficult to investigate the business model of each and every privately operated > public suffix

Not just difficult but impossible, as we can't see their future product plans.

**Comment by kaefert** [comment]
well wouldn't it be more important what they seem to promise their customers, since that is what internet users would expect their browsers to enforce... at least that's what I want from my browser:

To make sure things are as they seem.
