### ISSUE TITLE
Private Suffix "Domain Rot"

### ISSUE THREAD

**Issue by c22** [publicsuffix/list#566]
I suppose similar to #296, really interested in more of a discussion.

Seems obvious to me that private suffixes can be easily submitted by their owners, but I'd say over time this leaves the list susceptible to "domain rot", where the owner has potentially forgotten about their submission or is no longer capable of maintaining it. What happens then? Is there any process to verify that domains in the list are indeed still being maintained by, and are in custody of, their original owners?

I'm also genuinely interested in what other options were explored when it came to ensuring cookies were set correctly. The list seems like it was a means to an end at the time, but couldn't this problem be solved another way nowadays? Why would browsers not "default deny" and use something akin to SPF but for cookies?

Apologies if this would be better suited to the mailing list.

**Comment by weppos** [comment]
@c22 you are raising interesting questions, and I definitely agree with some of these concerns.

Speaking of the listing of private names, we don't have (yet) a fully determined policy. The listing of private domains was really limited before Let's Encrypt started to adopt the list for rate limiting. This action both increased the listing for Let's Encrypt purposes and the awareness of the list itself in the ecosystem. As a result, we've registered a big increase of listing requests for private domains.

As a result, we started to evaluate some changes to the listing requirements. The first one was to introduce a more objective validation, based on DNS. We are currently requesting the owner to add a specific DNS record to validate the entries. We are also requesting to leave the DNS record in place, as we reserve the right to remove the entry from the PSL should the record be removed.

This is a first step towards listing/delisting. I've been willing to come with a more automated procedure for listing/delisting and I have a few ideas in mind, just not a lot of time to build up a practical proposal yet.

Of course, in case someone should get a domain that was previously listed, the new owner has all the rights to request the removal. At the time being, we don't actively purge the list although I've personally removed a few entries in the past connected to domains that expired.

As for the alternatives, I can't speak for browser vendors or client developers.

There are definitely pros and cons of using DNS entries, but as @sleevi pointed out several times there is also a cost of DNS lookups that makes convenient to have a compiled list.

I've been thinking about coming with a proposal of an enhancement of the list that combines DNS with an auto-discovery mechanism and an automated tool to periodically compile a list. That would bring in the best of both worlds.

However, a final work must be spent about the registries. While we see a lot of activity and interest to contribute to the PSL from private domain owners (some of the genuinely, others mostly for LE) there is very little support from the registries. Ironically, registry-managed suffixes (what we use to list in the ICANN section) are also the primary reason the list exist.

We always had to balance between these two worlds, and it's not easy to introduce automation in that specific world.
