### ISSUE TITLE
Add .anani.com.br

### ISSUE THREAD

**Issue by RegistryPRO** [publicsuffix/list#576]
Add .anani.com.br in Private section.

THanks

**Comment by weppos** [comment]
@RegistryPRO do you manage this suffix?

**Comment by RegistryPRO** [comment]
@eppos Yes.

**Comment by RegistryPRO** [comment]
@weppos Yes.

**Comment by weppos** [comment]
Please open a PR and add the necessary records for validation.
https://github.com/publicsuffix/list/wiki/Guidelines

**Comment by RegistryPRO** [comment]
@weppos Instead of including .jur.pro.br in the PUblicSuffix list, can we use the .jjur.pro.br TXT file ID for .anani.com.br?

**Comment by weppos** [comment]
I'm not sure what you mean.

**Comment by RegistryPRO** [comment]
@weppos I can use the TXT record that would be used to include .jur.pro.br ($ Dig TXT _psl.jur.pro.br https://github.com/publicsuffix/list/pull/57747) to include .anani. com.br?

I will not include .jur.pro.br. Can I use the TXT record and the ID to include .anani.com.br?

**Comment by weppos** [comment]
> @weppos I can use the TXT record that would be used to include .jur.pro.br ($ Dig TXT _psl.jur.pro.br https://github.com/publicsuffix/list/pull/57747) to include .anani. com.br?

No. The record must correspond to the request.

> I will not include .jur.pro.br

Should #324 #448 be closed then?
