### ISSUE TITLE
Add zone.id

### ISSUE THREAD

**Issue by hdrxs312** [publicsuffix/list#577]
I want to add Zone.id as Public Suffix.
Anyone can help me? @weppos ?

**Comment by hdrxs312** [comment]
This is my PR: https://github.com/publicsuffix/list/pull/575

**Comment by weppos** [comment]
You already have an open PR. There is no need to open another ticket. Please be patient, your PR will be reviewed when possible.

**Comment by hdrxs312** [comment]
Thank you

**Comment by hdrxs312** [comment]
How long do I have to wait @weppos

**Comment by sleevi** [comment]
The list is volunteer driven and may take weeks or even months for approval.

**Comment by hdrxs312** [comment]
@sleevi is there any way to get approved earlier? may be something should i do..

**Comment by sleevi** [comment]
Ensure you follow the Guidelines and it will be reviewed in the order it
was received.

**Comment by hdrxs312** [comment]
ok thank you @sleevi.
i have followed the Guideline. but if anything wrong, please inform me soon..

**Comment by hdrxs312** [comment]
as written in Guideline, i should do follow up.
now, can you let me know my PR progress?
i start worry about my website.
with 1400+ user and 4000+ registered subdomain, it's very potentially cookie stealing.
hope you understand me.. :-( @sleevi @weppos
