### ISSUE TITLE
Redelegated .presse.ml

### ISSUE THREAD

**Issue by NICml** [publicsuffix/list#590]
Redelegated .presse.ml

New operator:

NIC Presse du Mali
Saymon Rhuano Dias de Andrade
saymon@domaines.presse.ml

**Comment by weppos** [comment]
Hello @NICml,

Please have a look at https://github.com/publicsuffix/list/wiki/Guidelines and provide a PR if you are the owner of the domain.

**Comment by NICml** [comment]
@weppos I am the new operator of presse.ml, but I do not know how to create a PR. But can I authenticate by TXT and email?

**Comment by NICml** [comment]
@sleevi ICANN o The procederem? O presse.ml.ml is ICANN Domain Root

**Comment by sleevi** [comment]
I have no idea what you are saying.

**Comment by NICml** [comment]
@sleevi o The ICANN Domain Root, que o other  procede?

**Comment by NICml** [comment]
@sleevi the suffix does not have private records is a public suffix

**Comment by sleevi** [comment]
Presse.ml is already listed so there is no need for further changes. If you are requesting that it be removed, please read GitHub Help on how to submit a PR to remove it, and follow the Guidelines to authenticate.

**Comment by NICml** [comment]
is there another procedure to re delegate public ICANN root suffixes

**Comment by sleevi** [comment]
No, because if no changes are necessary, no changes are necessary.

**Comment by NICml** [comment]
@sleevi I do not want to remove the suffix I would like to include the contact data in Public suffix

**Comment by sleevi** [comment]
Yes, I understand, and that’s not necessary nor desired.

**Comment by NICml** [comment]
@sleevi  I would like to include the new suffix operator name and the contact email

**Comment by sleevi** [comment]
That is not necessary.

**Comment by NICml** [comment]
@sleevi Can I only exclude you from the ICANN suffix list?

**Comment by sleevi** [comment]
I have no idea what you’re asking. Are you asking to be moved to a private suffix? Why? It would be easier if you opened a pull request that tried to explain what you’re trying to do, as it all sounds unnecessary.

**Comment by sleevi** [comment]
Then there is nothing to change.

**Comment by NICml** [comment]
Ok. Vou thank you
