### ISSUE TITLE
Add .blogspot.click

### ISSUE THREAD

**Issue by NICml** [publicsuffix/list#592]
Add blogspot.click

**Comment by weppos** [comment]
Please have a look at https://github.com/publicsuffix/list/wiki/Guidelines and provide a PR if you are the owner of the domain.

**Comment by NICml** [comment]
@weppos I'm already trying to make a PR and I did not get it. Is very dificult.

**Comment by weppos** [comment]
https://help.github.com/articles/creating-a-pull-request/
