### ISSUE TITLE
.بارت (xn--mgbbh1a) suffixes 

### ISSUE THREAD

**Issue by h-j-13** [publicsuffix/list#595]
https://www.iana.org/domains/root/db/xn--mgbbh1a.html  
it  looks like a India TLD still in use
> Registry Information
IANA Reports
Delegation of eight top-level domains representing India in various languages to the National Internet Exchange of India (2017-06-09)
Record last updated 2017-06-30. Registration date 2016-08-15.

**Comment by weppos** [comment]
Closed by #639
