### ISSUE TITLE
Wrong domainname in .ua geographic names section

### ISSUE THREAD

**Issue by mixmaxdp** [publicsuffix/list#601]
Current version of publicsuffix contains section
```
// ua geographic names
// https://hostmaster.ua/2ld/
```

which in turn has strange domain
`dominic.ua`
included - this one is not related to any of geographic regions of Ukraine and most likely was an error/omission.

It is not listed on current version of https://hostmaster.ua/2ld/ either.
I'd suggest removal of this entry. 

Additionally would be nice to re-sync all other general/geo/etc. names based on the info from https://hostmaster.ua/2ld/

_I'd send a pr, but I'm not affiliated with hostmaster organization._

**Comment by simon-friedberger** [comment]
This has already been removed.
