### ISSUE TITLE
Simplify by removing single label names

### ISSUE THREAD

**Issue by pzb** [publicsuffix/list#602]
According to [the Formal Algorithm](https://publicsuffix.org/list/) for the PSL:

> If no rules match, the prevailing rule is "*"

Right now there are many single label entries in the PSL.  This has led to implementations failing to implement the default rule of `*`.  It has also led to incorrect use of the PSL to attempt to determine if a TLD is a public TLD.

I suggest that all single label entries be moved to comments to both simplify the list and help avoid developers using the data in unsupported ways.

**Comment by sleevi** [comment]
Can you explain why you believe it is an improper/unsupported method?

This use Case was explicitly considered and supported.

**Comment by pzb** [comment]
From the front page:

>Some people use the PSL to determine what is a valid domain name and what isn't. This is dangerous, particularly in these days where new gTLDs are arriving at a rapid pace, if your software does not regularly receive PSL updates, because it will erroneously think new gTLDs are not valid. The DNS is the proper source for this information. If you must use it for this purpose, please do not bake static copies of the PSL into your software with no update mechanism.

This strong suggests that the PSL team does not recommend using it to determine valid public TLDs.

**Comment by sleevi** [comment]
Not without an update mechanism. We support it with an update mechanism - the discussion goes back to the Bugzilla days and we agreed to be a superset if the root zone database

**Comment by sleevi** [comment]
I’m not sure I understand the last point - every PSL implementation I’ve
looked at has the * fallback (although some allow it to be disabled, for
the reasons you mentioned)
