### ISSUE TITLE
Please remove qld.gov.au from public suffix list 

### ISSUE THREAD

**Issue by DCCSDSfwilson** [publicsuffix/list#61]
Please remove qld.gov.au. This bug fix has been actioned for other states within Australia.

// act.gov.au  Bug 984824 - Removed at request of Greg Tankard
// nsw.gov.au  Bug 547985 - Removed at request of Shae.Donelan@services.nsw.gov.au
// nt.gov.au  Bug 940478 - Removed at request of Greg Connors Greg.Connors@nt.gov.au

**Comment by weppos** [comment]
@DCCSDSfwilson can you please confirm you are authorized to make this request? Do you manage qld.gov.au? Can you provide a reason for the removal?
