### ISSUE TITLE
Please remove se.com from Public Suffix List

### ISSUE THREAD

**Issue by IsafromSE** [publicsuffix/list#612]
The Domain se.com , listed as a public Suffix under Centralnic ownership, is now owned by the Company Schneider Electric.
As a result, we would like to remove this Domain from the public Suffix list.
You can validate our request by sending an email to the email address placed in the whois for se.com.
or sending us a TXT to place on our DNS for authentication.  
Could you please let me know how long the removal will take?
Thank you in advance,
Regards

**Comment by sleevi** [comment]
Please see https://github.com/publicsuffix/list/wiki/Guidelines for how to request removal.

Setting aside the time it would take to review and integrate, it can take between 6 months to a year for various PSL consumers to update.

**Comment by IsafromSE** [comment]
Hello, Validation record added in reference to #613. Could you please validate and proceed to removal? Thanks !

**Comment by weppos** [comment]
Please only follow up when the record is correctly setup.

**Comment by weppos** [comment]
Closed by #614
