### ISSUE TITLE
Please stop adding unofficial extensions

### ISSUE THREAD

**Issue by sql-sith** [publicsuffix/list#623]
Unless an extension is an officially-sponsored SLD (like CO.UK), it should not appear on this list. Otherwise, what would prevent every domain owner from requesting that you put every domain on the list? 

This might not seem like a big deal, but it does have implications. If a domain name is not a registry-sponsored (sellable) domain, then it is just a domain name - not an official "suffix." 

So what happens is that people buy a second- or third-level domain name and then act like a registrar, or even a registry, by selling people sub-domains. This is certainly acceptable if they then help their customers get set up on a DNS/WHOIS/hosting service that has the resources to perform these services.

However, since these people do not have the infrastructure available to actually be a registrar or registry (and run things like their own DNS and WHOIS) they go to places like GoDaddy (where I work) and try to put these domains into our offsite DNS system. This is a system that we offer to people where we host DNS for their domains they have registered through another registrar. 

If people who own names like ybo.party or dirkstation.org or appchizi.com approach us to put one of those names into our offsite DNS system, some of our more junior support people might look at your list, see the name listed as a "suffix," and take that as authoritative.  In other words, they will assume that a name on this list is a registry-sponsored (sellable) domain. 

However, none of these should be treated as a proper "suffix" (ie: registry-sponsored domain) - they are just domain names, and that is all. Putting these names on this list legitimizes domain owners asking Go Daddy and other registrars to add it to our lists by giving them credibility they should not have. It's basically a con, and they are using this list to perpetrate the con by passing off their domains as TLDs or SLDs when they are really just registered domain names for which they are selling subdomains. 

Again, it's fine if they want to sell sub-domains of their names, but they should then be responsible for providing the infrastructure associated with those names, or their customers should be encouraged to set up DNS and hosting with any of the many organizations that can provide this service using their own resources or using legitimate reseller agreements.

**Comment by weppos** [comment]
Hello @sql-sith, thanks for you feedback.
The list is split between ICANN (IANA) TLDs and private TLDs on purpose. If you don't care about private suffixes, you can parse that section out.

**Comment by sql-sith** [comment]
Thanks, @weppos. I actually hadn't noticed that. Just to clarify, what you are calling ICANN (IANA) TLDs is the list of all of the IANA-recognized TLD groups (infrastructure, generic, restricted generic, sponsored, country-code, and test) along with the lower-level names that have been sponsored by each of those registries - so that the kinds of names I am concerned about are not on the ICANN part of the list, and all the names we need to use are on the ICANN part of the list. Is this correct?

**Comment by sleevi** [comment]
@sql-sith Does the discussion of "Divisions" at https://publicsuffix.org/list/ answer this question? I believe the answer is "Yes", based on your question, but I'm hoping that the documentation will provide a clear and unambiguous answer - and, if not, that we can improve it :)

**Comment by sql-sith** [comment]
I think the answer is yes, also. I do think some things on that page may be able to be reworded - for example, saying that "the registered or registrable domain is the public suffix plus one additional label" is only true if all of the owners of private rules have a registry or at least a registration process. I may circle back later to see if I can make any suggestions that you could then either implement or ignore, depending on whether you found them helpful.

Also, I have a question about the example. Is the reason that "cookies may not be set for bar.jp" because the `*.jp` rule requires the `*` to be surrounded by dots? In other words, does `foo.bar.jp match` `*.jp` because the `*` matches `.bar.` but `bar.jp` does not match because the `bar` label lacks a required leading dot? The *Definitions* and *Algorithm* sections lead me to believe that `bar.jp` should match the rule `*.jp` and allow cookies, since dots are ignored after the labels are determined. This would mean that the domain produces the labels `bar` and `jp` while the rule produces `*` and `jp`, which would match (allowing cookies.

**Comment by sleevi** [comment]
On Wed, Mar 21, 2018 at 10:34 PM Chris Leonard <notifications@github.com>
wrote:

> I think the answer is yes, also. I do think some things on that page may
> be able to be reworded - for example, saying that "the registered or
> registrable domain is the public suffix plus one additional label" is only
> true if all of the owners of private rules have a registry or at least a
> registration process. I may circle back later to see if I can make any
> suggestions that you could then either implement or ignore, depending on
> whether you found them helpful.
>

I’m not quite sure that’s correct, but we may be using registerable
differently, with you using a more constrained interpretation. You can
certainly register domains at, say, AppEngine - so it applies.

Also, I have a question about the example. Is the reason that "cookies may
> not be set for bar.jp" because the *.jp rule requires the * to be
> surrounded by dots? In other words, does foo.bar.jp match *.jp because
> the * matches .bar. but bar.jp does not match because the bar label lacks
> a required leading dot? The *Definitions* and *Algorithm* sections lead
> me to believe that bar.jp should match the rule *.jp and allow cookies,
> since dots are ignored after the labels are determined. This would mean
> that the domain produces the labels bar and jp while the rule produces *
> and jp, which would match (allowing cookies.
>

So, as best I can understand the question, no. I don’t know why surrounding
dots are seen as relevant - the algorithm explains it in terms of labels,
which would not have introduced such a notion.

Perhaps this is related to
https://github.com/publicsuffix/list/issues/145 ?

>
