### ISSUE TITLE
I want to help the project

### ISSUE THREAD

**Issue by frju365** [publicsuffix/list#627]
Hello,

As I told to @weppos, I see that you have many problem in merging PR and reviewing PR (lack of time). Me, I've time, I'm a student. So I ask you  : Can I help ? and can this help be productive ?

I sent a mail to @weppos with a list of PR which I've reviewed. But apparently, and I understand that, you didn't have time to merge them. I'm really active in Free software community and understand well web security. I'm contributor in many Organizations like Tutanota, Yunohost or I've Something to Hide website (+ many other for translations and testings). 

You told a person in a PR that you hadn't time to review the PR and merge a PR... so why don't you add collaborator ? A list which is an example/base for security taken by many big Organizations on the Internet shouldn't be owned by only 2 persons. I think this can cause many problem, because in a way, you don't only care of this project but many. Moreover, the big problem os that, it's the only base for security and prefix management. Why is it a big problem ? Because most of the persons here can't open PR on another list... just because there is no other list. So, one more time, is it possible to help you in any way ?

Thanks in advance for your answer, and thanks for the work you made,
frju365

PS: I think the problem for let's encrypt is that a link to the list is written on the main website... that's why many ppl go here to ask for Let's Encrypt rate limit. I will send a message to LE orga (PM on the forum) to remove the link. The second reason is : the form link on their website is not really maintained, at least no in time... and when the problem is about security of certificate, it's a big problem/issue.

**Comment by weppos** [comment]
> But apparently, and I understand that, you didn't have time to merge them.

I don't recall I've ever said that.

I got your email, and I was going to reply. I appreciate your help, but I definitely don't expect someone supposed to help to open tickets like this one, as this is exactly the opposite of helping.

Due to the importance of the project, I don't think it would be wise to add commit access to someone after less than a week, and a few PRs reviewed. Sorry to be honest.

**Comment by weppos** [comment]
I will follow up to your email asap. I took a few days off, it looks like these days it's even hard to accept the fact someone can take time to disconnect from internet.

**Comment by frju365** [comment]
Thanks and sorry for this ticket :-) I was not sure that you got my email. 
By collaborators, I didn't mean me ;-) I know that you and everybody won't give merge access to a contributor just after one week. But plenty of persons here would be proud to contribute to a so important project. And take time to disconnect from internet, nobody expect from you to be here every days at every minutes... Nobody can expect something from a person doesn't get money to maintain a project (and because the user who asks didn't give money for the service). I didn't mean that. I just think we can find a way to be productive, I'm sure ;-)

For example, I can do review for you and send mail each time I checked 5 or 10 PR which are following the Guidelines and can be merged. Is it ok like that ? After that, you could do a second quick review and merge if it's good.
