### ISSUE TITLE
PSL is missing several IANA-recognized TLDs (.招聘 / .charity / .inc / .llc / .sport)

### ISSUE THREAD

**Issue by tweedge** [publicsuffix/list#639]
I notice the PSL does not include .llc or .sport, despite IANA seeming to recognize them (per [tlds-alpha-by-domain](https://data.iana.org/TLD/tlds-alpha-by-domain.txt)). I was wondering if there was any particular reason for that? If not, I can submit a pull request to the PSL with all IANA-recognized TLDs.

**Comment by weppos** [comment]
> The .sport TLD has been added to the IANA root three months ago. Right now, Letsencrypt requests fail for .sport domains and Letsencrypt said that they need the PSL to be updated first. 

@wstaub can you please provide a reference to this assertion.

> This is an example where the PSL does more harm than good if it does not automatically include all the TLDs of the IANA DNS root.

This statement denotes a very poor understanding of the PSL purpose. Before making such harsh statements, you should probably take the time to familiarize with the project and do an effort to understand what it is designed for.

**Comment by tweedge** [comment]
@weppos my understanding mirrors that of @wstaub, then. As far as I can discern from PSL documentation, it provides suffixes for browsers to determine how cookies should be set, efficiently grouping sites together, and more domain-related tasks mostly focused on web browsing and experience. Given that, is there any particular reason why the PSL should therefore not include all IANA-recognized TLDs?

My rationale being: Should the PSL not make an effort to include all IANA-recognized TLDs, the PSL would be ineffective as a general-purpose DNS parser/grouper. Which I fully recognize is not among the highest priorities for PSL maintenance, but it's a compelling use case for large projects that require site grouping and one that's definitely seen in the wild (my project alone parses ~700,000,000 domains/day). Should the PSL include all IANA-recognized TLDs, I can't honestly identify any negatives aside from writing one more test case, which I would be happy to attend to personally.

I'm all ears, and would love to hear any intricacies or considerations that I've overlooked. This is an excellent project and has done wonders for my work so far, thank you for all your efforts.

**Comment by dnsguru** [comment]
@weppos @sleevi - we were tracking the contracting emails from ICANN for this and then adding them - I know with @gerv stepping back it is kind of on us... 

I swept through and the following need adding to PSL:

// charity : 2018-04-11 Corn Lake, LLC
charity

// inc : 2018-03-10 GTLD Limited
inc

// llc : 2017-12-14 Afilias plc
llc

// sport : 2017-11-16 Global Association of International Sports Federations (GAISF)
sport

**Comment by tweedge** [comment]
@dnsguru I ran a quick sanity check against [tlds-alpha-by-domain](https://data.iana.org/TLD/tlds-alpha-by-domain.txt) as well and found an additional two entries - [xn--mgbbh1a](https://www.iana.org/domains/root/db/xn--mgbbh1a.html) and [xn--otu796d](https://www.icann.org/resources/agreement/xn--otu796d-2017-08-06-en).

**Comment by dnsguru** [comment]
@tweedge Thanks for that- 

// xn--otu796d  : 2017-08-06 Dot Trademark TLD Holding Company Limted
招聘

We will need to run the patch for xn--mgbbh1a past NIXI as a separate matter as it is an IDN ccTLD for India and has to follow a different path.

**Comment by dnsguru** [comment]
@weppos or @sleevi please make patch file that includes these and expedite the merge on it - this looks like our first larger batch addition of ICANN/IANA TLDs with the new process as we take over from Gerv.   

@tweedge  caught another we'd missed but it is a ccTLD in IDN for India and we'll need to verify what to do with the good folks at NIXI on that unless you want to also add it while in the file.

// xn--mgbbh1a ("Bharat", Kashmiri) : IN
// India
بارت

**Comment by sleevi** [comment]
Ah, I see what happened. Our script https://github.com/publicsuffix/list/blob/master/tools/patchnewgtlds broke when `*.zw` was changed to specific entries, and we didn't notice until now. Filed Issue 643 for that, which I have a fix for, and will unblock this pickup.

As for new ccTLDs (the India case), those have been added by hand, as ICANN does not publish them in https://newgtlds.icann.org/newgtlds.csv file (because they're not gTLDs). If someone wants to update https://github.com/publicsuffix/list/blob/master/tools/newgtlds to a different datasource, or also patch in the ccTLD lists, it's worth filing an issue and submitting PRs for. Python (2 or 3) are preferable
