### ISSUE TITLE
.kw TLD changes

### ISSUE THREAD

**Issue by hasbean** [publicsuffix/list#641]
Hello,

I'm trying to get a LetsEncrypt ssl certificate for http://ix.kw/ and I keep getting this error back:

`Error creating new authz :: Name is an ICANN TLD`

.kw is currently listed as *.kw, which is contrary to what's listed in the wiki
https://en.wikipedia.org/wiki/.kw

I believe it should be changed to:

```
kw
ind.kw
net.kw
edu.kw
gov.kw
com.kw
org.kw
```

**Comment by sleevi** [comment]
Wikipedia is not an authoritative source.

In reading through https://citra.gov.kw/sites/en/LegalReferences/Registration-Regulation-EN_vOlVPNs.pdf , it's not clear that registration at the .kw level is allowed (At least based on my parsing of Section 2, Item 19). That is, it's unclear that they allow general registration in `.kw` versus are simply the authortative registry for `.kw`

If you can find a better reference, we'd be happy to review, @hasbean

**Comment by Bashar** [comment]
Dear @sleevi ,
I'm the technical contact for .kw [registry](https://www.iana.org/domains/root/db/kw.html) and this is to confirm that 2nd level domains on .kw will be allowed to the public to registered. we ran into the same issue when we wanted to SSL http://nic.kw and http://www.kw and were forced to only include www.nic.kw

We are under ongoing policy updates for .kw 2nd level specifically and shall be published soon. All recent policies can be found here https://www.nic.kw/en/policies/ for your reference.

As we are still under some housekeeping and publicsuffix is on my list.

I shall soon submit a PR as per your [guidelines](https://github.com/publicsuffix/list/wiki/Guidelines) once I'm done.

**Comment by weppos** [comment]
@Bashar thanks for joining the discussion. I've looked into the policies you referenced, but sadly the content of the PDF files is not in English and I can't really understand what it is in it.

Should you provide a pull-request with the proper changes (or provide here a list of official suffixes), I will be happy to authenticate the request even via email (as we allow for registries) and merge the changes.
