### ISSUE TITLE
IANA/ICANN patch utility sensitive to changes in *.zw

### ISSUE THREAD

**Issue by sleevi** [publicsuffix/list#643]
When we landed https://github.com/publicsuffix/list/pull/369 , we broke https://github.com/publicsuffix/list/blob/master/tools/patchnewgtlds , which was sensitive to expecting "*.zw" to place the new ICANN/IANA TLDs. As a result, we haven't been picking up the differences for some time.

The script should be updated to recognize `org.zw` as the marker in the short-term, but longer-term, we should look at a clearer end-marker.

**Comment by weppos** [comment]
Wow, good catch.

I think that is kind of fragile to base the tool on a token that also represent a data.
What do you think if we add a `// newGTLD` comment after the current `org.zw` rule, and we update the script to use it? That would be a more stable reference.

I can open a PR.

**Comment by sleevi** [comment]
Yeah, sorry, I didn't mean to close that with this commit. Let's open a new PR for the follow-up, as that's exactly what I was thinking :)
