### ISSUE TITLE
First come first serve

### ISSUE THREAD

**Issue by hdrxs312** [publicsuffix/list#647]
Hi all maintainer..
Actually, i want to ask this question since 3 months ago.
Why first Pull Requests submitted did not get reviewed. on other side, there is new PR but already get reviewed.
.
For example, my PR has submitted 5 months ago, but hasn't got review yet.
And there are 3 PR that get review just between 1 - 5 days after submission.
.
Why you did not use "First Come First Serve" procedure?

**Comment by sleevi** [comment]
This is a volunteer run project. Pull requests are reviewed as volunteers have time. There is a mailing list for asking questions - no need to file issues. https://groups.google.com/forum/#!forum/publicsuffix-discuss

**Comment by hdrxs312** [comment]
i can't post there..
it's not about available time.
it's about "who first submit, and who first served".
.
did you know that our project is as important as another PR that has approved.
.
like hosting provider that selling subdomain.. so did we. 
we need cookie isolation among subdomains.
.
what do you think about my case?

**Comment by weppos** [comment]
Not all PRs have the same priority, as I mentioned in #638
We are not going to provide here specific replies to your case. You already have a ticket open that will be reviewed at some point, we'll follow up there.
