### ISSUE TITLE
Add NITR.PRO

### ISSUE THREAD

**Issue by RegistryPRO** [publicsuffix/list#657]
Please return the suffix NITR.pro to the ICANN list

**Comment by RegistryPRO** [comment]
Can I prepare registry alias in DNS, BUT if they can provide the ID

**Comment by RegistryPRO** [comment]
https://github.com/mhuggins/dominatrix/blob/master/lib/extensions.txt

**Comment by sleevi** [comment]
What are you talking about?

**Comment by RegistryPRO** [comment]
@sleevi The NITR.PRO suffix add in list ICANN Root Domains

**Comment by RegistryPRO** [comment]
@sleevi Why was it closed?

**Comment by RegistryPRO** [comment]
@frju365 How are you? 
I tried to open a PR, but I can not. I do not know how to create a PR. 

Thank you very much

**Comment by RegistryPRO** [comment]
@frju365 Sorry to bother you but but I really do not know C go or open a PR.

**Comment by frju365** [comment]
Fine, thanks.
To open a PR, it's quite simple : first you go on the https://github.com/publicsuffix/list/blob/master/public_suffix_list.dat file. You click on edit at the top right of the page. It will create automatically a fork on your account. After clicking, you will be able to modify the file. So, here you can add the domain you want to add : if it's a private domain, you must add it in the private section (end of the file). After editing, you click on "Propose File Change". After clicking, you will have a page to compare your change with the master branch. Click on "open a PR" or the button which is in green. After that, you will be able to add a description : follow the guidelines. Then click on the green button. That's it. Then, don't forget to add your TXT record with the URL of the PR and add the test you did(in comment or by editing the description). Finally, check your PR (if everything seems ok to verification) : https://github.com/publicsuffix/list/wiki/Guidelines#submit-the-change

**Comment by RegistryPRO** [comment]
@frju365 ok. I'll try again

**Comment by RegistryPRO** [comment]
@frju365 I'm very happy with the explanation you gave me. They never explained me as well as you!

I do not know if I did it right, but I tried to do my best not to make a mistake or cause a problem.
Thanks for the help, you are a great person!

I create a PR.

**Comment by RegistryPRO** [comment]
@frju365 Thank you for your help and for teaching me. The community needs more people like you!

Thanks for the teachings
