### ISSUE TITLE
PR model

### ISSUE THREAD

**Issue by frju365** [publicsuffix/list#662]
Hello,

I had an idea... Why can't we add a model of PR on github the user has just to complete ? As model, I would take take this : https://github.com/publicsuffix/list/pull/615 . It seems to be the most complete PR we had. I know we can set model in Github Settings for PR and Issue.

Thanks in advance for your answer,
frju365

**Comment by sleevi** [comment]
@frju365 It's something I'd thought about (and was experimenting with in my local repo), along with local checkboxes & the like.

That said, I'm a bit mixed at how well it'd help - it's not clear that it would help ensure people read the Guidelines any more carefully than they do now.

**Comment by frju365** [comment]
Yeah. Of course ppl need to read guidelines and not sure this will ensure ppl read it, but at least it will be more easy to validate each PR, and perhaps clearer for the users which will did them. I think what did Yunohost Orga in #615 is good. We have every info. And we can add the guideline#submit_the_change directly in the PR model. It will avoid problem like in the last PR we saw.

**Comment by frju365** [comment]
Moreover it's easy, and works very well in some orga I work for. Same for the Issue. You can see PR model of the Yunohost orga itself which are quite nice... and really, it helps the contributors/users.
https://github.com/YunoHost/yunohost/pulls

**Comment by sleevi** [comment]
Yeah, it's not difficult to do ( https://help.github.com/articles/creating-a-pull-request-template-for-your-repository/ ), but basically felt tantamount to duplicating the Guidelines

**Comment by frju365** [comment]
ok. I can do a model for you if you want ;-) I persist to say it's well better and will avoid problem like the #661 or #651 where I needed to say what was written in the Guidelines. :-)
