### ISSUE TITLE
Change to a nice forum ?

### ISSUE THREAD

**Issue by frju365** [publicsuffix/list#664]
Hello,

It's very weird that an orga like the PSL uses Google Discussion. There are big problems in using this Google Service : 
- you have to signup to every services of Google
- you have to accept Google privacy policy (which is not really good)
- you can't discuss without google (as you want absolutely that everything goes on this discussion place)
- And it's not really attractive

Google is really not good to discuss. So what about a nice forum to discuss about the PSL ?
We could make tag, split discussions (between IANA and Private domain for example, or between dev of the PSL and contribution) and the user won't have to accept any contract which is made by a big company (which is not respectful about our privacy -- cf. "Snowden", "Cambridge analytics", "GPRD"...).

Moreover, the forum has a big advantage is that we are free to do what we want on this. We can maintain it as we want to.

Then, another advantage is that we can make sub-forum to discuss perhaps per language, and moreover, we could perhaps integrate Github Issues/PR in the forum.

Then, like that, it will prevent us to pollute PR with big discussion like the last one. We have just to give an invitation link to the user and he will be able to discuss with us on the forum without to signup to Google Services.

Then, it's attractive, so more ppl will perhaps develop (help) the PSL and help us in fact.

Finally, maintaining a forum can be made by psl-maintainer at the beginning but can quickly evolved to a community forum where the maintainers will be persons of the community.

For the software you can use to build a forum, it's easy : 
- You have a VPS : 
    - Flarum
    - Discourse
- You have not a VPS : you have online forum, Reddit, StackExchange...

Other Idea which are costless : 
- Matrix : Very good for chat and discussion. Sometimes, we answer question the users made 20 min ago. So we could add a link to our channel and invite the user to discuss.
- IRC : As Matrix it's free and very good for short discussion or **community** discussion.
- XMPP
- A classic mailling-list : https://framalistes.org (french association/community) which allows you to create mailing-list using a free software called "Sympa"

So, could it be good to have a forum or another solution than than Google Discussion ? It's just an idea, "not because every communities have one", but because it's strategical.

Thanks in advance for your answer,
frju365

PS: sorry for my bad english. :)

**Comment by weppos** [comment]
I appreciate your feedback @frju365, but I don't think that investing time and effort in setting up a forum and maintaining it (without even mentioning the need to find a place to host it) is a good use of our time at the moment.

The advantages you mentioned may make sense for large volume mailing lists, but our mailing list currently has a very low volume. Therefore there is no need at all for sub forums or other features.

Can we move the mailing list elsewhere? Probably yes. Should we? Personally, I don't think we should at the moment.

I can't speak for @sleevi, but being him a Google employee I think he has even less issues than me in keeping using Google Groups for now.

I understand your personal feelings against Google @frju365, and there is nothing personal in my response, but at the time being we need to focus on the best use of our time for the best interest of the project.

For what is worth, I assume you can signup with a different email and then just use the email system to interact with the ML, without having to use the Google Groups interface nor signup in other Google services.

**Comment by sleevi** [comment]
I agree. I appreciate the thoughtful suggestion, but it is not in line with the needs of the PSL at this time.

**Comment by frju365** [comment]
ok. So, I hope you will understand that I will speak to the contributors in PR/Issues instead. I hope you understand my choice.

**Comment by frju365** [comment]
Ah yes: I forgot to say that I'm not against Google itself, but against it's policy (privacy policy in particular), and I want simply promote Free softwares. If you want I have a little server at home. If it's not really important, I can try to set up a forum and maintain it if you agree.

**Comment by sleevi** [comment]
Thank you for your offer, but setting up a separate forum is not desired. While we understand that may limit your participation - as @weppos noted, this tracker explicitly should not be used as a Forum or mailing list - the current solutions best reflect the projects desires for maintenance and communication.

As noted, using the issue tracker instead of the psl-discuss mailing list creates more work for the project members, and thus while well intentioned, unfortunately hurts more than it helps.

**Comment by frju365** [comment]
Well, yes... but I won't use Google. :) It's either I help here, either I don't help anymore. :-) Really sorry.

**Comment by sleevi** [comment]
@frju365 I understand, and if you’re unable to help in a way that is helpful to the project, then it may be best not to. As mentioned, you don’t have to use a Google account to participate, and while you can certainly help on PRs as appropriate, please respect the wishes of the project and don’t use Github as the discussion forum. Thank you for understanding.

**Comment by frju365** [comment]
Well. Ok. I will try to use the PSL Google discussion... without a Google account. (I missed the sentence, sorry). I read too fast. Thanks.
