### ISSUE TITLE
Australian gov.au third level domains in PSL

### ISSUE THREAD

**Issue by weppos** [publicsuffix/list#665]
This ticket is migrated from https://bugzilla.mozilla.org/show_bug.cgi?id=884195

---

Today I received a bug report about the parsing of the .gov.au TLD.

> I get an error like " 'hostname' is not allowed according to Registry policy ". But wa.gov.au and sa.gov.au are valid hosts.
> https://github.com/weppos/publicsuffix-ruby/issues/30

I see there is a list of Australian third level domains in the PSL

```
// 3LDs
qld.gov.au
sa.gov.au
tas.gov.au
vic.gov.au
wa.gov.au
```

I wonder if there is any reason to list them. Apparently, they are perfectly valid domains.
I tried to search for a ticket or reference, but I was only able to find a request to unlist nsw.gov.au in Bug 547985.

**Comment by weppos** [comment]
Also note that some `gov.au` where requested for removal:

```
// act.gov.au  Bug 984824 - Removed at request of Greg Tankard
// nsw.gov.au  Bug 547985 - Removed at request of <Shae.Donelan@services.nsw.gov.au>
// nt.gov.au  Bug 940478 - Removed at request of Greg Connors <Greg.Connors@nt.gov.au>
```

**Comment by weppos** [comment]
I vote to try to validate the need for that rules with the `gov.au` administrators (or fallback to `au`), and unless required remove them.

@sleevi @dnsguru objection? Any of you happen to have contacts with .AU to share privately?

**Comment by sleevi** [comment]
@weppos No private contacts, although it seems pretty obvious from their usage that they probably do want to be on there, even if some have requested removal. While registration is centrally maintained, operation of services and domains seems to be disparate systems (i.e. cookie blocking helps).

**Comment by weppos** [comment]
There are apparently multiple websites at 4th level:

https://www.google.it/search?q=allinurl:sa.gov.au
https://www.google.it/search?q=allinurl:tas.gov.au

At this point, I am not going to take action on those suffixes and leave it as it is, until we get any input from someone at .AU.

**Comment by gsouf** [comment]
@weppos are domains in PSL supposed to be things that we cannot use as a website or email address? Because for example sa.gov.au responds to http requests, and emails addresses in @sa.gov.au do exist

**Comment by dnsguru** [comment]
@gsouf We just catalog a list of things, we don't prescribe what gets done with it in whatever way by whomever or when.
