### ISSUE TITLE
Clarification on non-matching rules under a known TLD

### ISSUE THREAD

**Issue by rushmorem** [publicsuffix/list#689]
While testing my implementation against two other implementations I noticed that from a list of domains I was parsing, mine parses one domain as invalid that the other implementations saw as valid. The domain is "gp-id-ter-acc-1.to.gp-kl-cas-11-ses001-ses-1.wdsl.5m.za".

The rules for the `za` TLD are as follows:-

```
ac.za
agric.za
alt.za
co.za
edu.za
gov.za
grondar.za
law.za
mil.za
net.za
ngo.za
nis.za
nom.za
org.za
school.za
tm.za
web.za
```

As you can see, none of the rules match so those other implementations are, understandably, invoking this part of the algorithm:

> If no rules match, the prevailing rule is "*".

thereby returning the public suffix as `za` and the registrable domain as `5m.za`.

My question is, since this domain is falling under a known TLD, `za`, shouldn't it be treated as invalid rather than invoking the wildcard rule?

**Comment by sleevi** [comment]
The PSL does not distinguish on the notion of 'known TLDs' - if they did, that'd be part of the algorithm as well :)

**Comment by rushmorem** [comment]
I see. Thanks for clearing that up for me.
