### ISSUE TITLE
Use normalized non-ASCII names

### ISSUE THREAD

**Issue by rockdaboot** [publicsuffix/list#715]
Some international domain names / rules use composed characters, others use decomposed chars.

E.g. `läns.museum` is composed while `südtirol.it` is decomposed.

For comparison of strings it would be nice to have just one *or* the other. Since older entries are composed, I suggest NFKC as described at https://en.wikipedia.org/wiki/Unicode_equivalence#Normalization.

**Comment by weppos** [comment]
@rockdaboot I actually think we should convert the entire definition in A-labels. The only reason I frankly haven't pushed this change forward (yet) is because it will be a compatibility break and hence it will need to be handled carefully. Ideally also taking advantage to switch to a more flexible format.

I'm collecting current issues here https://github.com/publicsuffix/list/wiki/Design-issues

I recall the folks at Let's Encrypt reporting this as issue, as well other entities. Basically, almost nobody uses U-labels for comparison. I had to switch my libs to pre-process the list into A-labels before caching a copy of the list.

I asked Gerv in the past, and he said it was likely a mistake to use U-labels.

Do you see any issue in your use cases to have a list of punycode entries instead of unicode?

**Comment by rockdaboot** [comment]
> Do you see any issue in your use cases to have a list of punycode entries instead of unicode?

Not basically. But just to be sure I would like to test a list with A-Labels with libpsl. I'll report back.

**Comment by rockdaboot** [comment]
Well I have to amend libpsl. When loading public_suffix_list.dat, UTF-8 NFKC is expected. Currently, U-Labels are stored as found and also converted & stored as A-Labels (punycode).

All it needs is to convert A-Labels to their U-Label form and store both. I could do that in the next days and make up a release. Just to be prepared for a coming change.

**Comment by rockdaboot** [comment]
But apart from that, it would be nice to have NFKC in public_suffix_list.dat right now.

**Comment by sleevi** [comment]
@weppos Do you think we should take all the compatibility issues in one change, or do you think it's reasonable to set the expectation that we'll *keep* making compatibility changes, and that consumers must have flexibility to update implementations (and/or to process into their preferred 'static' format)?

**Comment by weppos** [comment]
@sleevi that's a good question. I understand the implication of making changes to the currently published version of the list. Reason why I have been collecting the ideas and my preference would be for going through the list at one shot and try to come with a format that could be extendible enough to allow further customizations (JSON?).

Having said that, what I would propose is to:

1. Create a new definition file, eg `list.json`
2. Edit that file as master
3. For an undefinite amount of time, have the current `public_suffix_list.dat` be auto-generated from that list, but in a way that will preserve compatibility

For example, should we decide to use JSON and A-names, it should be fairly easy to generate automatically post-commit the `public_suffix_list.dat` converting the A-names back into U-names, and dumping the list in a TXT file as today.

Consumers will have the time to transition from the previous implementation into the new one, either depending directly or in turns by processing the new file into their own preferred static format.

This would be the approach I would propose.

**Comment by weppos** [comment]
> But apart from that, it would be nice to have NFKC in public_suffix_list.dat right now.

Please give me some time to research into the topic. I admit my ignorance here, encoding is not my top skill.

**Comment by rockdaboot** [comment]
Please move the format/JSON discussion into a separate issue. It is not directly related to this one.

Meanwhile, I got the first bug report against libpsl due to non-NFKC entries in PSL. Please have a look at https://github.com/rockdaboot/libpsl/issues/108 for some explanation why non-NFKC needs a IDN library (you don't have one when choosing 'build libpsl without IDN library').

**Comment by rockdaboot** [comment]
@weppos Good to have the list in NFC. Should I extend the TravisCI file(s) to error on non-NFCK (when checking PRs) ?

**Comment by weppos** [comment]
> Should I extend the TravisCI file(s) to error on non-NFCK (when checking PRs) ?

That would be awesome @rockdaboot 👍
