### ISSUE TITLE
[feature suggestion] automatic submission handling

### ISSUE THREAD

**Issue by naox** [publicsuffix/list#72]
How about making system for handling automatic submissions for publicsuffix list for domain owners? 
- page for submiting domain/subdomain (with captcha)
- scan new submitions immediately and all submited domains every ~30 days - check http://submited-domain/.well_known/public_suffix for value '1'
- if value is 0 then remove from list
- if scan fails retry 5 times, 24h apart. If value is still neither 1 or 0 remove from list

(by submiting domain/subdomain again and placing 0 in .well_known/public_suffix you basicly request quick delist)

alternatively you can do same thing but using dns txt record for lower load/traffic. edit: now I think of it dns txt record would be probably better but if immediate actions were to be supported system would have to do recursive lockups (to avoid cache) (just for those immediate actions)

without this publicsuffix system is basicly catalog for only tld prefixes - and it could be much more.

**Comment by sleevi** [comment]
> without this publicsuffix system is basicly catalog for only tld prefixes

I'm not sure I understand this part. The PSL contains, well, public suffices, which needn't be TLDs.

For the programatic expression of domain policy - and the complexities therein - you probably want the [IETF DBOUND WG](https://www.ietf.org/mailman/listinfo/dbound) as the place to propose/discuss.

As for automation, please be aware that changes to the list can take anywhere from 6 weeks to 6 months in many popular programs, and even longer for the long-tail. If the goal is for more rapid changes (which seems to be the case), then that's a separate problem.

**Comment by naox** [comment]
You are probably right. Whole publixsuffix list is just a dirty walkaround for a lack of standarised way for domain owners to declare their domain as public suffix by a creating well known dns record. Browsers and every other program that want to know if domain is public suffix sould check this well known record instead of checking hardcoded copy of list (facepalm). Maybe even it would be possible for registries to publish such records on TLDs (?)

**Comment by weppos** [comment]
@naox thanks for the suggestion. We all agree that some level of automation should be introduced.
I am closing this ticket as it's not directly actionable and it's more a discussion thread.

We'll follow up as soon as we'll be able to work on something practical.
