### ISSUE TITLE
https://publicsuffix.org/list/public_suffix_list.dat outdated

### ISSUE THREAD

**Issue by yaneti** [publicsuffix/list#724]
Seem the website linked list served by Amazon/Cloudfront is a month old. Which does not correspond to the stated update blurb on the site.
```
Last-Modified: Wed, 03 Oct 2018 14:33:30 GMT
```

**Comment by weppos** [comment]
Thanks. I reported it https://bugzilla.mozilla.org/show_bug.cgi?id=1515909

**Comment by sleevi** [comment]
Thanks; I somehow missed that bug. Upstream is reporting that mirroring is working now.
