### ISSUE TITLE
Update about open PR

### ISSUE THREAD

**Issue by matyix** [publicsuffix/list#749]
Hello maintainers 

I'd like to inquire about our PR - https://github.com/publicsuffix/list/pull/730. We'd really like to manage subdomains properly and provide an additional level of security to our end users.  The service was launched last month and there are already hundreds of active users. 

Could you please give us some additional guidance or advice on how could we help to speed up the process? Appreciate your feedback and help.

Thanks.
Janos

**Comment by weppos** [comment]
There is no need to open a new ticket for feedback. You already have an existing one. We also have a mailing list.

We are not able to provide a specific ETA. We will communicate further feedback on #730 when we'll be able to review it.
