### ISSUE TITLE
when you merge pull requests?

### ISSUE THREAD

**Issue by kraja** [publicsuffix/list#776]
Hello,
please, exactly, when you merge pull requests? We waiting many months. If you need any donate anywhere to speed up this, ok, i am ready. I mean many of other requesters is too ready. 

But, sorry, its big problem if your work, our clients, waiting months, and we cant doing anything to speed up. 

Thanks, Michal

**Comment by weppos** [comment]
See https://github.com/publicsuffix/list/issues/760

**Comment by kraja** [comment]
Its not relevant reply, sorry. I can read. 

It is really bad that someone takes the authority to manage something, and then does not do it.

**Comment by weppos** [comment]
There is activity in this repository, so it's clearly managed
https://github.com/publicsuffix/list/commits/master

The process we are adopting may not meet your expectation, but it's designed for the best interest of the project and not of a specific entity, and the time each contributor can allocate.

**Comment by weppos** [comment]
And for the records, you got a feedback on your PR https://github.com/publicsuffix/list/pull/734 on November and you ignored it since today. So blaming us for delays in this circumstance it's a bit inappropriate.

**Comment by kraja** [comment]
> 
> 
> And for the records, you got a feedback on your PR #734 on November and you ignored it since today. So blaming us for delays in this circumstance it's a bit inappropriate.

Sorry, but same problem have in #760  what you linked, on his pull request i cant see any comment from you. I fix my request if there bug immediately, but again: i do not understand where you see problem, i cant see anything bad. Thanks

**Comment by kraja** [comment]
@weppos Can you respond me please, where is problem in #734 ? I still not understand what is bad. We really need it update :-( Thanks
