### ISSUE TITLE
Add .GAYS.LGBT

### ISSUE THREAD

**Issue by gayslgbt** [publicsuffix/list#777]
Add .GAYS.LGBT in private seccion.

Thanks

**Comment by gayslgbt** [comment]
@frju365 Do you know an easier way to create a Pull Request?

Because the Guideline is difficult to understand.

Thank you

**Comment by weppos** [comment]
Hello, please take a look at https://help.github.com/en/enterprise/2.16/user/articles/editing-files-in-your-repository, https://help.github.com/en/articles/creating-a-pull-request and https://github.com/publicsuffix/list/wiki/Guidelines
