### ISSUE TITLE
amend rw zones in public suffixes

### ISSUE THREAD

**Issue by rwakajan** [publicsuffix/list#819]
hello
can you help to update rw zones in https://publicsuffix.org/list/public_suffix_list.dat with update information below.
we are non-profit company located in Rwanda and mandated to manage .rw domains.

// rw : http://www.ricta.org.rw/about-us
rw
gov.rw
net.rw
ac.rw
co.rw
coop.rw
org.rw
mil.rw

regards,

Janvier R.

**Comment by sleevi** [comment]
Thanks for opening this. I can confirm that RICTA is listed as the ccTLD operator, as per https://www.iana.org/domains/root/db/rw.html

Normally, we validate based on published registry policies - thus not requiring any secondary validation of the person making the request. While the [Registry/Registrar Agreement](https://www.ricta.org.rw/sites/default/files/resources/registry_registrar_contract_0.pdf) does not appear to be the normal Registry policy, I will note that Annex 2, Section 3.2 (Page 16) does note that these are reserved 2LDs by the registry. I'll open a pull request to update the .rw section accordingly.

**Comment by sleevi** [comment]
In looking at the changes, this will remove the following:

`com.rw`
`edu.rw`
`gouv.rw`
`int.rw`
`mil.rw`

Can you confirm that this is intentional, and that there are no registrations within these namespaces? If there are, this may have serious security implications and disruptions for these sites, and it would be advisable not to remove them until all existing registrations have expired/been revoked.

**Comment by rwakajan** [comment]
Thanks for reply.

i confirm that this request is intentional from RICTA, and there are no
registrations within these namespaces thus no impact to remove them.

**Comment by sleevi** [comment]
Do you have an email at RICTA that we can use to confirm that? I just want to make sure we're definitely talking to someone authorized to speak on RICTA's behalf :)

**Comment by rwakajan** [comment]
Thanks Sleevi
yes, we do have email.
you can use below emails to confirm
noc@ricta.org.rw
rw-adm@ricta.org.rw

**Comment by sleevi** [comment]
Confirmed with Registry based on IANA-provided contact mails.

**Comment by rwakajan** [comment]
Thanks for the email the confirmation is sent to your email.
kindly note the changes to rw zones to upload. Just added mil.rw

// rw : http://www.ricta.org.rw/about-us
rw
gov.rw
net.rw
ac.rw
co.rw
coop.rw
org.rw
mil.rw

sorry for inconvenience.

regards,

Janvier R.
