### ISSUE TITLE
The NewGTLDs script should use the ICANN JSON feed

### ISSUE THREAD

**Issue by sleevi** [publicsuffix/list#831]
As captured in https://github.com/publicsuffix/list/pull/822#discussion_r289142418 , ICANN has switched to providing the gTLD list via JSON at https://www.icann.org/resources/registries/gtlds/v2/gtlds.json and the CSV list at https://www.icann.org/resources/registries/gtlds/v1/newgtlds.csv

We should update the[`newgtlds` script](https://github.com/publicsuffix/list/blob/master/tools/newgtlds) to use the new feeds.

**Comment by cpu** [comment]
I wrote a small Go tool that uses the v2 JSON feed for [`zlint`](https://github.com/zmap/zlint) called [`zlint-gtld-update`](https://github.com/zmap/zlint/blob/master/cmd/zlint-gtld-update/main.go)

On top of that I have an [automation repository](https://github.com/cpu/zlint-autopull) (based on athe approach @weppos uses with [publicsuffix-go](https://github.com/weppos/publicsuffix-go)) configured with a once-a-day Travis CI cron build to make automatic PRs when TLD data changes.

My Python skills aren't as refined as my Go skills but I think with some review help I can arrive at a solution that works for you folks if it would be helpful! I would probably have time to start on this late next week.

**Comment by weppos** [comment]
Thanks for the offering @cpu. You know I'm an happy Go dev too, so I would be totally fine with using Go. Python was used in the past because previous contributors/maintainers (notably @gerv) were familiar with that.

I am actually not using Python at all, I believe the last time I've used it was to adjust the code in this repo. 😅

**Comment by cpu** [comment]
>  I would be totally fine with using Go. 

That would certainly make my life easier :+1: :rocket:

**Comment by weppos** [comment]
@sleevi any preference?

**Comment by sleevi** [comment]
I’m perfectly happy with Go :)

**Comment by cpu** [comment]
Great! 

Would you folks prefer to see the existing tool ported to Go using the same deprecated data source in one PR, and then separately updated for the new JSON data source in a follow-up or is it acceptable to do both in one fell swoop?

**Comment by sleevi** [comment]
One fell swoop is fine

**Comment by cpu** [comment]
I started working on this today. Hope to have a PR up for review shortly.

**Comment by cpu** [comment]
A first version is ready for review: https://github.com/publicsuffix/list/pull/834
