### ISSUE TITLE
public_suffix_list.dat out of date

### ISSUE THREAD

**Issue by autodiscover** [publicsuffix/list#833]
I just noticed that https://publicsuffix.org/list/public_suffix_list.dat is out of date: It does have commit 1170111 (iobb.net), but not 6f03f42 (web.app). This means that the last update to the file was 12 days ago.

As I have worked with the PSL quite a lot recently, I'd be happy to give something back, maybe in the context of automation/monitoring of the file status. I understand that Mozilla manages the synchronization state, but maybe there's still something I can help out with.

**Comment by sleevi** [comment]
Thanks! I filed this for Mozilla's infrastructure team at https://bugzilla.mozilla.org/show_bug.cgi?id=1558748 - as we here from them, I'll update this.

**Comment by autodiscover** [comment]
The download file is up to date again.
