### ISSUE TITLE
Clarify how to run the tests

### ISSUE THREAD

**Issue by unilynx** [publicsuffix/list#848]
It would be nice to update the Wiki page to specify the recommend platform for `make test` to run on. I ran through OSX, Fedora latest, Ubuntu LTS 18.04 before hitting on debian:stable on which the tests finally compiled and all succeeded. 

(if it's useful, I could contribute a Dockerfile which would just let anyone run `docker run xxx/testpsl https://github.com/WebHare/list.git` to clone and run the tests, but that's basically just reinventing what Travis already does for you)

**Comment by simon-friedberger** [comment]
AFAICT the tests run on all of these platforms but sometimes require setting up dependencies. If need be, we have them in GH actions.
