### ISSUE TITLE
public_suffix_list.dat out of date

### ISSUE THREAD

**Issue by peterthomassen** [publicsuffix/list#852]
I just noticed that https://publicsuffix.org/list/public_suffix_list.dat is out of date: It does have commit 333c03bfdf0b86ddca6191b80ac7cabe18910af6 (*.webhare.dev), but not e8812ff555bac71fba170fc7add5bd6248230df5 (lelux.site). This means that the last update to the file was 6 days ago.

As I said before, I'd be happy to give something back to the community, maybe in the context of automation/monitoring of the file status. I understand that Mozilla manages the synchronization state, but maybe there's still something I can help out with.

**Comment by weppos** [comment]
Moving the conversation to https://bugzilla.mozilla.org/show_bug.cgi?id=1558748

Regression from #833
