### ISSUE TITLE
Provide checksum for the file

### ISSUE THREAD

**Issue by cmouse** [publicsuffix/list#87]
While the file is transferred over HTTPS it would be benefitial for many cases to provide a checksum to ensure transfer and storage succeeded, meaning you could download https://publicsuffix.org/list/public_suffix_list.dat.sha256 as well. Or something similar.

**Comment by gerv** [comment]
Regenerating this every time would be a pain in the behind. If you are concerned about this problem, obtain the file using Git rather than HTTPS download, which will automatically verify the integrity for you.

Gerv
