### ISSUE TITLE
Is this list in: "https://www.publicsuffix.org/list/" an updated list?

### ISSUE THREAD

**Issue by ealashwali** [publicsuffix/list#875]
Hi, I want to use the [tldextract library ](https://github.com/john-kurkowski/tldextract) for treating domain names, which relies on the public suffix list provided [publicsuffix.org](https://www.publicsuffix.org/). The list page states that it is updated daily from your Github page [see](https://www.publicsuffix.org/list/). 

However, the copyright of the publicsuffix.org page is `Copyright © 2007–16 Mozilla Foundation. ` which made me confused. Is the list provided in [the publicsuffix.org](https://www.publicsuffix.org/) updated or not? Can you plz confirm to me if you have any idea about that?

**Comment by sleevi** [comment]
As you note, that's the copyright of the page you're looking at, not the list.

Yes, the list is normally updated daily. We've got a [slight bug](https://bugzilla.mozilla.org/show_bug.cgi?id=1558748) with it not updating for the past week, but it's otherwise current.
