### ISSUE TITLE
Remove k12.ri.us domain to migrate domain to new Managed DNS provider

### ISSUE THREAD

**Issue by OSHEAN** [publicsuffix/list#903]
Hello,
Please remove k12.ri.us from list
// k12.ri.us

Descripton of Organization
Reason for PSL Removal
DNS verification via dig

Description of Organization
Organization Website: https://www.oshean.org

OSHEAN, Inc. is an ISP for Research and Education Networks.  We provide IPs, Transport, Managed DNS hosting and cloud service provider.

Reason for PSL removal
k12.ri.us is a domain that we manage and host. We are moving the Managed DNS service to a new provider and the zone can't be imported due to the public list check.  We were advised to remove the domain from the list by the provider.

DNS Verification via dig

_psl.k12.ri.us.		59	IN	TXT	"https://github.com/publicsuffix/list/issues/903"

Thank you.

**Comment by dnsguru** [comment]
MERGED AND CLOSED #923
