### ISSUE TITLE
Missing TLDs

### ISSUE THREAD

**Issue by wavenator** [publicsuffix/list#918]
.iselect
.active
.vista
.bnl
.boots
.duns
.epost
.goodhands
.starhub
.xperia
.spiegel

**Comment by sleevi** [comment]
Thanks for reporting this.

It's correct that these entries are not listed. You can view why at the IANA Root Zone information:
* https://www.iana.org/domains/root/db/iselect.html
* https://www.iana.org/domains/root/db/active.html
* https://www.iana.org/domains/root/db/vista.html
* https://www.iana.org/domains/root/db/bnl.html
* https://www.iana.org/domains/root/db/boots.html
* https://www.iana.org/domains/root/db/duns.html
* https://www.iana.org/domains/root/db/epost.html
* https://www.iana.org/domains/root/db/goodhands.html
* https://www.iana.org/domains/root/db/starhub.html
* https://www.iana.org/domains/root/db/xperia.html
* https://www.iana.org/domains/root/db/spiegel.html

Other unassigned names include:
* https://www.iana.org/domains/root/db/blanco.html
* https://www.iana.org/domains/root/db/cartier.html
* https://www.iana.org/domains/root/db/chloe.html
* https://www.iana.org/domains/root/db/doha.html
* https://www.iana.org/domains/root/db/everbank.html
* https://www.iana.org/domains/root/db/honeywell.html
* https://www.iana.org/domains/root/db/htc.html
* https://www.iana.org/domains/root/db/iwc.html
* https://www.iana.org/domains/root/db/jlc.html
* https://www.iana.org/domains/root/db/mcd.html
* https://www.iana.org/domains/root/db/mcdonalds.html
* https://www.iana.org/domains/root/db/meo.html
* https://www.iana.org/domains/root/db/mobily.html
* https://www.iana.org/domains/root/db/montblanc.html
* https://www.iana.org/domains/root/db/pamperedchef.html
* https://www.iana.org/domains/root/db/panerai.html
* https://www.iana.org/domains/root/db/piaget.html
* https://www.iana.org/domains/root/db/sapo.html
* https://www.iana.org/domains/root/db/statoil.html
* https://www.iana.org/domains/root/db/telecity.html
* https://www.iana.org/domains/root/db/zippo.html
