### ISSUE TITLE
Please remove .gov.au

### ISSUE THREAD

**Issue by RichardDenver** [publicsuffix/list#92]
After cross government consultation, agreement and permission has been granted by the Domain Name Administrator at the Department of Finance and Deregulation to remove .gov.au from the public suffix.  AUDA have been notified of our intent to remove the .gov.au from the public suffix list. Please remove at your earliest convenience.

// gov.au - Bug XXXXXX - Removed with permission from the Commonwealth of Australia at the request of Richard Denver

**Comment by sleevi** [comment]
Could you explain more about the motivating change? Has the Financial Management and Accountability Act of 1997 been superceded, or are organizations still required to host within the .gov.au namespace?

As far as authorization, AuDA/AusRegistry seems to still be the appropriate party to request removal, but that seems like a move that will put .gov.au domain holders at risk of a variety of cross-domain attacks, which places users and visitors information at risk, and for which the presence on the PSL mitigates.

**Comment by RichardDenver** [comment]
Hi Sleevi,

All government departments and agencies are required to use .gov.au domain names. The FMA Act 1997 still remains in place. New Digital Principals and standards have been introduced (see https://www.dto.gov.au/standard ) as well as new Privacy principles (see https://www.oaic.gov.au/privacy-law/privacy-act/australian-privacy-principles).

I understand your concern, AuDA have been part of the discussions and the decision has been reached to enable current and future cross government service integration. AuDA represent the .au domain space and they have confirmed that ownership of .gov.au resides with the Commonwealth and any decision regarding it. They have also provided email advice to contact the group direct and request the change be made. Happy to share this correspondence if it is required to complete the request.

Decisions regarding the state domains will remain with the states at this time.

Thanks

Richard

**Comment by gerv** [comment]
Assuming we can authenticate this request, as I'm sure we can, and we believe that they understand the consequences of what they are doing, I think we shouldn't keep a domain name on the PSL against the express wishes of its owner. gov.foo is always a bit of an edge case - some governments appreciate the protection of one site from another, other governments want to do single-signon at the top level. (The UK uses services.gov.uk for all services, perhaps to avoid the issue here.) If Australia wants to be in the second category, we shouldn't stop them.

**Comment by gerv** [comment]
Richard Denver: can you name a clearly-official email address we can bounce an email off for due diligence authorization for this change?

**Comment by RichardDenver** [comment]
Hi Gervase an authentication email can be sent to r.denver@bom.gov.au

Thanks
Richard

Sent from my Windows Phone
________________________________

**Comment by sleevi** [comment]
@gerv , Richard: I guess my concern with authenticating is that the Bureau of Meteorology doesn't represent the authorized domain namespace for .gov.au.

Richard, do you have a contact at either AuDA or AusRegistry that we could authenticate? As Gerv said, if we can authenticate, and if the stakeholders are aware of the risks posed, then we should honor that request, but I do want to make sure we're doing due diligence in authenticating the request as not just being from a potential stakeholder, but as being from the authorized party.

**Comment by RichardDenver** [comment]
Hi Sleevi,

Please provide a valid email address and I will forward through the correspondence from auDA along with the contact person CC'ed as evidence.

Regards
Richard

Sent from my Windows Phone
________________________________

**Comment by sleevi** [comment]
Feel free to send it to sleevi@google.com and I'll happily work to confirm :)

**Comment by sleevi** [comment]
Received the details and am in the process of confirming.

**Comment by sleevi** [comment]
This request is *NOT* authorized by AuDA, who has confirmed that Department of Finance is responsible for managing .gov.au

The extent of the authorization is *only* for adding !bom.gov.au

Would you like to update this request to do so? Otherwise I will need to close this request as unauthorized :(

**Comment by RichardDenver** [comment]
Hi Sleevi,

Please leave the request open as Finance have agreed to the removal of .gov.au and AuDA are aware of this. I will follow up from my end.

Regards

Richard

**Comment by JordanHatch** [comment]
Hi there,

I work for the Digital Transformation Office. We have responsibility for some aspects of administration for the .gov.au domain namespace, working with the Department of Finance.

I just wanted to jump in on this thread to let you know we're following-up internally to understand the background to this request. I'd ask that you hold off making this change at the present time.

Many thanks,
Jordan

**Comment by weppos** [comment]
Closing until further update.
