### ISSUE TITLE
Question - Pseudo extension

### ISSUE THREAD

**Issue by Pseudo-NIC** [publicsuffix/list#944]
Can I include as a suffix the pseudo extension .NE.Tv.BR that acts as an alternative to the extension .NET.BR?

Can you include similar and competing extensions?

.NET.BR X .NE.Tv.BR?

Thanks

**Comment by Pseudo-NIC** [comment]
Example:

WWW.EXAMPLE.NET.BR
WWW.EXAMPLE.NE.Tv.BR

**Comment by weppos** [comment]
These extensions are not competing as they represent different suffixes. You can find here our guidelines for inclusion:
https://github.com/publicsuffix/list/wiki/Guidelines
