### ISSUE TITLE
Proposed new top level domains - no technical skills

### ISSUE THREAD

**Issue by world33** [publicsuffix/list#955]
Hello,

Hopefully someone can help.

When I checked for some University websites on Alexa I noticed that some domains had the same traffic rank because Alexa was considering them as subdomains instead of top level domains.
I contacted the Alexa support to notify them about the error and they replied as follow:
---
Hello,

Thank you for reaching out. Please submit those domains to the Public Suffix List at https://publicsuffix.org/submit/. That list is what we use to distinguish hosting domains and TLDs from non-hosting domains.
Cheers,
Debbie
Alexa Customer Support
---

I tried to have a look at the procedure to submit new top level domains in the website suggested but I found it too complicated for my technical skills and time consuming.
If anyone has experience in these type of submissions please consider to verify whether the following extensions, which all belong to the list below of recognized universities published in uniRank, can be considered top level domains and be properly submitted/added:

Proposed new top level domains:

rs.ba
edu.tl
edu.so
edu.gm
edu.cv
co.cu
ac.cd
ac.bw

List of Universities adopting the above domains and erroneously reported by Alexa with the same traffic rank

Domain	AlexaRank
http://www.ues.rs.ba	119471
http://www.ubn.rs.ba	119471

http://dit.edu.tl	1261688
http://www.untl.edu.tl	1261688

http://bu.edu.so	1585468
http://www.eau.edu.so	1585468
http://plasma.edu.so	1585468
http://simad.edu.so	1585468
http://www.jobkey.edu.so	1585468
http://uss.edu.so	1585468
http://mu.edu.so	1585468
http://nugaaluniversity.edu.so	1585468
http://www.ku.edu.so	1585468
http://www.iou.edu.so	1585468
http://salaam.edu.so	1585468
http://www.uniso.edu.so	1585468
http://just.edu.so	1585468
http://snu.edu.so	1585468
http://psu.edu.so	1585468
http://justech.edu.so	1585468
http://zust.edu.so	1585468

http://www.aiu.edu.gm	176392
http://www.utg.edu.gm	176392

http://meia.edu.cv	176465
http://www.iscee.edu.cv	176465
http://uni-mindelo.edu.cv	176465
http://us.edu.cv	176465
http://www.ulusofona.edu.cv	176465
http://www.unicv.edu.cv	176465
http://www.iscjs.edu.cv	176465

http://www.cug.co.cu	44536
http://www.udg.co.cu	44536
http://www.isdi.co.cu	44536

http://ucc.ac.cd	560874
http://www.unilu.ac.cd	560874
http://ucbukavu.ac.cd	560874
http://www.uniuele.ac.cd	560874
http://upn.ac.cd	560874
http://www.uea.ac.cd	560874
http://um.ac.cd	560874
http://www.unikin.ac.cd	560874
http://www.ucgraben.ac.cd	560874

http://www.boitekanelo.ac.bw	97738
http://www.buan.ac.bw	97738
http://www.megasize.ac.bw	97738
http://www.baisago.ac.bw	97738
http://www.bac.ac.bw	97738
http://abm.ac.bw	97738
http://www.isbs.ac.bw	97738
http://www.neweracollege.ac.bw	97738
http://www.guc.ac.bw	97738
http://www.biust.ac.bw	97738

**Comment by weppos** [comment]
Hello, thanks for your report. Unfortunately, we will need the registry operators to submit and validate these suffixes, or the individual entities.
