### ISSUE TITLE
Re-delegation question

### ISSUE THREAD

**Issue by nic-ml** [publicsuffix/list#956]
Hello, I would like to know if it is necessary to change the delegation of the suffix .presse.ml.

The suffix .presse.ml remains open for domain registrations, but with the privatization of SOTELMA and the extinction of NIC-Mali, the suffix .presse.ml is delegated to WHOIS PRIVACY.

Do I need to change his delegation to Public Suffix or can I keep it as is?

Thanks

www.whoisprivacy.presse.ml

**Comment by weppos** [comment]
It is my understanding, looking at the site, that you are still offering registration at third level domains and that `foo.presse.ml` is potentially owned by a different owner of `bar.presse.ml`. Is my interpretation correct?

**Comment by nic-ml** [comment]
@weppos Yes.

Foo.presse.ml belongs to the owner X

Bar.presse.ml belongs to owner Y

example.presse.ml belongs to owner Z

All of our domains belong to different and distinct owners.

We just don't use WHOIS or RDAP to expose the data.

**Comment by nic-ml** [comment]
@weppos The presse.ml domains continue to offer domains to different owners, but our domains are not free.

Freenom operates the records directly under .ML.

The other extensions like gouv.ml, com.ml, edu.ml are operated by AGETIC and can be delegated to other organizations.

**Comment by weppos** [comment]
> @weppos Yes.
> 
> Foo.presse.ml belongs to the owner X
> 
> Bar.presse.ml belongs to owner Y
> 
> example.presse.ml belongs to owner Z
> 
> All of our domains belong to different and distinct owners.
> 
> We just don't use WHOIS or RDAP to expose the data.

Then no change is required.

**Comment by nic-ml** [comment]
@weppos is it necessary to re-delegate?

Or

.presse.ml can continue in the same way as it is currently?

Thanks

**Comment by nic-ml** [comment]
@weppos Excuse me. I read your response late.

Thank you for solving the problem!
