### ISSUE TITLE
Clarify expected times for PSL changes to percolate to clients

### ISSUE THREAD

**Issue by sleevi** [publicsuffix/list#957]
In https://github.com/publicsuffix/list/pull/924, eq.edu.au was requested as an 'urgent' removal, but it wasn't clearly communicated that with the PSL, there's no such concept as an 'urgent' removal. That is, while the PSL may update, each individual client will update the PSL at their own update pace, and this may cause challenges, particularly with removals.

For example, https://bugs.chromium.org/p/chromium/issues/detail?id=1048523 was filed against Chrome 80 indicating it was still included, but that was because the removal happened after the window for changes in Chrome 80 to be considered, and won't be considered until the next time the PSL is updated.

While this is broadly addressed in [SAC 070](https://www.icann.org/en/system/files/files/sac-070-en.pdf), it seems it would be useful in either the Guidelines or as part of our bug template to help consumers understand that changes to the PSL may take time to percolate to clients, particularly those [listed on the website](https://publicsuffix.org/learn/). Given that some platforms have incorporated the PSL within the OS itself, updates may not happen until the next OS update.

This issue is not about coming up with solutions for versioning, or even how to reduce that time, but merely to make sure it's clearly documented. For removals, this is particularly important, since we've increasingly seen removals because "Vendor X won't provide service if I'm on the PSL" (for example, wildcard certificates), and understanding that just because the vendor's copy may be updated, clients' copies may not.

**Comment by dnsguru** [comment]
@sleevi should we add this as documentation here?  I don't believe that we have much more within our sphere of control.  As PSL maintainers we cannot really identify or commit to what happens after something is submitted and committed to the list, as it is up to integrators to do their own thing in their derivative use of the PSL.

**Comment by weppos** [comment]
I propose to edit the Homepage
<https://github.com/publicsuffix/list/wiki> (which
is currently quite sad) or the Guidelines
<https://github.com/publicsuffix/list/wiki/Guidelines> to include an
expectation section.

We don't mention anywhere expectations regarding inclusion and propagation
of changes.
We don't as we don't set expectations especially regarding the propagation,
but I agree we should be explicit about it.

-- Simone

**Comment by sleevi** [comment]
@weppos Did you mean edit https://github.com/publicsuffix/publicsuffix.org to make it clear on the home page? The Guidelines seems fine, or even the issue template used when creating a PR

**Comment by dnsguru** [comment]
https://github.com/publicsuffix/list/wiki/Guidelines 

I added
https://github.com/publicsuffix/list/wiki/Guidelines#expectations-on-inclusion-and-propagation

**Comment by weppos** [comment]
Closing as it was addressed as per previous comment.
