### ISSUE TITLE
Remove edugit.org

### ISSUE THREAD

**Issue by Natureshadow** [publicsuffix/list#972]
In the past, the EduGit service from Teckids e.V. used edugit.org for hosting GitLab pages. This was a bug, and the service was now moved to edugit.io.

Please remove edugit.org from the list.

**Comment by weppos** [comment]
@Natureshadow I will need you to open a PR with the removal, as you did for https://github.com/publicsuffix/list/pull/736, so that we can authenticate the request.

Thanks!
