### ISSUE TITLE
Drop deprecated Python library from the list

### ISSUE THREAD

**Issue by nicktimko** [publicsuffix/list#975]
https://publicsuffix.org/learn/ lists under Libraries: "Python: [publicsuffix](https://pypi.org/project/publicsuffix/)". However, the current (1.1.1) release on PyPI has a deprecation warning.

> Please don’t use this module. It is provided for historical reasons only. New code should instead use one of the other libraries that provide similar functionality. For example:
> 
> publicsuffix2 [links to https://pypi.org/project/publicsuffix2/]
> publicsuffixlist [already on the list]

So, can the page be updated to remove the "publicsuffix" or add a "2" on the end (text and link) to replace it with a maintained version?

Meta-note: I don't see where the HTML and such for public-suffix.org lives, so I'm not sure how to just do a direct PR.

**Comment by sleevi** [comment]
Thanks for reporting this!

https://github.com/publicsuffix/publicsuffix.org is for the website if
you’d like to open a PR :)

**Comment by dnsguru** [comment]
Resolved in [PR 22](https://github.com/publicsuffix/publicsuffix.org/pull/22) by @nicktimko **(Thx!)**

Closing
