### ISSUE TITLE
Add no-ip.com domains

### ISSUE THREAD

**Issue by junaariyoshi** [publicsuffix/list#98]
Similar to issue #88 for FreeDNS, the same is needed for no-ip.com and their domains to work with let's encrypt. Although I guess no-ip.com would not have that many entries.

As I'm a customer with them I opened a ticket asking for support...

**Comment by junaariyoshi** [comment]
Arrrrg overlooked the pending pull request: #64 

So I guess this is almost then resolved :-)

**Comment by weppos** [comment]
Duplicate of #64
